/* MessageViewer.h created by stephane on Tue 04-Jul-2000 */

#import <Cocoa/Cocoa.h>

#ifdef SNOW_LEOPARD

#import "MVTerminationHandler.h"

@class MessageMall;
@class TableViewManager;
@class MessageContentController;
@class MailboxesOutlineViewController;
@class ExpandingSplitView;
@class MailVerticalSplitView;
@class ColorBackgroundView;
@class ActivityViewController;
@class ToDoListController;
@class ToDoMall;
@class ToDoListView;
@class MessageViewerLazyPopUpButton;
@class VerticalSplitViewHandle;
@class MailboxPaneBottomView;
@class MailToolbar;
@class MessageViewerSearchField;
@class SplitterAnimation;
@class SearchSliceView;
@class SafeBoolCache;

@protocol MailboxesOutlineViewControllerDelegate <NSObject>
- (void)selectAllMessages;
- (void)focusMessages;
- (long)viewerNumber;
@end

@protocol MessageTransferDelegate <NSObject>
- (void)transfer:(id)arg1 didCompleteWithError:(id)arg2;
- (id)undoManagerForMessageTransfer:(id)arg1;
- (void)hideMessagesForMessageTransfer:(id)arg1;
- (void)unhideMessagesForMessageTransfer:(id)arg1;
- (void)messageTransferDidTransferMessages:(id)arg1;
- (void)messageTransferDidUndoTransferOfMessages:(id)arg1;
@end

@protocol MVMailboxSelectionOwner <NSObject>
- (id)selectedMailboxes;
- (id)selectedMailbox;
- (id)sortedSectionItemsForTimeMachine;
- (BOOL)isSelectedMailboxSpecial;
- (void)selectPathsToMailboxes:(id)arg1;
- (BOOL)mailboxIsExpanded:(id)arg1;
- (BOOL)sectionIsExpanded:(id)arg1;
- (void)revealMailbox:(id)arg1;
- (id)mailboxSelectionWindow;
@end

@protocol MessageViewerSearchFieldFocusDelegate <NSObject>
- (void)searchFieldDidEndSearching:(id)arg1;
@end

@interface MessageViewer : NSResponder <MailboxesOutlineViewControllerDelegate, MessageTransferDelegate, MVMailboxSelectionOwner, NSAnimationDelegate, NSSpeechSynthesizerDelegate, NSSplitViewDelegate, NSUserInterfaceValidations, NSWindowDelegate, MVTerminationHandler>
{
    MessageMall *_messageMall;
    TableViewManager *_tableManager;
    MessageContentController *_contentController;
    MailboxesOutlineViewController *_outlineViewController;
    NSWindow *_window;
    ExpandingSplitView *_splitView;
    NSScrollView *_messageListScrollView;
    MailVerticalSplitView *_verticalSplitView;
    ColorBackgroundView *_viewerContainer;
    ColorBackgroundView *_mailboxesView;
    ActivityViewController *_activityViewController;
    NSToolbarItem *_searchViewItem;
    NSString *_lastSearchPhrase;
    NSString *_searchPhrase;
    int _currentSearchArea;
    int _currentSearchField;
    int _currentSearchTarget;
    int _selectedTag;
    BOOL _userChangedSliceView;
    NSMenu *_tableHeaderMenu;
    ToDoListController *_toDoController;
    ToDoMall *_toDoMall;
    NSScrollView *_toDoScrollView;
    ToDoListView *_toDoListView;
    NSMenu *_toDoColumnsMenu;
    NSMenu *_toDoSortByMenu;
    NSMenu *_messageColumnsMenu;
    NSMenu *_messageSortByMenu;
    NSMenuItem *_columnsMenuItem;
    NSMenuItem *_sortByMenuItem;
    BOOL _toDoListViewIsShowing;
    BOOL _previewPaneWasVisibleWhenToDoListWasShown;
    NSArray *_toDoMailboxes;
    MessageViewerLazyPopUpButton *newMailboxButton;
    NSButton *activityToggleButton;
    MessageViewerLazyPopUpButton *actionButton;
    VerticalSplitViewHandle *verticalSplitViewHandle;
    MailboxPaneBottomView *mailboxPaneBottomView;
    BOOL _shouldPreventTableViewResize;
    BOOL _shouldMakeTableViewSelectionVisible;
    BOOL _shouldMakeMessageSelectionVisible;
    BOOL _showingDefaultSearchString;
    BOOL _updatingSearchField;
    BOOL _allowShowingDeletedMessages;
    BOOL _suppressWindowTitleUpdates;
    BOOL _didSetupUI;
    BOOL _isObservingFirstResponder;
    float _restoreMailboxPaneToWidthAfterDragOperation;
    float _lastSplitViewPosition;
    float _lastMailboxSplitPosition;
    float _lastDragXPosition;
    NSArray *_mailboxesToDisplayWhenVisible;
    NSString *_stringToSearchWhenVisible;
    BOOL _shouldCascadeWhenShowing;
    MailToolbar *_toolbar;
    NSMutableDictionary *_toolbarItems;
    MessageViewerSearchField *_searchField;
    NSDictionary *_savedDefaults;
    NSMutableArray *_noteDocumentEditorsForPlainTextTransfer;
    NSArray *_messagesToDeleteAfterPlainTextTransferHasCompleted;
    BOOL _pendingPlainTextTransfers;
    unsigned int _numberOfPendingPlainTextTransfers;
    unsigned int _viewerNumber;
    NSMutableArray *_transferOperations;
    NSDictionary *_plainTextTransferParameters;
    float _splitViewPositionBeforeSearch;
    SplitterAnimation *_animation;
    SearchSliceView *_searchSliceView;
    SafeBoolCache *_atLeastOneSelectedMessageIsInOutboxCache;
    SafeBoolCache *_atLeastOneSelectedMessageIsInDraftsCache;
    SafeBoolCache *_canCreateToDoCache;
    NSNumber *_uniqueID;
}

+ (void)initialize;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)allMessageViewers;
+ (id)allSingleMessageViewers;
+ (id)existingViewerForStore:(id)arg1;
+ (id)existingViewerForMailboxUid:(id)arg1;
+ (id)_mailboxUidForTag:(unsigned long)arg1;
+ (id)newViewerForMailboxWithTag:(unsigned long)arg1;
+ (id)existingViewerShowingMessage:(id)arg1;
+ (void)registerNewViewer:(id)arg1;
+ (void)deregisterViewer:(id)arg1;
+ (void)showAllViewers;
+ (id)mailboxUidsBeingViewed;
+ (id)frontmostMessageViewer;
+ (void)searchForString:(id)arg1;
+ (unsigned long)firstAvailableViewerNumber;
+ (id)_mailboxUidsForPaths:(id)arg1;
+ (unsigned long)deleteOperationForEvent:(id)arg1 isKeyPressed:(BOOL)arg2;
+ (void)saveAllViewersToDefaultsWithDelay;
+ (void)saveAllViewersToDefaultsWithNotification:(id)arg1;
+ (void)saveAllViewersToDefaults;
+ (void)saveAllViewersToDefaultsOmittingViewer:(id)arg1;
+ (BOOL)restoreAllViewersFromDefaults;
+ (void)willRestoreAllViewersFromDefaults;
+ (void)didRestoreAllViewersFromDefaults;
+ (BOOL)isRestoringViewersFromDefaults;
+ (id)messageViewersByUniqueID;
- (unsigned long)viewerNumber;
- (void)revealMessage:(id)arg1;
- (void)revealCurrentMessage;
- (void)_displayFollowup:(id)arg1;
- (void)_cantFindFollowupToMessage:(id)arg1;
- (void)showFollowupsToMessage:(id)arg1;
- (id)_mailboxUidsFromDefaults:(id)arg1;
- (id)initWithSavedDefaults:(id)arg1;
- (void)intializeLazyPopUpButtons;
- (id)init;
- (id)plainInit;
- (id)initWithMailboxUids:(id)arg1;
- (void)dealloc;
- (void)release;
- (void)_registerForApplicationNotifications;
- (void)_unregisterForApplicationNotifications;
- (void)_registerForStoreNotifications;
- (void)_unregisterForStoreNotifications;
- (void)storeBeingInvalidated:(id)arg1;
- (id)_store;
- (void)_setStore:(id)arg1;
- (BOOL)_selectedMailboxesAreOutgoing:(char *)arg1;
- (BOOL)_isViewingMailboxUid:(id)arg1;
- (BOOL)_isShowingMessage:(id)arg1;
- (id)window;
- (void)show;
- (void)showAndMakeKey:(BOOL)arg1;
- (void)_setupUIAndOrderFront:(BOOL)arg1 andMakeKey:(BOOL)arg2;
- (id)tableHeaderViewGetDefaultMenu:(id)arg1;
- (id)_toDoController;
- (void)_setUpWindowContents;
- (void)_setupMailboxOutlineView;
- (void)_setupNextKeyViewLoop;
- (void)_setUpMenus;
- (void)takeOverAsSelectionOwner;
- (void)resignAsSelectionOwner;
- (void)windowDidBecomeMain:(id)arg1;
- (void)nowWouldBeAGoodTimeToTerminate:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)windowWillMiniaturize:(id)arg1;
- (void)openMailboxesPaneToWidth:(float)arg1 byAnimating:(BOOL)arg2;
- (float)mailboxesPaneWidth;
- (BOOL)mailboxesPaneIsOpen;
- (BOOL)mailboxesPaneIsOpenWideEnoughToUse;
- (void)_enableSplitViewAutosaving;
- (void)_disableSplitViewAutosaving;
- (void)splitViewDidResizeSubviews:(id)arg1;
- (void)splitViewWillResizeSubviews:(id)arg1;
- (struct CGRect)splitView:(id)arg1 additionalEffectiveRectOfDividerAtIndex:(long)arg2;
- (BOOL)splitView:(id)arg1 shouldCollapseSubview:(id)arg2 forDoubleClickOnDividerAtIndex:(long)arg3;
- (void)toggleMailboxesPane:(id)arg1;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (float)splitView:(id)arg1 constrainMinCoordinate:(float)arg2 ofSubviewAt:(long)arg3;
- (float)maxMailboxesViewWidthAllowed;
- (float)idealMailboxesViewWidth;
- (float)splitView:(id)arg1 constrainMaxCoordinate:(float)arg2 ofSubviewAt:(long)arg3;
- (void)updateMailboxButtonVisibility;
- (float)splitView:(id)arg1 constrainSplitPosition:(float)arg2 ofSubviewAt:(long)arg3;
- (id)selectedMailboxes;
- (id)selectedMailbox:(BOOL)arg1;
- (id)selectedMailbox;
- (BOOL)isSelectedMailboxSpecial;
- (void)selectPathsToMailboxes:(id)arg1;
- (BOOL)mailboxIsExpanded:(id)arg1;
- (BOOL)sectionIsExpanded:(id)arg1;
- (id)expandedItems;
- (id)sortedSectionItemsForTimeMachine;
- (void)revealMailbox:(id)arg1;
- (id)mailboxSelectionWindow;
- (void)setSelectedMailboxes:(id)arg1;
- (id)selectedMessages;
- (void)setSelectedMessages:(id)arg1;
- (id)currentDisplayedMessage;
- (void)outlineViewDoubleClick:(id)arg1;
- (void)selectMailbox:(id)arg1;
- (void)_openBrowserForMessages:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)keyUp:(id)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)_mailboxWasRenamed:(id)arg1;
- (void)mailboxSelectionChanged:(id)arg1;
- (void)_mallDidOpen;
- (void)_mallStructureDidChange;
- (void)_accountsDidChange:(id)arg1;
- (void)_mailboxesDidChange:(id)arg1;
- (void)_selectNextMessage:(id)arg1;
- (void)smartMailboxCriteriaChanged:(id)arg1;
- (void)_setMailboxUids:(id)arg1;
- (BOOL)_selectionContainsMessagesWithDeletedStatusEqualTo:(BOOL)arg1;
- (BOOL)_selectionContainsMessagesWithReadStatusEqualTo:(BOOL)arg1;
- (BOOL)_selectionContainsMessagesWithFlaggedStatusEqualTo:(BOOL)arg1;
- (BOOL)_selectionContainsMessagesWithJunkMailLevelEqualTo:(int)arg1;
- (BOOL)_selectionContainsMessagesWithAttachments;
- (BOOL)atLeastOneSelectedMessageIsInOutbox:(id)arg1;
- (BOOL)_updatedAtLeastOneSelectedMessageIsInOutbox:(id)arg1;
- (BOOL)atLeastOneSelectedMessageIsInDrafts:(id)arg1;
- (BOOL)_updatedAtLeastOneSelectedMessageIsInDrafts:(id)arg1;
- (BOOL)shouldDeleteMessagesGivenCurrentState;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)canCreateToDo;
- (BOOL)_updatedCanCreateToDo:(id)arg1;
- (BOOL)validateUserInterfaceItemForToDoList:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)_removeAccessibilityLinks;
- (void)messageWasDisplayedInTextView:(id)arg1;
- (void)messageNoLongerDisplayedInTextView:(id)arg1;
- (void)messageThreadSummaryWasDisplayedInTextView:(id)arg1;
- (void)checkNewMail:(id)arg1;
- (void)replyMessage:(id)arg1;
- (void)replyAllMessage:(id)arg1;
- (void)replyToSender:(id)arg1;
- (void)replyToOriginalSender:(id)arg1;
- (void)showComposeWindow:(id)arg1;
- (BOOL)_showEditorForNote:(id)arg1;
- (void)showNoteEditor:(id)arg1;
- (void)showAddressPanel:(id)arg1;
- (void)undeleteMessages:(id)arg1;
- (void)deleteMessages:(id)arg1;
- (void)deleteMessagesAllowingMoveToTrash:(BOOL)arg1;
- (void)openMessages:(id)arg1;
- (void)_openMessages:(id)arg1 withModifiers:(unsigned long)arg2;
- (void)selectAllMessages;
- (void)focusMessages;
- (void)focusMailboxes;
- (void)focusMessage;
- (void)replyViaIM:(id)arg1;
- (void)showAccountInfo:(id)arg1;
- (id)tableManager;
- (id)mailboxesOutlineViewController;
- (id)contentController;
- (void)jumpToSelection:(id)arg1;
- (id)editorWithType:(int)arg1;
- (void)redirectMessage:(id)arg1;
- (void)forwardMessage:(id)arg1;
- (void)forwardAsAttachment:(id)arg1;
- (void)showToDoReferencedMessageInNewWindow:(id)arg1;
- (void)showToDoInList:(id)arg1;
- (id)currentSingleSelectedToDoMailbox;
- (id)displaySelectedMessageInSeparateWindow:(id)arg1;
- (id)_displaySelectedMessageInSeparateWindow:(id)arg1 withModifiers:(unsigned long)arg2;
- (void)_openMessageInWebBrowser:(id)arg1;
- (void)renameMailbox:(id)arg1;
- (void)moveMessagesToMailbox:(id)arg1;
- (void)copyMessagesToMailbox:(id)arg1;
- (id)_selectedMessagesWhoseFlag:(unsigned long)arg1 isEqualToState:(BOOL)arg2;
- (void)_changeFlag:(id)arg1 state:(BOOL)arg2 forMessages:(id)arg3 undoActionName:(id)arg4;
- (void)markAsRead:(id)arg1;
- (void)markAsUnread:(id)arg1;
- (void)markAsReadFromToolbar:(id)arg1;
- (void)markAsUnreadFromToolbar:(id)arg1;
- (void)markAsUnflagged:(id)arg1;
- (void)markAsFlagged:(id)arg1;
- (void)markAsFlaggedFromToolbar:(id)arg1;
- (void)markAsUnflaggedFromToolbar:(id)arg1;
- (void)changeColor:(id)arg1;
- (void)rebuildTableOfContents:(id)arg1;
- (void)_putMessageDataOntoPasteboard:(id)arg1 attributedString:(id)arg2 shouldDelete:(id)arg3 pasteboardType:(id)arg4;
- (void)_copyMessagesToPasteboard:(id)arg1 deleteWhenCopied:(BOOL)arg2 pasteboardType:(id)arg3 alternateType:(id)arg4;
- (void)_progressAlertDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)_showActivityProgressPanelForCopy:(id)arg1;
- (BOOL)_doCopy:(id)arg1 deleteWhenCopied:(BOOL)arg2;
- (void)copy:(id)arg1;
- (void)cut:(id)arg1;
- (int)pasteMessages:(id)arg1 todosByMessage:(id)arg2 unsuccessfulMessages:(id)arg3 flagsToSet:(id)arg4 destinationAccount:(id)arg5 destinationStore:(id)arg6;
- (void)addToDosFromDictionary:(id)arg1 forMessages:(id)arg2 newDocumentIDsByOld:(id)arg3 destinationAccount:(id)arg4;
- (void)_pasteData:(id)arg1 pasteboardType:(id)arg2 alternateData:(id)arg3 alternateType:(id)arg4 destination:(id)arg5;
- (void)paste:(id)arg1;
- (void)startSpeaking:(id)arg1;
- (void)stopSpeaking:(id)arg1;
- (void)speechSynthesizer:(id)arg1 didFinishSpeaking:(BOOL)arg2;
- (void)showPrintPanel:(id)arg1;
- (BOOL)send:(id)arg1 forDraft:(BOOL)arg2 actualMessage:(id)arg3;
- (BOOL)send:(id)arg1 forDraft:(BOOL)arg2;
- (BOOL)send:(id)arg1;
- (void)batchSendSheetDidEnd:(id)arg1 returnCode:(long)arg2 context:(void *)arg3;
- (void)saveAs:(id)arg1;
- (void)saveAllAttachments:(id)arg1;
- (void)quickLookSelectedAttachments:(id)arg1;
- (BOOL)acceptsPreviewPanelControl:(id)arg1;
- (void)beginPreviewPanelControl:(id)arg1;
- (void)endPreviewPanelControl:(id)arg1;
- (id)_criterionForMailbox:(id)arg1;
- (id)mailboxSearchCriterionForScope:(int)arg1 containsSentMailbox:(char *)arg2 containsTrashMailbox:(char *)arg3 shouldExcludeJunk:(char *)arg4;
- (void)searchIndex:(id)arg1;
- (BOOL)_isShowingSearchResults;
- (unsigned long)_searchResultCount;
- (BOOL)_canSaveSearchWithTarget:(int)arg1;
- (BOOL)_canSearchSelectedMailboxes;
- (void)_showSearchSliceView;
- (void)_hideSearchSliceViewByAnimating:(BOOL)arg1;
- (void)_searchForString:(id)arg1;
- (id)searchPhrase;
- (void)setSearchPhrase:(id)arg1;
- (void)_updateSearchStatus;
- (void)_clearSearchByAnimating:(BOOL)arg1;
- (void)clearSearch:(id)arg1;
- (void)setupSearchParametersForTag:(long)arg1;
- (int)searchField;
- (int)searchTarget;
- (int)searchArea;
- (void)_handleAttachmentsRemovedFromMessages:(id)arg1 newMessages:(id)arg2;
- (void)_removeAttachmentsFromMessages:(id)arg1 fromStores:(id)arg2;
- (void)removeAttachments:(id)arg1;
- (void)scrollBodyToShowToDo:(id)arg1;
- (id)todoTextFromDisplaySelection;
- (BOOL)createToDoWithViewAsKey:(id)arg1;
- (void)_selectAndRevealToDoMailboxForAccount:(id)arg1;
- (id)firstCreateToDoResponder;
- (void)createToDo:(id)arg1;
- (void)sortByTagOfSender:(id)arg1;
- (void)focus:(id)arg1;
- (void)unfocus:(id)arg1;
- (void)openAllThreads:(id)arg1;
- (void)closeAllThreads:(id)arg1;
- (void)toggleThreadedMode:(id)arg1;
- (void)selectThread:(id)arg1;
- (void)selectPreviousInThread:(id)arg1;
- (void)selectNextInThread:(id)arg1;
- (void)showDeletions:(id)arg1;
- (void)hideDeletions:(id)arg1;
- (void)showCompletedToDos:(id)arg1;
- (void)hideCompletedToDos:(id)arg1;
- (void)toggleContentsColumn:(id)arg1;
- (void)toggleMessageNumbersColumn:(id)arg1;
- (void)toggleMessageFlagsColumn:(id)arg1;
- (void)toggleFromColumn:(id)arg1;
- (void)togglePresenceColumn:(id)arg1;
- (void)toggleToColumn:(id)arg1;
- (void)toggleDateSentColumn:(id)arg1;
- (void)toggleDateReceivedColumn:(id)arg1;
- (void)toggleLocationColumn:(id)arg1;
- (void)toggleAuthorColumn:(id)arg1;
- (void)toggleSizeColumn:(id)arg1;
- (void)writeDefaultsToArray:(id)arg1;
- (id)dictionaryRepresentation;
- (void)_findSomeDefaultsIfNecessary;
- (void)_setupFromDefaults;
- (id)_viewerDefaultsKeyFormats;
- (void)_teardownDefaults;
- (void)_copyDefaultsFromViewerNumber:(unsigned long)arg1 toViewerNumber:(unsigned long)arg2;
- (id)_countStringForType:(BOOL)arg1 isDrafts:(BOOL)arg2 omitUnread:(BOOL)arg3 totalCount:(unsigned int *)arg4;
- (void)_messageUpdated:(id)arg1;
- (void)_documentsTransferred:(id)arg1;
- (void)_updateWindowTitle;
- (void)_reallyUpdateWindowTitle;
- (void)_updateMallUids:(id)arg1;
- (id)_currentMessageManager;
- (void)_setSplitViewPercentage:(float)arg1 animate:(BOOL)arg2;
- (void)animationDidEnd:(id)arg1;
- (void)messageWasSelected:(id)arg1 fromMessageBrowserController:(id)arg2;
- (void)scrollCurrentlySelectedMessageToTop;
- (void)selectedMessagesDidChange;
- (void)messageWasDoubleClicked:(id)arg1;
- (void)messageBrowserView:(id)arg1 willStartDragWithEvent:(id)arg2;
- (void)draggedImage:(id)arg1 movedTo:(struct CGPoint)arg2;
- (void)messageBrowserViewDidEndDragging:(id)arg1;
- (BOOL)transferSelectedMessagesToMailbox:(id)arg1 deleteOriginals:(BOOL)arg2;
- (void)_transferSelectedMessagesToExchangeMailboxAlertDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(id)arg3;
- (void)noteDocumentEditorHasInitialized:(id)arg1;
- (void)_transferPlainTextCopiesOfMessagesWithParameters:(id)arg1;
- (id)_alertForConvertingToPlainTextNote;
- (id)_alertForConvertingToPlainTextNoteWithTodo;
- (BOOL)deleteMessages:(id)arg1 allowMoveToTrash:(BOOL)arg2 allowUndo:(BOOL)arg3;
- (void)_reallyAnimateProgressInidicator;
- (void)_updateSearchStatusWithDelay;
- (void)threadDidExpand;
- (void)threadDidCollapse;
- (void)clearUndoRedoStacksUnconditionally:(BOOL)arg1;
- (void)searchWillStart;
- (void)searchDidFinish;
- (void)searchDidUpdate;
- (id)selectedMailboxUids;
- (void)performSearch:(id)arg1;
- (void)saveSearch:(id)arg1;
- (void)reapplySortingRules:(id)arg1;
- (void)_returnToSenderSheetDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)_deleteMessagesAfterBounce:(id)arg1;
- (void)_bounceMessages:(id)arg1;
- (void)returnToSender:(id)arg1;
- (void)addSenderToAddressBook:(id)arg1;
- (void)markAsJunkMail:(id)arg1;
- (void)markMessagesAsJunkMail:(id)arg1 stores:(id)arg2;
- (void)_deleteJunkedMessages:(id)arg1 inStores:(id)arg2 moveToTrash:(BOOL)arg3;
- (void)synchronouslyMarkAsJunkMail:(id)arg1 inStores:(id)arg2 delete:(BOOL)arg3;
- (void)undoMarkMessagesAsJunkMail:(id)arg1 stores:(id)arg2;
- (void)markAsNotJunkMail:(id)arg1;
- (void)markMessagesAsNotJunkMail:(id)arg1 stores:(id)arg2;
- (void)synchronouslyMarkAsNotJunkMail:(id)arg1 inStores:(id)arg2;
- (BOOL)_transferMessages:(id)arg1 toMailbox:(id)arg2 deleteOriginals:(BOOL)arg3 allowUndo:(BOOL)arg4 isDeleteOperation:(BOOL)arg5;
- (void)_reportError:(id)arg1;
- (void)transfer:(id)arg1 didCompleteWithError:(id)arg2;
- (void)hideMessagesForMessageTransfer:(id)arg1;
- (void)unhideMessagesForMessageTransfer:(id)arg1;
- (void)messageTransferDidTransferMessages:(id)arg1;
- (void)messageTransferDidUndoTransferOfMessages:(id)arg1;
- (id)undoManagerForMessageTransfer:(id)arg1;
- (void)_updateSearchItemLabel;
- (void)createUniqueID;

@end

@interface MessageViewer (TimeMachine)
- (id)toolbarConfigurationDict;
- (float)mailboxesPaneWidth;
- (float)previewSplitPercentage;
@end

@interface MessageViewer (AppleScript)
+ (id)messageViewerForUniqueID:(id)arg1;
- (id)uniqueID;
- (id)objectSpecifier;
- (id)allMessages;
- (id)focusedMessages;
- (void)setFocusedMessages:(id)arg1;
- (int)appleScriptSortColumn;
- (void)setAppleScriptSortColumn:(int)arg1;
- (BOOL)isSortedAscending;
- (void)setIsSortedAscending:(BOOL)arg1;
- (BOOL)previewPaneVisible;
- (void)setPreviewPaneVisible:(BOOL)arg1;
- (id)visibleColumns;
- (void)setVisibleColumns:(id)arg1;
- (id)inbox;
- (id)outbox;
- (id)draftsMailbox;
- (id)sentMailbox;
- (id)trashMailbox;
- (id)junkMailbox;
- (void)setScriptingProperties:(id)arg1;
@end

@interface MessageViewer (MessageViewerToolbar) <MessageViewerSearchFieldFocusDelegate, NSToolbarDelegate>
- (void)setupToolbar;
- (BOOL)validateToolbarItem:(id)arg1;
- (id)previousIdentifierForUpgradingToolbar:(id)arg1;
- (id)toolbar:(id)arg1 upgradedItemIdentifiers:(id)arg2;
- (void)configureSegmentedItem:(id)arg1 withDictionary:(id)arg2 forSegment:(long)arg3;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (void)_updateToolbar;
- (void)toolbarWillAddItem:(id)arg1;
- (void)toolbarDidRemoveItem:(id)arg1;
- (void)toolbarDidReorderItem:(id)arg1;
- (void)ensureSearchFieldVisibilityInToolbar;
- (void)searchFieldDidEndSearching:(id)arg1;
@end


#elif defined(LEOPARD)

@class MessageMall;
@class TableViewManager;
@class MessageContentController;
@class MailboxesOutlineViewController;
@class ExpandingSplitView;
@class MailVerticalSplitView;
@class ColorBackgroundView;
@class ActivityViewController;
@class SearchTextField;
@class ToDoListController;
@class ToDoMall;
@class ToDoListView;
@class MessageViewerLazyPopUpButton;
@class VerticalSplitViewHandle;
@class MailboxPaneBottomView;
@class SplitterAnimation;
@class SearchSliceView;
@class ActivityViewController;
@class ToDoListController;
@class ToDoListView;
@class ToDoMall;

@protocol MVMailboxSelectionOwner
- (id)selectedMailboxes;
- (id)selectedMailbox;
- (id)sortedSectionItemsForTimeMachine;
- (BOOL)isSelectedMailboxSpecial;
- (void)selectPathsToMailboxes:(id)fp8;
- (BOOL)mailboxIsExpanded:(id)fp8;
- (BOOL)sectionIsExpanded:(id)fp8;
- (void)revealMailbox:(id)fp8;
- (id)mailboxSelectionWindow;
@end

@protocol MailboxesOutlineViewControllerDelegate
- (void)selectAllMessages;
- (void)focusMessages;
@end

@interface MessageViewer : NSResponder <MVMailboxSelectionOwner, MailboxesOutlineViewControllerDelegate>
{
    MessageMall *_messageMall;
    TableViewManager *_tableManager;
    MessageContentController *_contentController;
    MailboxesOutlineViewController *_outlineViewController;
    NSWindow *_window;
    ExpandingSplitView *_splitView;
    NSScrollView *_messageListScrollView;
    MailVerticalSplitView *_verticalSplitView;
    ColorBackgroundView *_viewerContainer;
    ColorBackgroundView *_mailboxesView;
    ActivityViewController *_activityViewController;
    SearchTextField *_searchField;
    NSView *_searchFieldView;
    NSToolbarItem *_searchViewItem;
    NSString *_lastSearchPhrase;
    int _currentSearchArea;
    int _currentSearchField;
    int _currentSearchTarget;
    int _selectedTag;
    BOOL _userChangedSliceView;
    NSMenu *_tableHeaderMenu;
    ToDoListController *_toDoController;
    ToDoMall *_toDoMall;
    NSScrollView *_toDoScrollView;
    ToDoListView *_toDoListView;
    NSMenu *_toDoColumnsMenu;
    NSMenu *_toDoSortByMenu;
    NSMenu *_messageColumnsMenu;
    NSMenu *_messageSortByMenu;
    NSMenuItem *_columnsMenuItem;
    NSMenuItem *_sortByMenuItem;
    BOOL _toDoListViewIsShowing;
    BOOL _previewPaneWasVisibleWhenToDoListWasShown;
    NSArray *_toDoMailboxes;
    MessageViewerLazyPopUpButton *newMailboxButton;
    MessageViewerLazyPopUpButton *actionButton;
    VerticalSplitViewHandle *verticalSplitViewHandle;
    MailboxPaneBottomView *mailboxPaneBottomView;
    BOOL _shouldPreventTableViewResize;
    BOOL _shouldMakeTableViewSelectionVisible;
    BOOL _shouldMakeMessageSelectionVisible;
    BOOL _showingDefaultSearchString;
    BOOL _updatingSearchField;
    BOOL _allowShowingDeletedMessages;
    BOOL _suppressWindowTitleUpdates;
    BOOL _didSetupUI;
    float _restoreMailboxPaneToWidthAfterDragOperation;
    float _lastSplitViewPosition;
    float _lastMailboxSplitPosition;
    float _lastDragXPosition;
    NSArray *_mailboxesToDisplayWhenVisible;
    NSToolbar *_toolbar;
    NSMutableDictionary *_toolbarItems;
    NSDictionary *_savedDefaults;
    NSMutableArray *_transferOperations;
    NSMutableDictionary *_viewerContents;
    float _splitViewPositionBeforeSearch;
    SplitterAnimation *_animation;
    SearchSliceView *_searchSliceView;
    BOOL _updatingToolbar;
    float _mailboxesViewWidthAtLastToolbarUpdate;
}

+ (void)initialize;
+ (id)allMessageViewers;
+ (id)allSingleMessageViewers;
+ (id)existingViewerForStore:(id)fp8;
+ (id)existingViewerForMailboxUid:(id)fp8;
+ (id)existingViewerForMessage:(id)fp8;
+ (id)_mailboxUidForTag:(unsigned int)fp8;
+ (id)newViewerForMailboxWithTag:(unsigned int)fp8;
+ (id)existingViewerShowingMessage:(id)fp8;
+ (void)registerNewViewer:(id)fp8;
+ (void)deregisterViewer:(id)fp8;
+ (void)showAllViewers;
+ (id)mailboxUidsBeingViewed;
+ (id)frontmostMessageViewer;
+ (void)searchForString:(id)fp8;
+ (id)_mailboxUidsForPaths:(id)fp8;
+ (void)saveDefaultsWithDelay;
+ (void)saveDefaults;
+ (void)restoreFromDefaults;
- (void)revealMessage:(id)fp8;
- (void)revealCurrentMessage;
- (void)_displayFollowup:(id)fp8;
- (void)_cantFindFollowupToMessage:(id)fp8;
- (void)showFollowupsToMessage:(id)fp8;
- (id)_mailboxUidsFromDefaults:(id)fp8;
- (id)initWithSavedDefaults:(id)fp8;
- (void)intializeLazyPopUpButtons;
- (id)init;
- (id)plainInit;
- (id)initWithMailboxUids:(id)fp8;
- (void)dealloc;
- (void)_registerForApplicationNotifications;
- (void)_unregisterForApplicationNotifications;
- (void)_registerForStoreNotifications;
- (void)_unregisterForStoreNotifications;
- (void)storeBeingInvalidated:(id)fp8;
- (void)_setStore:(id)fp8;
- (BOOL)_isViewingMailboxUid:(id)fp8;
- (BOOL)_isViewingMessage:(id)fp8;
- (BOOL)_isShowingMessage:(id)fp8;
- (id)window;
- (void)show;
- (void)showAndMakeKey:(BOOL)fp8;
- (void)_setupUIAndOrderFront:(BOOL)fp8 andMakeKey:(BOOL)fp12;
- (id)tableHeaderViewGetDefaultMenu:(id)fp8;
- (id)_toDoController;
- (void)_setUpWindowContents;
- (void)_setupMailboxOutlineView;
- (void)_setupNextKeyViewLoop;
- (void)_setUpMenus;
- (void)takeOverAsSelectionOwner;
- (void)resignAsSelectionOwner;
- (void)windowDidBecomeMain:(id)fp8;
- (void)nowWouldBeAGoodTimeToTerminate:(id)fp8;
- (BOOL)windowShouldClose:(id)fp8;
- (void)windowWillMiniaturize:(id)fp8;
- (void)openMailboxesPaneToWidth:(float)fp8 byAnimating:(BOOL)fp12;
- (BOOL)mailboxesPaneIsOpen;
- (BOOL)mailboxesPaneIsOpenWideEnoughToUse;
- (void)splitViewDidResizeSubviews:(id)fp8;
- (void)splitViewWillResizeSubviews:(id)fp8;
- (void)dividerDidEndDragSession:(id)fp8;
- (void)splitViewDoubleClickedOnDivider:(id)fp8;
- (void)toggleMailboxesPane:(id)fp8;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (BOOL)splitView:(id)fp8 canCollapseSubview:(id)fp12;
- (float)splitView:(id)fp8 constrainMinCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)maxMailboxesViewWidthAllowed;
- (float)idealMailboxesViewWidth;
- (void)updateMailboxButtonVisibilityForWidth:(float)fp8;
- (float)splitView:(id)fp8 constrainSplitPosition:(float)fp12 ofSubviewAt:(int)fp16;
- (id)selectedMailboxes;
- (id)selectedMailbox:(BOOL)fp8;
- (id)selectedMailbox;
- (BOOL)isSelectedMailboxSpecial;
- (void)selectPathsToMailboxes:(id)fp8;
- (BOOL)mailboxIsExpanded:(id)fp8;
- (BOOL)sectionIsExpanded:(id)fp8;
- (id)expandedItems;
- (id)sortedSectionItemsForTimeMachine;
- (void)revealMailbox:(id)fp8;
- (id)mailboxSelectionWindow;
- (void)setSelectedMailboxes:(id)fp8;
- (id)selectedMessages;
- (void)setSelectedMessages:(id)fp8;
- (id)currentDisplayedMessage;
- (void)outlineViewDoubleClick:(id)fp8;
- (void)selectMailbox:(id)fp8;
- (void)_openBrowserForMessages:(id)fp8;
- (void)keyDown:(id)fp8;
- (void)keyUp:(id)fp8;
- (void)swipeWithEvent:(id)fp8;
- (void)_mailboxWasRenamed:(id)fp8;
- (void)mailboxSelectionChanged:(id)fp8;
- (void)_mallDidOpen;
- (void)_mallStructureDidChange;
- (void)_accountsDidChange:(id)fp8;
- (void)smartMailboxCriteriaChanged:(id)fp8;
- (void)_setMailboxUids:(id)fp8;
- (BOOL)_selectionContainsMessagesWithDeletedStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithReadStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithFlaggedStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithJunkMailLevelEqualTo:(int)fp8;
- (BOOL)_selectionContainsMessagesWithAttachments;
- (BOOL)atLeastOneSelectedMessageIsInOutbox:(id)fp8;
- (BOOL)atLeastOneSelectedMessageIsInDrafts:(id)fp8;
- (BOOL)_validateActionForToDoList:(SEL)fp8 tag:(int)fp12;
- (BOOL)_validateAction:(SEL)fp8 tag:(int)fp12;
- (BOOL)validateMenuItem:(id)fp8;
- (void)messageWasDisplayedInTextView:(id)fp8;
- (void)messageThreadSummaryWasDisplayedInTextView:(id)fp8;
- (void)checkNewMail:(id)fp8;
- (void)replyMessage:(id)fp8;
- (void)replyAllMessage:(id)fp8;
- (void)replyToSender:(id)fp8;
- (void)replyToOriginalSender:(id)fp8;
- (void)showComposeWindow:(id)fp8;
- (BOOL)_showEditorForNote:(id)fp8;
- (void)showNoteEditor:(id)fp8;
- (void)showAddressPanel:(id)fp8;
- (void)toggleAttachmentsArea:(id)fp8;
- (void)undeleteMessages:(id)fp8;
- (void)deleteMessages:(id)fp8;
- (void)deleteMessagesAllowingMoveToTrash:(BOOL)fp8;
- (void)openMessages:(id)fp8;
- (void)selectAllMessages;
- (void)focusMessages;
- (void)focusMailboxes;
- (void)focusMessage;
- (void)replyViaIM:(id)fp8;
- (void)showAccountInfo:(id)fp8;
- (id)tableManager;
- (id)mailboxesOutlineViewController;
- (void)jumpToSelection:(id)fp8;
- (id)editorWithType:(int)fp8;
- (void)redirectMessage:(id)fp8;
- (void)forwardMessage:(id)fp8;
- (void)forwardAsAttachment:(id)fp8;
- (void)showToDoReferencedMessageInNewWindow:(id)fp8;
- (void)showToDoInList:(id)fp8;
- (id)currentSingleSelectedToDoMailbox;
- (void)displaySelectedMessageInSeparateWindow:(id)fp8;
- (void)renameMailbox:(id)fp8;
- (void)moveMessagesToMailbox:(id)fp8;
- (void)copyMessagesToMailbox:(id)fp8;
- (id)_selectedMessagesWhoseFlag:(unsigned long)fp8 isEqualToState:(BOOL)fp12;
- (void)_changeFlag:(id)fp8 state:(BOOL)fp12 forMessages:(id)fp16 undoActionName:(id)fp20;
- (void)markAsRead:(id)fp8;
- (void)markAsUnread:(id)fp8;
- (void)markAsReadFromToolbar:(id)fp8;
- (void)markAsUnreadFromToolbar:(id)fp8;
- (void)markAsUnflagged:(id)fp8;
- (void)markAsFlagged:(id)fp8;
- (void)markAsFlaggedFromToolbar:(id)fp8;
- (void)markAsUnflaggedFromToolbar:(id)fp8;
- (void)changeColor:(id)fp8;
- (void)rebuildTableOfContents:(id)fp8;
- (void)_putMessageDataOntoPasteboard:(id)fp8 attributedString:(id)fp12 shouldDelete:(id)fp16 pasteboardType:(id)fp20;
- (void)_copyMessagesToPasteboard:(id)fp8 deleteWhenCopied:(BOOL)fp12 pasteboardType:(id)fp16 alternateType:(id)fp20;
- (void)_progressAlertDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_showActivityProgressPanelForCopy:(id)fp8;
- (BOOL)_doCopy:(id)fp8 deleteWhenCopied:(BOOL)fp12;
- (void)copy:(id)fp8;
- (void)cut:(id)fp8;
- (int)pasteMessages:(id)fp8 todosByMessage:(id)fp12 unsuccessfulMessages:(id)fp16 flagsToSet:(id)fp20 destinationAccount:(id)fp24 destinationStore:(id)fp28;
- (void)addToDosFromDictionary:(id)fp8 forMessages:(id)fp12 newDocumentIDsByOld:(id)fp16 destinationAccount:(id)fp20;
- (void)_pasteData:(id)fp8 pasteboardType:(id)fp12 alternateData:(id)fp16 alternateType:(id)fp20 destination:(id)fp24;
- (void)paste:(id)fp8;
- (void)startSpeaking:(id)fp8;
- (void)stopSpeaking:(id)fp8;
- (void)speechSynthesizer:(id)fp8 didFinishSpeaking:(BOOL)fp12;
- (void)showPrintPanel:(id)fp8;
- (BOOL)send:(id)fp8 forDraft:(BOOL)fp12 actualMessage:(id)fp16;
- (BOOL)send:(id)fp8 forDraft:(BOOL)fp12;
- (BOOL)send:(id)fp8;
- (void)saveAs:(id)fp8;
- (void)saveAllAttachments:(id)fp8;
- (void)quickLookSelectedAttachments:(id)fp8;
- (id)defaultSearchString;
- (void)showDefaultSearchString;
- (id)_criterionForMailbox:(id)fp8;
- (id)mailboxSearchCriterionForScope:(int)fp8 containsSentMailbox:(char *)fp12 containsTrashMailbox:(char *)fp16 shouldExcludeJunk:(char *)fp20;
- (void)searchIndex:(id)fp8;
- (BOOL)_isShowingSearchResults;
- (unsigned int)_searchResultCount;
- (BOOL)_canSaveSearchWithTarget:(int)fp8;
- (BOOL)_canSearchSelectedMailboxes;
- (void)_showSearchSliceView;
- (void)_hideSearchSliceViewByAnimating:(BOOL)fp8;
- (void)_searchForString:(id)fp8;
- (void)_updateSearchStatus;
- (void)_clearSearchByAnimating:(BOOL)fp8;
- (void)clearSearch:(id)fp8;
- (void)setupSearchParametersForTag:(int)fp8;
- (int)searchField;
- (int)searchTarget;
- (int)searchArea;
- (void)controlTextDidEndEditing:(id)fp8;
- (void)controlTextDidChange:(id)fp8;
- (void)_removeAttachmentsFromMessages:(id)fp8 fromStores:(id)fp12;
- (void)removeAttachments:(id)fp8;
- (void)scrollBodyToShowToDo:(id)fp8;
- (id)todoTextFromDisplaySelection;
- (BOOL)createToDoWithViewAsKey:(id)fp8;
- (void)_selectAndRevealToDoMailboxForAccount:(id)fp8;
- (id)firstCreateToDoResponder;
- (void)createToDo:(id)fp8;
- (void)sortByTagOfSender:(id)fp8;
- (void)focus:(id)fp8;
- (void)unfocus:(id)fp8;
- (void)openAllThreads:(id)fp8;
- (void)closeAllThreads:(id)fp8;
- (void)toggleThreadedMode:(id)fp8;
- (void)selectThread:(id)fp8;
- (void)selectPreviousInThread:(id)fp8;
- (void)selectNextInThread:(id)fp8;
- (void)showDeletions:(id)fp8;
- (void)hideDeletions:(id)fp8;
- (void)toggleContentsColumn:(id)fp8;
- (void)toggleMessageNumbersColumn:(id)fp8;
- (void)toggleMessageFlagsColumn:(id)fp8;
- (void)toggleFromColumn:(id)fp8;
- (void)togglePresenceColumn:(id)fp8;
- (void)toggleToColumn:(id)fp8;
- (void)toggleDateSentColumn:(id)fp8;
- (void)toggleDateReceivedColumn:(id)fp8;
- (void)toggleLocationColumn:(id)fp8;
- (void)toggleAuthorColumn:(id)fp8;
- (void)toggleSizeColumn:(id)fp8;
- (void)writeDefaultsToArray:(id)fp8;
- (id)_saveDefaults;
- (void)_loadDefaults;
- (void)_setupFromDefaults;
- (id)_countStringForType:(int)fp8 isDrafts:(BOOL)fp12 omitUnread:(BOOL)fp16 totalCount:(unsigned int *)fp20;
- (void)_messageUpdated:(id)fp8;
- (void)_documentsTransferred:(id)fp8;
- (void)_updateWindowTitle;
- (void)_reallyUpdateWindowTitle;
- (void)_updateMallUids:(id)fp8;
- (id)_currentMessageManager;
- (void)_setSplitViewPercentage:(float)fp8 animate:(BOOL)fp12;
- (void)animationDidEnd:(id)fp8;
- (void)messageWasSelected:(id)fp8 fromMessageBrowserController:(id)fp12;
- (void)scrollCurrentlySelectedMessageToTop;
- (void)messageWasDoubleClicked:(id)fp8;
- (void)messageBrowserView:(id)fp8 willStartDragWithEvent:(id)fp12;
- (void)draggedImage:(id)fp8 movedTo:(struct _NSPoint)fp12;
- (void)messageBrowserViewDidEndDragging:(id)fp8;
- (BOOL)transferSelectedMessagesToMailbox:(id)fp8 deleteOriginals:(BOOL)fp12;
- (BOOL)deleteMessages:(id)fp8 allowMoveToTrash:(BOOL)fp12 allowUndo:(BOOL)fp16;
- (void)_reallyAnimateProgressInidicator;
- (void)_updateSearchStatusWithDelay;
- (void)threadDidExpand;
- (void)threadDidCollapse;
- (void)clearUndoRedoStacks;
- (void)searchWillStart;
- (void)searchDidFinish;
- (void)searchDidUpdate;
- (id)selectedMailboxUids;
- (void)performSearch:(id)fp8;
- (void)saveSearch:(id)fp8;
- (void)reapplySortingRules:(id)fp8;
- (void)_returnToSenderSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_bounceMessages:(id)fp8;
- (void)returnToSender:(id)fp8;
- (void)addSenderToAddressBook:(id)fp8;
- (void)markAsJunkMail:(id)fp8;
- (void)markMessagesAsJunkMail:(id)fp8 stores:(id)fp12;
- (void)_deleteJunkedMessages:(id)fp8 inStores:(id)fp12 moveToTrash:(BOOL)fp16;
- (void)synchronouslyMarkAsJunkMail:(id)fp8 inStores:(id)fp12 delete:(BOOL)fp16;
- (void)undoMarkMessagesAsJunkMail:(id)fp8 stores:(id)fp12;
- (void)markAsNotJunkMail:(id)fp8;
- (void)markMessagesAsNotJunkMail:(id)fp8 stores:(id)fp12;
- (void)synchronouslyMarkAsNotJunkMail:(id)fp8 inStores:(id)fp12;
- (BOOL)_transferMessages:(id)fp8 toMailbox:(id)fp12 deleteOriginals:(BOOL)fp16 allowUndo:(BOOL)fp20 isDeleteOperation:(BOOL)fp24;
- (void)_reportError:(id)fp8;
- (void)transfer:(id)fp8 didCompleteWithError:(id)fp12;
- (void)hideMessagesForMessageTransfer:(id)fp8;
- (void)unhideMessagesForMessageTransfer:(id)fp8;
- (void)selectMessagesForUndo:(id)fp8;
- (id)undoManagerForMessageTransfer:(id)fp8;
- (void)_updateSearchItemLabel;

@end

@interface MessageViewer (AppleScript)
- (id)uniqueID;
- (id)objectSpecifier;
- (id)allMessages;
- (id)focusedMessages;
- (void)setFocusedMessages:(id)fp8;
- (int)appleScriptSortColumn;
- (void)setAppleScriptSortColumn:(int)fp8;
- (BOOL)isSortedAscending;
- (void)setIsSortedAscending:(BOOL)fp8;
- (BOOL)previewPaneVisible;
- (void)setPreviewPaneVisible:(BOOL)fp8;
- (id)visibleColumns;
- (void)setVisibleColumns:(id)fp8;
- (id)inbox;
- (id)outbox;
- (id)draftsMailbox;
- (id)sentMailbox;
- (id)trashMailbox;
- (id)junkMailbox;
- (void)setScriptingProperties:(id)fp8;
@end

@interface MessageViewer (MessageViewerToolbar)
- (void)setupToolbar;
- (BOOL)validateToolbarItem:(id)fp8;
- (id)previousIdentifierForUpgradingToolbar:(id)fp8;
- (id)toolbar:(id)fp8 upgradedItemIdentifiers:(id)fp12;
- (void)configureSegmentedItem:(id)fp8 withDictionary:(id)fp12 forSegment:(int)fp16;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (void)setupSearchView:(BOOL)fp8;
- (void)_handleCancelSearchButton:(id)fp8;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (void)_reallyUpdateToolbar;
- (void)_updateToolbarForResizing:(BOOL)fp8;
- (void)toolbarDidRemoveItem:(id)fp8;
- (void)toolbarWillAddItem:(id)fp8;
- (void)toolbarDidMoveItem:(id)fp8;
- (void)toolbarDidReplaceAllItems:(id)fp8;
- (void)_mailboxesViewFrameChanged;
- (void)_mailboxesViewDidEndLiveResize;
@end

@interface MessageViewer (TimeMachine)
- (id)toolbarConfigurationDict;
- (float)mailboxesPaneWidth;
- (float)previewSplitPercentage;
@end

#elif defined(TIGER)

@class MessageStore;
@class TableViewManager;
@class ASExtendedOutlineView;
@class MailboxesOutlineViewOwner;
@class StoreViewingAttributes;
@class SearchTextField;
@class MailboxUid;
@class MessageMall;
@class ExpandingSplitView;
@class AsyncArrows;
@class ColorBackgroundView;
@class MessageContentController;
@class MailVerticalSplitView;
@class VerticalSplitViewHandle;
@class SplitterAnimation;
@class MailboxPaneBottomView;
@class SearchSliceView;

@protocol MVMailboxSelectionOwner
- (id)selectedMailboxes;
- (id)selectedMailbox;
- (void)selectPathsToMailboxes:(id)fp8;
- (BOOL)mailboxIsExpanded:(id)fp8;
- (void)revealMailbox:(id)fp8;
- (id)mailboxSelectionWindow;
@end

@interface MessageViewer : NSResponder <MVMailboxSelectionOwner>
{
    MessageMall *_messageMall;
    TableViewManager *_tableManager;
    MessageContentController *_contentController;
    NSWindow *_window;
    ExpandingSplitView *_splitView;
    MailVerticalSplitView *_verticalSplitView;
    ColorBackgroundView *_viewerContainer;
    ColorBackgroundView *_mailboxesView;
    ASExtendedOutlineView *_outlineView;
    SearchTextField *_searchField;
    NSView *_searchFieldView;
    NSToolbarItem *_searchViewItem;
    NSString *_lastSearchPhrase;
    int _currentSearchType;
    int _currentSearchTarget;
    int _selectedTag;
    NSMenu *_tableHeaderMenu;
    MailboxesOutlineViewOwner *_outlineViewOwner;
    NSButton *newMailboxButton;
    NSPopUpButton *actionButton;
    VerticalSplitViewHandle *verticalSplitViewHandle;
    MailboxPaneBottomView *mailboxPaneBottomView;
    BOOL _shouldPreventTableViewResize;
    BOOL _shouldMakeTableViewSelectionVisible;
    BOOL _shouldPreventFirstViewResize;
    BOOL _shouldMakeMessageSelectionVisible;
    BOOL _showingDefaultSearchString;
    BOOL _updatingSearchField;
    BOOL _allowShowingDeletedMessages;
    BOOL _suppressWindowTitleUpdates;
    float _restoreMailboxPaneToWidthAfterDragOperation;
    float _lastSplitViewPosition;
    float _lastMailboxSplitPosition;
    float _lastDragXPosition;
    NSArray *_mailboxesToDisplayWhenVisible;
    NSToolbar *_toolbar;
    NSMutableDictionary *_toolbarItems;
    NSDictionary *_savedDefaults;
    NSMutableArray *_transferOperations;
    NSMutableDictionary *_viewerContents;
    float _splitViewPositionBeforeSearch;
    SplitterAnimation *_animation;
    SearchSliceView *_searchSliceView;
    BOOL _updatingToolbar;
    float _mailboxesViewWidthAtLastToolbarUpdate;
}

+ (id)allMessageViewers;
+ (id)allSingleMessageViewers;
+ (id)existingViewerForStore:(id)fp8;
+ (id)existingViewerForMailboxUid:(id)fp8;
+ (id)existingViewerForMessage:(id)fp8;
+ (id)newViewerForMailboxWithTag:(unsigned int)fp8;
+ (id)existingViewerShowingMessage:(id)fp8;
+ (void)registerNewViewer:(id)fp8;
+ (void)deregisterViewer:(id)fp8;
+ (void)showAllViewers;
+ (id)mailboxUidsBeingViewed;
+ (id)frontmostMessageViewer;
+ (void)searchForString:(id)fp8;
+ (id)_mailboxUidsForPaths:(id)fp8;
+ (void)saveDefaultsWithDelay;
+ (void)saveDefaults;
+ (void)restoreFromDefaults;
- (void)revealMessage:(id)fp8;
- (void)revealCurrentMessage;
- (void)_displayFollowup:(id)fp8;
- (void)_cantFindFollowupToMessage:(id)fp8;
- (void)showFollowupsToMessage:(id)fp8;
- (id)_mailboxUidsFromDefaults:(id)fp8;
- (id)initWithSavedDefaults:(id)fp8;
- (id)init;
- (id)plainInit;
- (id)initWithMailboxUids:(id)fp8;
- (void)dealloc;
- (void)_registerForApplicationNotifications;
- (void)_unregisterForApplicationNotifications;
- (void)_registerForStoreNotifications;
- (void)_unregisterForStoreNotifications;
- (void)storeBeingInvalidated:(id)fp8;
- (void)preferencesChanged:(id)fp8;
- (void)_setStore:(id)fp8;
- (BOOL)_isViewingMailboxUid:(id)fp8;
- (BOOL)_isViewingMessage:(id)fp8;
- (BOOL)_isShowingMessage:(id)fp8;
- (id)window;
- (void)show;
- (void)showAndMakeKey:(BOOL)fp8;
- (void)awakeFromNib;
- (void)_setupUI;
- (void)_setUpWindowContents;
- (void)_setupMailboxOutlineView;
- (void)_setupNextKeyViewLoop;
- (void)takeOverAsSelectionOwner;
- (void)resignAsSelectionOwner;
- (void)windowDidBecomeMain:(id)fp8;
- (void)nowWouldBeAGoodTimeToTerminate:(id)fp8;
- (BOOL)windowShouldClose:(id)fp8;
- (void)windowWillMiniaturize:(id)fp8;
- (struct _NSSize)windowWillResize:(id)fp8 toSize:(struct _NSSize)fp12;
- (void)openMailboxesPaneToWidth:(float)fp8;
- (BOOL)mailboxesPaneIsOpen;
- (BOOL)mailboxesPaneIsOpenWideEnoughToUse;
- (void)splitViewDidResizeSubviews:(id)fp8;
- (void)splitViewWillResizeSubviews:(id)fp8;
- (void)splitViewDoubleClickedOnDivider:(id)fp8;
- (void)toggleMailboxesPane:(id)fp8;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (BOOL)splitView:(id)fp8 canCollapseSubview:(id)fp12;
- (float)splitView:(id)fp8 constrainMinCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)maxMailboxesViewWidthAllowed;
- (float)idealMailboxesViewWidth;
- (void)updateMailboxButtonVisibilityForWidth:(float)fp8;
- (float)splitView:(id)fp8 constrainSplitPosition:(float)fp12 ofSubviewAt:(int)fp16;
- (id)selectedMailboxes;
- (id)selectedMailbox;
- (void)selectPathsToMailboxes:(id)fp8;
- (BOOL)mailboxIsExpanded:(id)fp8;
- (void)revealMailbox:(id)fp8;
- (id)mailboxSelectionWindow;
- (void)setSelectedMailboxes:(id)fp8;
- (id)selectedMessages;
- (void)setSelectedMessages:(id)fp8;
- (id)currentDisplayedMessage;
- (void)outlineViewDoubleClick:(id)fp8;
- (void)selectMailbox:(id)fp8;
- (void)keyDown:(id)fp8;
- (void)keyUp:(id)fp8;
- (void)_mailboxWasRenamed:(id)fp8;
- (void)mailboxSelectionChanged:(id)fp8;
- (void)_mallDidOpen;
- (void)_mallStructureDidChange;
- (void)smartMailboxCriteriaChanged:(id)fp8;
- (void)_setMailboxUids:(id)fp8;
- (BOOL)_selectionContainsMessagesWithDeletedStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithReadStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithFlaggedStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithJunkMailLevelEqualTo:(int)fp8;
- (BOOL)_selectionContainsMessagesWithAttachments;
- (BOOL)atLeastOneSelectedMessageIsInOutbox:(id)fp8;
- (BOOL)_validateAction:(SEL)fp8 tag:(int)fp12;
- (BOOL)validateMenuItem:(id)fp8;
- (void)messageWasDisplayedInTextView:(id)fp8;
- (void)messageThreadSummaryWasDisplayedInTextView:(id)fp8;
- (void)checkNewMail:(id)fp8;
- (void)replyMessage:(id)fp8;
- (void)replyAllMessage:(id)fp8;
- (void)replyToSender:(id)fp8;
- (void)replyToOriginalSender:(id)fp8;
- (void)showComposeWindow:(id)fp8;
- (void)showAddressPanel:(id)fp8;
- (void)toggleAttachmentsArea:(id)fp8;
- (void)undeleteMessages:(id)fp8;
- (void)deleteMessages:(id)fp8;
- (void)deleteMessagesAllowingMoveToTrash:(BOOL)fp8;
- (void)selectAllMessages;
- (void)setFirstResponder;
- (void)replyViaIM:(id)fp8;
- (void)showAccountInfo:(id)fp8;
- (id)tableManager;
- (id)mailboxesOutlineViewOwner;
- (void)jumpToSelection:(id)fp8;
- (void)editorWithGatekeeperApproval:(id)fp8;
- (id)editorWithType:(int)fp8;
- (void)redirectMessage:(id)fp8;
- (void)forwardMessage:(id)fp8;
- (void)displaySelectedMessageInSeparateWindow:(id)fp8;
- (void)renameMailbox:(id)fp8;
- (void)moveMessagesToMailbox:(id)fp8;
- (void)copyMessagesToMailbox:(id)fp8;
- (id)_selectedMessagesWhoseFlag:(unsigned long)fp8 isEqualToState:(BOOL)fp12;
- (void)_changeFlag:(id)fp8 state:(BOOL)fp12 forMessages:(id)fp16 undoActionName:(id)fp20;
- (void)markAsRead:(id)fp8;
- (void)markAsUnread:(id)fp8;
- (void)markAsReadFromToolbar:(id)fp8;
- (void)markAsUnreadFromToolbar:(id)fp8;
- (void)markAsUnflagged:(id)fp8;
- (void)markAsFlagged:(id)fp8;
- (void)markAsFlaggedFromToolbar:(id)fp8;
- (void)markAsUnflaggedFromToolbar:(id)fp8;
- (void)changeColor:(id)fp8;
- (void)rebuildTableOfContents:(id)fp8;
- (void)_putMessageDataOntoPasteboard:(id)fp8 attributedString:(id)fp12 shouldDelete:(id)fp16 pasteboardType:(id)fp20;
- (void)_copyMessagesToPasteboard:(id)fp8 deleteWhenCopied:(BOOL)fp12 pasteboardType:(id)fp16;
- (void)_progressAlertDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (BOOL)_doCopy:(id)fp8 deleteWhenCopied:(BOOL)fp12;
- (void)copy:(id)fp8;
- (void)cut:(id)fp8;
- (void)_pasteData:(id)fp8 pasteboardType:(id)fp12 destination:(id)fp16;
- (void)paste:(id)fp8;
- (void)startSpeaking:(id)fp8;
- (void)stopSpeaking:(id)fp8;
- (void)speechSynthesizer:(id)fp8 didFinishSpeaking:(BOOL)fp12;
- (void)showPrintPanel:(id)fp8;
- (BOOL)send:(id)fp8 forDraft:(BOOL)fp12;
- (BOOL)send:(id)fp8;
- (void)saveAs:(id)fp8;
- (void)saveAllAttachments:(id)fp8;
- (id)defaultSearchString;
- (void)showDefaultSearchString;
- (id)_criterionForMailbox:(id)fp8;
- (id)mailboxSearchCriterionForScope:(int)fp8;
- (void)searchIndex:(id)fp8;
- (BOOL)_isShowingSearchResults;
- (unsigned int)_searchResultCount;
- (BOOL)_canSaveSearchWithTarget:(int)fp8;
- (BOOL)_canSearchSelectedMailboxes;
- (BOOL)_canContentSearchSelectedMailboxes;
- (void)_showSearchSliceView;
- (void)_hideSearchSliceView;
- (void)_searchForString:(id)fp8;
- (void)_updateSearchStatus;
- (void)_clearSearch;
- (void)clearSearch:(id)fp8;
- (void)setupSearchParametersForTag:(int)fp8;
- (int)searchType;
- (int)searchTarget;
- (void)controlTextDidEndEditing:(id)fp8;
- (void)controlTextDidChange:(id)fp8;
- (void)_removeAttachmentsFromMessages:(id)fp8 fromStores:(id)fp12;
- (void)removeAttachments:(id)fp8;
- (void)sortByTagOfSender:(id)fp8;
- (void)focus:(id)fp8;
- (void)unfocus:(id)fp8;
- (void)openAllThreads:(id)fp8;
- (void)closeAllThreads:(id)fp8;
- (void)toggleThreadedMode:(id)fp8;
- (void)selectThread:(id)fp8;
- (void)selectPreviousInThread:(id)fp8;
- (void)selectNextInThread:(id)fp8;
- (void)showDeletions:(id)fp8;
- (void)hideDeletions:(id)fp8;
- (void)toggleContentsColumn:(id)fp8;
- (void)toggleMessageNumbersColumn:(id)fp8;
- (void)toggleMessageFlagsColumn:(id)fp8;
- (void)toggleFromColumn:(id)fp8;
- (void)togglePresenceColumn:(id)fp8;
- (void)toggleToColumn:(id)fp8;
- (void)toggleDateSentColumn:(id)fp8;
- (void)toggleDateReceivedColumn:(id)fp8;
- (void)toggleLocationColumn:(id)fp8;
- (void)toggleSizeColumn:(id)fp8;
- (void)writeDefaultsToArray:(id)fp8;
- (id)_saveDefaults;
- (void)_loadDefaults;
- (void)_setupFromDefaults;
- (id)_numberOfMessagesStringIsDrafts:(BOOL)fp8 omitUnread:(BOOL)fp12;
- (void)_updateWindowTitle;
- (void)_updateMessageMallUids:(id)fp8;
- (id)_currentMessageManager;
- (void)_setSplitViewPercentage:(float)fp8 animate:(BOOL)fp12;
- (void)animationDidEnd:(id)fp8;
- (void)messageWasSelected:(id)fp8 fromMessageBrowserController:(id)fp12;
- (void)scrollCurrentlySelectedMessageToTop;
- (void)messageWasDoubleClicked:(id)fp8;
- (void)messageBrowserView:(id)fp8 willStartDragWithEvent:(id)fp12;
- (void)draggedImage:(id)fp8 movedTo:(struct _NSPoint)fp12;
- (void)messageBrowserViewDidEndDragging:(id)fp8;
- (BOOL)transferSelectedMessagesToMailbox:(id)fp8 deleteOriginals:(BOOL)fp12;
- (void)_reallyAnimateProgressInidicator;
- (void)_updateSearchStatusWithDelay;
- (void)threadDidExpand;
- (void)threadDidCollapse;
- (void)searchWillStart;
- (void)searchDidFinish;
- (void)searchDidUpdate;
- (id)selectedMailboxUids;
- (void)performSearch:(id)fp8;
- (void)saveSearch:(id)fp8;
- (void)reapplySortingRules:(id)fp8;
- (void)_returnToSenderSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)returnToSender:(id)fp8;
- (void)addSenderToAddressBook:(id)fp8;
- (void)markAsJunkMail:(id)fp8;
- (void)markMessagesAsJunkMail:(id)fp8 stores:(id)fp12;
- (void)_deleteJunkedMessages:(id)fp8 inStores:(id)fp12 moveToTrash:(BOOL)fp16;
- (void)synchronouslyMarkAsJunkMail:(id)fp8 inStores:(id)fp12 delete:(BOOL)fp16;
- (void)undoMarkMessagesAsJunkMail:(id)fp8 stores:(id)fp12;
- (void)markAsNotJunkMail:(id)fp8;
- (void)markMessagesAsNotJunkMail:(id)fp8 stores:(id)fp12;
- (void)synchronouslyMarkAsNotJunkMail:(id)fp8 inStores:(id)fp12;
- (BOOL)_transferSelectedMessagesToMailbox:(id)fp8 deleteOriginals:(BOOL)fp12;
- (void)_reportError:(id)fp8;
- (void)transfer:(id)fp8 didCompleteWithError:(id)fp12;
- (id)undoManagerForMessageTransfer:(id)fp8;
- (void)_updateSearchItemLabel;

@end

@interface MessageViewer (AppleScript)
- (id)uniqueID;
- (id)objectSpecifier;
- (id)allMessages;
- (id)focusedMessages;
- (void)setFocusedMessages:(id)fp8;
- (int)appleScriptSortColumn;
- (void)setAppleScriptSortColumn:(int)fp8;
- (BOOL)isSortedAscending;
- (void)setIsSortedAscending:(BOOL)fp8;
- (BOOL)previewPaneVisible;
- (void)setPreviewPaneVisible:(BOOL)fp8;
- (id)visibleColumns;
- (void)setVisibleColumns:(id)fp8;
- (id)inbox;
- (id)outbox;
- (id)draftsMailbox;
- (id)sentMailbox;
- (id)trashMailbox;
- (id)junkMailbox;
- (void)setScriptingProperties:(id)fp8;
@end

@interface MessageViewer (MessageViewerToolbar)
- (void)_setupToolBar;
- (BOOL)validateToolbarItem:(id)fp8 forSegment:(int)fp12;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (void)setupSearchView:(BOOL)fp8;
- (void)_handleCancelSearchButton:(id)fp8;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (void)_reallyUpdateToolbar:(BOOL)fp8;
- (void)_updateToolbarForResizing:(BOOL)fp8;
- (void)toolbarDidRemoveItem:(id)fp8;
- (void)toolbarWillAddItem:(id)fp8;
- (void)toolbarDidMoveItem:(id)fp8;
- (void)toolbarDidReplaceAllItems:(id)fp8;
- (void)_mailboxesViewFrameChanged;
- (void)_mailboxesViewDidEndLiveResize;
@end

#else

@class MessageStore;
@class TableViewManager;
@class ASExtendedOutlineView;
@class MailboxesOutlineViewOwner;
@class StoreViewingAttributes;
@class SearchTextField;
@class MailboxUid;
@class MessageMall;
@class ExpandingSplitView;
@class AsyncArrows;
@class ColorBackgroundView;
@class MessageContentController;

@interface MessageViewer:NSResponder
{
    MessageMall *_messageMall;	// 8 = 0x8
    TableViewManager *_tableManager;	// 12 = 0xc
    MessageContentController *_contentController;	// 16 = 0x10
    NSWindow *_window;	// 20 = 0x14
    ExpandingSplitView *_splitView;	// 24 = 0x18
    NSTextField *_statusField;	// 28 = 0x1c
    AsyncArrows *_progressIndicator;	// 32 = 0x20
    NSBox *_messageViewerBox;	// 36 = 0x24
    ColorBackgroundView *_mailboxesView;	// 40 = 0x28
    ASExtendedOutlineView *_outlineView;	// 44 = 0x2c
    SearchTextField *_searchField;	// 48 = 0x30
    NSView *_searchFieldView;	// 52 = 0x34
    NSToolbarItem *_searchViewItem;	// 56 = 0x38
    NSMenu *_searchMenu;	// 60 = 0x3c
    NSString *_lastSearchPhrase;	// 64 = 0x40
    int _currentSearchType;	// 68 = 0x44
    int _currentSearchTarget;	// 72 = 0x48
    int _selectedTag;	// 76 = 0x4c
    NSMenu *_tableHeaderMenu;	// 80 = 0x50
    NSMenuItem *_selectedMailboxesItem;	// 84 = 0x54
    MailboxesOutlineViewOwner *_outlineViewOwner;	// 88 = 0x58
    NSDrawer *_mailboxesDrawer;	// 92 = 0x5c
    NSButton *newMailboxButton;	// 96 = 0x60
    NSPopUpButton *actionButton;	// 100 = 0x64
    NSString *_sizeStatusString;	// 104 = 0x68
    NSString *_uiStatusMessage;	// 108 = 0x6c
    char _shouldCloseMailboxListingAfterDragOperation;	// 112 = 0x70
    char _shouldPreventTableViewResize;	// 113 = 0x71
    char _shouldMakeTableViewSelectionVisible;	// 114 = 0x72
    char _showingDefaultSearchString;	// 115 = 0x73
    char _updatingSearchField;	// 116 = 0x74
    char _allowShowingDeletedMessages;	// 117 = 0x75
    char _disableMailboxesButton;	// 118 = 0x76
    float _lastSplitViewPosition;	// 120 = 0x78
    float _lastDragXPosition;	// 124 = 0x7c
    NSArray *_mailboxesToDisplayWhenVisible;	// 128 = 0x80
    NSToolbar *_toolbar;	// 132 = 0x84
    NSMutableDictionary *_toolbarItems;	// 136 = 0x88
    NSDictionary *_savedDefaults;	// 140 = 0x8c
    NSMutableArray *_transferOperations;	// 144 = 0x90
}

+ allMessageViewers;
+ allSingleMessageViewers;
+ existingViewerForStore:fp8;
+ existingViewerForMailboxUid:fp8;
+ existingViewerForMessage:fp8;
+ (void)registerNewViewer:fp8;
+ (void)deregisterViewer:fp8;
+ (void)showAllViewers;
+ (void)updateStatusLineForAllViewers;
+ (void)saveDefaults;
+ (void)restoreFromDefaults;
- (void)showFollowupsToMessage:fp8;
- (void)_findFollowupsToMessage:fp8 inStore:fp12;
- (void)_displayFollowup:fp8 inStore:fp12;
- (void)_cantFindFollowupToMessage:fp8 inStore:fp12;
- _mailboxUidsFromDefaults:fp8;
- initWithSavedDefaults:fp8;
- init;
- plainInit;
- initWithMailboxUids:fp8;
- (void)dealloc;
- (void)_registerForApplicationNotifications;
- (void)_unregisterForApplicationNotifications;
- (void)_registerForStoreNotifications;
- (void)_unregisterForStoreNotifications;
- (void)storeBeingInvalidated:fp8;
- (void)preferencesChanged:fp8;
- (char)mailboxListingIsShowing;
- (void)setMailboxListingIsShowing:(char)fp8;
- (void)drawerDidOpen:fp8;
- (void)_setStore:fp8;
- (char)_isViewingMailboxUid:fp8;
- _accountBeingViewed;
- (char)_isViewingMessage:fp8;
- window;
- (void)show;
- (void)showAndMakeKey:(char)fp8;
- (void)_setupUI;
- (void)_loadDrawerAndMessages;
- (void)_setupMailboxOutlineView;
- (void)_setupMailboxesDrawer;
- (void)_setupNextKeyViewLoop;
- (void)takeOverAsSelectionOwner;
- (void)resignAsSelectionOwner;
- (void)windowDidBecomeMain:fp8;
- (void)nowWouldBeAGoodTimeToTerminate:fp8;
- (char)windowShouldClose:fp8;
- (void)windowWillMiniaturize:fp8;
- (struct _NSSize)windowWillResize:fp8 toSize:(struct _NSSize)fp12;
- (void)splitViewDidResizeSubviews:fp8;
- (void)splitViewWillResizeSubviews:fp8;
- (void)splitViewDoubleClickedOnDivider:fp8;
- (void)splitView:fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (char)splitView:fp8 canCollapseSubview:fp12;
- (float)splitView:fp8 constrainMinCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)splitView:fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- selectedMailboxes;
- (void)setSelectedMailboxes:fp8;
- selectedMessages;
- (void)setSelectedMessages:fp8;
- currentDisplayedMessage;
- (void)outlineViewDoubleClick:fp8;
- (void)selectMailbox:fp8;
- (void)keyDown:fp8;
- (void)keyUp:fp8;
- (void)_mailboxWasRenamed:fp8;
- (void)mailboxSelectionChanged:fp8;
- (void)_mallDidOpen;
- (void)_mallStructureDidChange;
- (void)_setMailboxUids:fp8;
- (char)_selectionContainsMessagesWithDeletedStatusEqualTo:(char)fp8;
- (char)_selectionContainsMessagesWithReadStatusEqualTo:(char)fp8;
- (char)_selectionContainsMessagesWithFlaggedStatusEqualTo:(char)fp8;
- (char)_selectionContainsMessagesWithJunkMailLevelEqualTo:(int)fp8;
- (char)_selectionContainsMessagesWithAttachments;
- (char)_validateAction:(SEL)fp8 tag:(int)fp12;
- (char)validateMenuItem:fp8;
- (void)messageWasDisplayedInTextView:fp8;
- (void)checkNewMail:fp8;
- (void)replyMessage:fp8;
- (void)replyAllMessage:fp8;
- (void)replyToSender:fp8;
- (void)replyToOriginalSender:fp8;
- (void)showComposeWindow:fp8;
- (void)showAddressPanel:fp8;
- (void)toggleAttachmentsArea:fp8;
- (void)undeleteMessages:fp8;
- (void)deleteMessages:fp8;
- (void)deleteMessagesAllowingMoveToTrash:(char)fp8;
- (void)replyViaIM:fp8;
- tableManager;
- (void)jumpToSelection:fp8;
- (void)redirectMessage:fp8;
- (void)forwardMessage:fp8;
- (void)_replyMessageWithType:(int)fp8;
- (void)displaySelectedMessageInSeparateWindow:fp8;
- (void)renameMailbox:fp8;
- (void)moveMessagesToMailbox:fp8;
- (void)copyMessagesToMailbox:fp8;
- (void)_changeFlag:fp8 state:(char)fp12 forMessages:fp16 undoActionName:fp20;
- (void)markAsRead:fp8;
- (void)markAsUnread:fp8;
- (void)markAsUnflagged:fp8;
- (void)markAsFlagged:fp8;
- (void)changeColor:fp8;
- (void)rebuildTableOfContents:fp8;
- (void)copy:fp8;
- (void)cut:fp8;
- (void)paste:fp8;
- (void)showPrintPanel:fp8;
- (char)send:fp8;
- (void)saveAs:fp8;
- (void)saveAllAttachments:fp8;
- (void)updateMenuCheckmarkForTag:(int)fp8;
- defaultSearchString;
- (void)showDefaultSearchString;
- (void)searchPopupChanged:fp8;
- (void)searchIndex:fp8;
- (void)clearSearch:fp8;
- (void)setupSearchParametersForTag:(int)fp8;
- (int)searchType;
- (int)searchTarget;
- (void)performSearch:fp8;
- (void)controlTextDidEndEditing:fp8;
- (void)controlTextDidChange:fp8;
- (void)_removeAttachmentsFromMessages:fp8 fromStores:fp12;
- (void)removeAttachments:fp8;
- (void)sortByTagOfSender:fp8;
- (void)focus:fp8;
- (void)unfocus:fp8;
- (void)openAllThreads:fp8;
- (void)closeAllThreads:fp8;
- (void)toggleThreadedMode:fp8;
- (void)selectThread:fp8;
- (void)selectPreviousInThread:fp8;
- (void)selectNextInThread:fp8;
- (void)showDeletions:fp8;
- (void)hideDeletions:fp8;
- (void)toggleContentsColumn:fp8;
- (void)toggleMessageNumbersColumn:fp8;
- (void)toggleMessageFlagsColumn:fp8;
- (void)toggleFromColumn:fp8;
- (void)togglePresenceColumn:fp8;
- (void)toggleToColumn:fp8;
- (void)toggleDateSentColumn:fp8;
- (void)toggleDateReceivedColumn:fp8;
- (void)toggleLocationColumn:fp8;
- (void)toggleSizeColumn:fp8;
- (void)_showMailboxesPanel;
- (void)showMailboxesPanel:fp8;
- (void)writeDefaultsToArray:fp8;
- _saveDefaults;
- (void)_setupFromDefaults;
- _sizeStatus;
- (void)showStatusMessage:fp8;
- (void)_updateStatusLine;
- (void)_updateStatusLineAndWindowTitle;
- (void)_updateMessageMallUids:fp8;
- (void)showStatusLine:fp8;
- (void)hideStatusLine:fp8;
- (void)messageWasSelected:fp8;
- (void)tableView:fp8 willStartDragWithEvent:fp12;
- (void)draggedImage:fp8 movedTo:(struct _NSPoint)fp12;
- (void)draggingUpdatedAtLocation:(struct _NSPoint)fp8;
- (void)tableViewDidEndDragging:fp8;
- (void)reapplySortingRules:fp8;
- (void)_returnToSenderSheetDidEnd:fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)returnToSender:fp8;
- (void)addSenderToAddressBook:fp8;
- (void)showMainThreadIsBusy:fp8;
- (void)showMainThreadIsNotBusy:fp8;
- (void)_performJunkMailActionOnMessages:fp8;
- (void)markAsJunkMail:fp8;
- (void)markMessagesAsJunkMail:fp8 stores:fp12;
- (void)synchronouslyMarkAsJunkMail:fp8 inStores:fp12 delete:(char)fp16;
- (void)undoMarkMessagesAsJunkMail:fp8 stores:fp12;
- (void)markAsNotJunkMail:fp8;
- (void)markMessagesAsNotJunkMail:fp8 stores:fp12;
- (void)synchronouslyMarkAsNotJunkMail:fp8 inStores:fp12;
- (char)transferSelectedMessagesToMailbox:fp8 deleteOriginals:(char)fp12;
- (void)_reportError:fp8;
- (void)transfer:fp8 didCompleteWithError:fp12;
- undoManagerForMessageTransfer:fp8;
- (void)_updateSearchItemLabel;

@end

@interface MessageViewer(AppleScript)
- uniqueID;
- objectSpecifier;
- allMessages;
- focusedMessages;
- (void)setFocusedMessages:fp8;
- (int)appleScriptSortColumn;
- (void)setAppleScriptSortColumn:(int)fp8;
- (char)isSortedAscending;
- (void)setIsSortedAscending:(char)fp8;
- (char)previewPaneVisible;
- (void)setPreviewPaneVisible:(char)fp8;
- visibleColumns;
- (void)setVisibleColumns:fp8;
- inbox;
- outbox;
- draftsMailbox;
- sentMailbox;
- trashMailbox;
- junkMailbox;
- (void)setScriptingProperties:fp8;
@end

@interface MessageViewer(MessageViewerToolbar)
- (void)_setupToolBar;
- (char)validateToolbarItem:fp8;
- toolbar:fp8 itemForItemIdentifier:fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (void)setupSearchView:(char)fp8;
- toolbarDefaultItemIdentifiers:fp8;
- toolbarAllowedItemIdentifiers:fp8;
- (void)toolbarDidRemoveItem:fp8;
@end

#endif
