name="GPGMail"
#dmgNamePrefix="GPGMail"
appNamme="GPGMail.mailbundle"
volumeName="GPGMail"

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png"
volumeLayout="Installer/DS_Store"

sshKeyname="Sparkle GPGMail - Private key"

unset REVISION PRERELEASE

MAJOR=2
MINOR=0
PRERELEASE=b6

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
