name="GPGMail"
appNamme="GPGMail.mailbundle"
bundleName="GPGMail.mpkg"
html="gpgmail"
pkgProj="Installer/GPGMail.pkgproj"
pkgReadme="Installer/package-introduction.txt"
bundlePath="build/$bundleName"
rmName="Uninstall.app"
rmPath="Installer/$rmName"
imgBackground="Installer/background_dmg.png";
downloadUrl="https://github.com/downloads/GPGMail/GPGMail/${dmgName}";
sshKeyname="Sparkle GPGMail - Private key"
dmgUrl="GPGTools/GPGMail"
preDMGBuild="Installer/fixInstaller.sh"


MAJOR_VERSION=2
MINOR_VERSION=0
PRERELEASE_VERSION=a31

version=${MAJOR_VERSION}.${MINOR_VERSION}${PRERELEASE_VERSION}
