/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSURLConnection.h"

@class FeedTransporter;

@interface _RSSConnection : NSURLConnection
{
    FeedTransporter *_feed;
    BOOL _isFinished;
    BOOL _isCancelled;
}

- (id)initWithRequest:(id)arg1 delegate:(id)arg2 startImmediately:(BOOL)arg3;
- (void)dealloc;
- (BOOL)isCancelled;
- (void)setIsCancelled:(BOOL)arg1;
- (BOOL)isFinished;
- (void)setIsFinished:(BOOL)arg1;
- (id)feed;
- (void)setFeed:(id)arg1;

@end

