/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTextField, NSView;

@interface AccountSummary : NSObject
{
    NSView *_view;
    NSTextField *_accountDescription;
    NSTextField *_fullname;
    NSTextField *_emailAddress;
    NSTextField *_userName;
    NSTextField *_incomingServer;
    NSTextField *_incomingServerSSLMode;
    NSTextField *_outgoingServer;
    NSTextField *_outgoingServerSSLMode;
    NSTextField *_outlookServer;
    NSTextField *_outlookServerLabel;
}

- (id)init;
- (void)setupUIWithAccount:(id)arg1 deliveryAccount:(id)arg2;
- (void)setupUIWithAccount:(id)arg1;
- (id)view;

@end

