/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, MessageStore, NSMutableArray;

@interface AttachmentLoader : NSObject
{
    MessageStore *_store;
    ActivityMonitor *_monitor;
    NSMutableArray *_entries;
}

+ (id)loaderForAttachment:(id)arg1 window:(id)arg2 reason:(int)arg3 application:(id)arg4 attachmentDirectory:(id)arg5;
+ (id)loaderForSavingAttachment:(id)arg1 window:(id)arg2 path:(id)arg3;
+ (void)startLoadingInlineAttachments:(id)arg1 window:(id)arg2 delegate:(id)arg3;
+ (void)cancelInlineLoads:(id)arg1 window:(id)arg2;
- (void)dealloc;

@end

