/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSView, NSWindow;

@interface ChildWindowController : NSWindowController
{
    NSWindow *_parentWindow;
    id _delegate;
    struct {
        unsigned int windowIsOpen:1;
        unsigned int shareKey:1;
        unsigned int closeWhenResigningKey:1;
        unsigned int delegateRespondsToBestFrameOriginForWindow:1;
        unsigned int viewPostingSheet:1;
        unsigned int reserved:27;
    } _flags;
    NSView *_firstKeyView;
    NSView *_lastKeyView;
}

- (id)initWithWindow:(id)arg1;
- (void)dealloc;
- (id)window;
- (id)parentWindow;
- (void)setParentWindow:(id)arg1;
- (BOOL)sharesKey;
- (void)setSharesKey:(BOOL)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (BOOL)shouldCloseWhenResigningKey;
- (void)setShouldCloseWhenResigningKey:(BOOL)arg1;
- (id)firstKeyView;
- (id)lastKeyView;
- (BOOL)isWindowOpen;
- (void)addNotifications;
- (void)removeNotifications;
- (void)showWindow:(id)arg1;
- (BOOL)canClose;
- (void)closeWindow:(id)arg1;
- (void)close;
- (void)closeImmediately;
- (struct CGPoint)bestWindowFrameOrigin;
- (void)closeIfNecessaryForEvent:(id)arg1 before:(BOOL)arg2;
- (void)viewWillPostSheet:(id)arg1;
- (void)viewDonePostingSheet:(id)arg1;
- (void)menuDidBeginTracking:(id)arg1;
- (void)parentWindowDidResignKey:(id)arg1;
- (void)parentWindowWillClose:(id)arg1;
- (void)parentWindowWillBeginSheet:(id)arg1;
- (void)parentWindowDidResize:(id)arg1;
- (void)parentWindowDidMove:(id)arg1;
- (void)parentWindowDidUpdate:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)window:(id)arg1 didProcessEvent:(id)arg2;

@end

