/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "DOMCSSValue.h"

@interface DOMCSSValue (MailExtras)
- (BOOL)matchesFontFamily:(id)arg1;
@end

