/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@interface FlatPopUpButtonCell : NSPopUpButtonCell
{
    BOOL _useThinLeftMargin;
}

+ (void)loadCapGraphics;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (float)_menuLocationHorizontalOffset;
- (void)_drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)useThinLeftMargin;
- (void)setUseThinLeftMargin:(BOOL)arg1;

@end

