/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@class NSImage;

@interface ImagePopUpButtonCell : NSPopUpButtonCell
{
    NSImage *image;
    NSImage *alternateImage;
    NSImage *inactiveImage;
}

- (void)dealloc;
- (float)_extraWidthForCellHeight:(float)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawBorderAndBackgroundWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setImage:(id)arg1;
- (id)image;
- (void)setAlternateImage:(id)arg1;
- (id)alternateImage;
- (void)setInactiveImage:(id)arg1;
- (id)inactiveImage;

@end

