/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, NSProgressIndicator, NSTextField, NSView;

@interface LoadingOverlay : NSObject
{
    NSView *_overlayView;
    NSProgressIndicator *_progressIndicator;
    NSTextField *_statusMessageField;
    ActivityMonitor *_monitor;
    id _modalDelegate;
}

- (id)initWithModalDelegate:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)displayInSuperview:(id)arg1;
- (void)displayInSuperviewAfterDelay:(id)arg1;
- (void)setActivityMonitor:(id)arg1;
- (void)setStatusMessage:(id)arg1;
- (id)statusMessage;
- (void)activityEnded:(id)arg1;
- (id)modalDelegate;
- (void)setModalDelegate:(id)arg1;
- (id)overlayView;
- (id)activityMonitor;

@end

