/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "MVTerminationHandler-Protocol.h"

@class MessageViewer, NSTimer;

@interface MailTimeMachineController : NSObject <MVTerminationHandler>
{
    MessageViewer *_messageViewer;
    BOOL _savingTOC;
    struct OpaqueEventHandlerRef *_helperAppEventHandler;
    struct ProcessSerialNumber _helperAppPSN;
    struct CGRect _mailFrame;
    id _tableOfContentsSaveLock;
    NSTimer *_tableOfContentsSaveTimer;
}

+ (id)sharedController;
- (id)init;
- (void)dealloc;
- (void)registerNotificationHandlers;
- (void)invalidateTableOfContentsAndBackupManager:(id)arg1;
- (void)invalidateTableOfContents:(id)arg1;
- (void)saveTableOfContents;
- (void)setTableOfContentsIsValid:(BOOL)arg1;
- (void)_setTableOfContentsTimer:(id)arg1;
- (void)registerTimeMachineHandlers;
- (void)unregisterTimeMachineHandlers;
- (void)handleAppleEvent:(id)arg1;
- (void)nowWouldBeAGoodTimeToTerminate:(id)arg1;
- (void)_approvedQuit;
- (void)_saveTableOfContents;
- (void)_thread_saveTableOfContents:(id)arg1;
- (void)_threadedSaveTableOfContentsEnded:(id)arg1;
- (BOOL)_timingOutSaveTableOfContents;
- (void)_threadedSaveTableOfContentsWithEndedSelector:(SEL)arg1;
- (id)_formattedAddressForAddress:(id)arg1;
- (id)_mailTimeMachineDescriptionForMessage:(id)arg1 withColumns:(id)arg2 andMall:(id)arg3 selected:(BOOL)arg4;
- (BOOL)_launchTimeMachineHelperApp;
- (void)_startWatchingHelperApp;
- (void)_stopWatchingHelperApp;
- (void)_enterTimeMachineMode;
- (void)_prepareExitTimeMachineModeWithDisplayState:(id)arg1;
- (void)_exitTimeMachineModeWithDisplayState:(id)arg1;

@end

