/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSView.h"

#import "NSTextViewDelegate-Protocol.h"

@class HeaderAttachmentsView, NSImageView, NSTextView, WebView;

@interface MessageTilingView : NSView <NSTextViewDelegate>
{
    NSTextView *headerView;
    NSView *bodyView;
    WebView *editorView;
    HeaderAttachmentsView *attachmentsView;
    NSImageView *senderImageView;
    NSTextView *revealLinkView;
    unsigned int _doneInitializing:1;
    unsigned int _tilingSubviews:1;
    unsigned int _resizingFromSuperview:1;
    unsigned int _bodyViewIsLoaded:1;
    unsigned int _okayToResize:1;
    unsigned int _hasResizedBody:1;
    unsigned int _showRevealMessageLink:1;
    int _separator;
    NSView *accessibilityLinkedView;
}

- (void)awakeFromNib;
- (void)dealloc;
- (id)attachmentsView;
- (id)senderImageView;
- (id)bodyView;
- (id)editorView;
- (void)setEditorView:(id)arg1;
- (void)setBodyView:(id)arg1;
- (id)_bodyViewToLink;
- (void)setUpAccessibilityLinks;
- (void)removeAccessibilityLinks;
- (void)setUpAccessibilityLinksFromView:(id)arg1;
- (void)showAttachmentsView:(BOOL)arg1;
- (void)setHeaderBodySeparator:(int)arg1;
- (void)_updateRevealLinkPosition;
- (void)showSenderImage:(BOOL)arg1;
- (BOOL)isFlipped;
- (void)subviewFrameChanged:(id)arg1;
- (struct CGSize)contentSize;
- (void)resizeWithOldSuperviewSize:(struct CGSize)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)tile;
- (void)drawRect:(struct CGRect)arg1;
- (void)setBodyViewIsLoaded:(BOOL)arg1;
- (BOOL)knowsPageRange:(struct _NSRange *)arg1;
- (BOOL)isOpaque;
- (void)mouseDown:(id)arg1;
- (void)setShowRevealMessageLink:(BOOL)arg1;
- (BOOL)showRevealMessageLink;
- (id)_textAttributesForRevealLink;
- (id)_revealLinkString;
- (id)revealLinkView;
- (id)_revealLinkView;
- (BOOL)showRevealMessageLinkView;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long)arg3;
- (void)textOrWebViewSelectionChanged:(id)arg1;

@end

