/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "SingleMessageViewer.h"

@class NSMenu, NSMutableArray, NSMutableDictionary;

@interface MessageBrowser : SingleMessageViewer
{
    NSMutableArray *_messages;
    unsigned int _includeDeleted:1;
    int _currentIndex;
    int _previousIndex;
    int _nextIndex;
    int _firstIndex;
    int _lastIndex;
    NSMutableDictionary *_messagesByID;
    NSMenu *_previousMenu;
    NSMenu *_nextMenu;
}

+ (BOOL)restoreAllViewersFromDefaults;
+ (void)saveAllViewersToDefaultsOmittingViewer:(id)arg1;
+ (id)browserForMessages:(id)arg1 isSortedAscending:(BOOL)arg2 includeDeleted:(BOOL)arg3;
- (id)initWithSavedDefaults:(id)arg1;
- (id)dictionaryRepresentation;
- (void)_setupFromDefaults;
- (void)dealloc;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)replaceWithEditorForType:(int)arg1;
- (void)_close;
- (long)_newCurrentIndexFromCurrentIndex:(long)arg1;
- (void)messageFlagsDidChange:(id)arg1;
- (void)messagesCompacted:(id)arg1;
- (void)_reallyRedeleteMessage:(id)arg1;
- (void)_redeleteMessage:(id)arg1;
- (void)_reallyUndeleteMessage:(id)arg1;
- (void)_undeleteMessage:(id)arg1;
- (void)_reallyDeleteMessage:(id)arg1 allowMoveToTrash:(BOOL)arg2;
- (void)deleteMessagesAllowingMoveToTrash:(BOOL)arg1;
- (void)setupToolbar;
- (void)showNextMessage:(id)arg1;
- (void)showPreviousMessage:(id)arg1;
- (void)showFirstMessage:(id)arg1;
- (void)keyDown:(id)arg1;
- (id)_initWithMessages:(id)arg1 isSortedAscending:(BOOL)arg2 includeDeleted:(BOOL)arg3;
- (id)initForViewingMessage:(id)arg1 showAllHeaders:(BOOL)arg2 viewingState:(id)arg3 withDefaults:(id)arg4;
- (void)_showMessage:(id)arg1;
- (void)_menuItemSelected:(id)arg1;
- (id)_imageForMessage:(id)arg1;
- (void)_addMessage:(id)arg1 toMenu:(id)arg2;
- (void)_updateMenuItemImagesForMenu:(id)arg1;
- (void)_updatePreviousNextMenuItemImages;
- (BOOL)_shouldDisplayMessage:(id)arg1;
- (void)_updatePreviousNextMenus;
- (void)_updateFirstAndLastIndex;
- (void)_nextMessageIndex:(int *)arg1 previousIndex:(int *)arg2 fromCurrentIndex:(long)arg3;
- (void)_updatePreviousAndNextIndex;
- (void)_showMessageAtIndex:(long)arg1;
- (BOOL)_isMessageIndexValid:(long)arg1;
- (long)_firstMessageIndex;
- (long)_lastMessageIndex;
- (long)_previousMessageIndex;
- (long)_nextMessageIndex;
- (void)_showFirstMessage;
- (void)_showLastMessage;
- (void)_showPreviousMessage;
- (void)_showNextMessage;

@end

