/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, MFError, Message, MimeBody, NSArray, NSAttributedString, NSDictionary, NSSet, NSString;

@interface MessageViewingState : NSObject
{
    NSAttributedString *_headerAttributedString;
    NSDictionary *_addressAttachments;
    NSDictionary *_plainAddresses;
    NSSet *_expandedAddressKeys;
    NSAttributedString *_attachmentsDescription;
    NSArray *_headerOrder;
    NSArray *_attachments;
    Message *_message;
    ActivityMonitor *_monitor;
    MimeBody *mimeBody;
    id document;
    MFError *error;
    int headerIndent;
    int headerFontAdjustmentDebt;
    int preferredAlternative;
    BOOL accountWasOffline;
    BOOL dontCache;
    BOOL showAllHeaders;
    BOOL showDefaultHeaders;
    BOOL isPrinting;
    BOOL viewSource;
    BOOL showControlChars;
    BOOL showAttachments;
    BOOL downloadRemoteURLs;
    BOOL triedToDownloadRemoteURLs;
    BOOL messageIsFromMicrosoft;
    BOOL isChildRequestForSenders;
    int displayType;
    unsigned int preferredEncoding;
    NSString *sender;
    NSString *senderName;
    NSString *childAddress;
    NSArray *requestedAddressesFromChild;
    id <MessageContentDisplay> displayer;
    id editor;
}

+ (void)initialize;
- (void)release;
- (void)dealloc;
- (id)init;
- (id)editor;
- (void)setEditor:(id)arg1;
- (void)editorClosed:(id)arg1;
- (id)mimeBody;
- (id)attachments;
- (id)headerAttributedString;
- (void)setHeaderAttributedString:(id)arg1;
- (id)plainAddresses;
- (void)setPlainAddresses:(id)arg1;
- (id)addressAttachments;
- (void)setAddressAttachments:(id)arg1;
- (id)expandedAddressKeys;
- (void)setExpandedAddressKeys:(id)arg1;
- (id)attachmentsDescription;
- (void)setAttachmentsDescription:(id)arg1;
- (id)headerOrder;
- (void)setHeaderOrder:(id)arg1;
- (int)headerDetailLevel;
- (id)description;
- (id)monitor;
- (void)setMonitor:(id)arg1;
- (id)message;
- (void)setMessage:(id)arg1;
- (id)displayer;
- (void)setDisplayer:(id)arg1;
- (id)requestedAddressesFromChild;
- (void)setRequestedAddressesFromChild:(id)arg1;
- (id)childAddress;
- (void)setChildAddress:(id)arg1;
- (id)senderName;
- (void)setSenderName:(id)arg1;
- (id)sender;
- (void)setSender:(id)arg1;
- (unsigned long)preferredEncoding;
- (void)setPreferredEncoding:(unsigned long)arg1;
- (int)displayType;
- (void)setDisplayType:(int)arg1;
- (BOOL)isChildRequestForSenders;
- (void)setIsChildRequestForSenders:(BOOL)arg1;
- (BOOL)messageIsFromMicrosoft;
- (void)setMessageIsFromMicrosoft:(BOOL)arg1;
- (BOOL)triedToDownloadRemoteURLs;
- (void)setTriedToDownloadRemoteURLs:(BOOL)arg1;
- (BOOL)downloadRemoteURLs;
- (void)setDownloadRemoteURLs:(BOOL)arg1;
- (BOOL)showAttachments;
- (void)setShowAttachments:(BOOL)arg1;
- (BOOL)showControlChars;
- (void)setShowControlChars:(BOOL)arg1;
- (BOOL)viewSource;
- (void)setViewSource:(BOOL)arg1;
- (BOOL)isPrinting;
- (void)setIsPrinting:(BOOL)arg1;
- (BOOL)showDefaultHeaders;
- (void)setShowDefaultHeaders:(BOOL)arg1;
- (BOOL)showAllHeaders;
- (void)setShowAllHeaders:(BOOL)arg1;
- (BOOL)dontCache;
- (void)setDontCache:(BOOL)arg1;
- (BOOL)accountWasOffline;
- (void)setAccountWasOffline:(BOOL)arg1;
- (int)preferredAlternative;
- (void)setPreferredAlternative:(int)arg1;
- (long)headerFontAdjustmentDebt;
- (void)setHeaderFontAdjustmentDebt:(long)arg1;
- (long)headerIndent;
- (void)setHeaderIndent:(long)arg1;
- (id)error;
- (void)setError:(id)arg1;
- (id)document;
- (void)setDocument:(id)arg1;
- (void)setMimeBody:(id)arg1;

@end

