/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "MessageViewer.h"

#import "MessageViewerSearchFieldFocusDelegate-Protocol.h"
#import "NSToolbarDelegate-Protocol.h"

@interface MessageViewer (MessageViewerToolbar) <MessageViewerSearchFieldFocusDelegate, NSToolbarDelegate>
- (void)setupToolbar;
- (BOOL)validateToolbarItem:(id)arg1;
- (id)previousIdentifierForUpgradingToolbar:(id)arg1;
- (id)toolbar:(id)arg1 upgradedItemIdentifiers:(id)arg2;
- (void)configureSegmentedItem:(id)arg1 withDictionary:(id)arg2 forSegment:(long)arg3;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (void)_updateToolbar;
- (void)toolbarWillAddItem:(id)arg1;
- (void)toolbarDidRemoveItem:(id)arg1;
- (void)toolbarDidReorderItem:(id)arg1;
- (void)ensureSearchFieldVisibilityInToolbar;
- (void)searchFieldDidEndSearching:(id)arg1;
@end

