/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ComposeBackEnd.h"

@class LibraryMessage, MailAccount, NSDictionary, NSSet, NSString;

@interface NoteComposeBackEnd : ComposeBackEnd
{
    MailAccount *_account;
    NSString *_summary;
    NSString *_creationDateHeader;
    LibraryMessage *_associatedMessage;
    NSString *_backgroundColor;
    NSDictionary *_onLoadToDosByID;
    NSDictionary *_onLoadToDosByPreviousID;
    NSSet *_onLoadDeletedToDoIDs;
}

+ (void)initialize;
+ (id)supportedMailboxUidTypes;
- (void)setStateFromBackEnd:(id)arg1;
- (BOOL)isExchangeNote;
- (id)summary;
- (void)setSummary:(id)arg1;
- (id)sender;
- (BOOL)preserveAddedArchiveBody;
- (id)backgroundColor;
- (BOOL)defaultFormatIsRich;
- (id)account;
- (id)mailboxUidCreateIfNeeded:(BOOL)arg1;
- (id)generatedSubject;
- (void)setSubject:(id)arg1;
- (void)_backgroundSaveEnded:(id)arg1;
- (void)updateToDosInContent:(id)arg1 documentID:(id)arg2 referencedMessageID:(id)arg3;
- (id)htmlDocumentForSave;
- (id)htmlStringFromRange:(id)arg1 htmlDocument:(id)arg2 removeCustomAttributes:(BOOL)arg3 convertObjectsToImages:(BOOL)arg4 convertEditableElements:(BOOL)arg5;
- (id)outgoingMessageUsingWriter:(id)arg1 contents:(id)arg2 headers:(id)arg3 isDraft:(BOOL)arg4 shouldBePlainText:(BOOL)arg5;
- (id)saveTaskName;
- (BOOL)isPaperless;
- (BOOL)hasChanges;
- (BOOL)restoredMessageIsRich;
- (BOOL)containsRichText;
- (BOOL)saveMessage;
- (id)todoDocumentID;
- (BOOL)isEditingMessage:(id)arg1;
- (void)updateDocumentReference:(id)arg1;
- (void)finishPreparingContentWithEditorSettings:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)onLoadDeletedToDoIDs;
- (void)setOnLoadDeletedToDoIDs:(id)arg1;
- (id)onLoadToDosByPreviousID;
- (void)setOnLoadToDosByPreviousID:(id)arg1;
- (id)onLoadToDosByID;
- (void)setOnLoadToDosByID:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (id)creationDateHeader;
- (void)setCreationDateHeader:(id)arg1;
- (id)associatedMessage;
- (void)setAssociatedMessage:(id)arg1;
- (void)setAccount:(id)arg1;

@end

