/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTextView.h"

@interface NSTextView (AtomicAddress)
- (void)fixAtomSelectionForSelectionRange:(struct _NSRange)arg1;
- (void)fixJoiningOfSelectedAtoms;
@end

