/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSToolbarItemGroup.h"

@interface SegmentedToolbarItem : NSToolbarItemGroup
{
}

- (id)initWithItemIdentifier:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)configureForDisplayMode:(unsigned long)arg1 andSizeMode:(unsigned long)arg2;
- (void)validate;
- (id)control;
- (void)controlAction:(id)arg1;
- (void)setSegmentCount:(long)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)labelForSegment:(long)arg1;
- (void)setLabel:(id)arg1 forSegment:(long)arg2;
- (void)setAlternateLabel:(id)arg1 forSegment:(long)arg2;
- (id)paletteLabelForSegment:(long)arg1;
- (void)setPaletteLabel:(id)arg1 forSegment:(long)arg2;
- (SEL)actionForSegment:(long)arg1;
- (void)setAction:(SEL)arg1 forSegment:(long)arg2;
- (id)targetForSegment:(long)arg1;
- (void)setTarget:(id)arg1 forSegment:(long)arg2;
- (void)setTag:(long)arg1 forSegment:(long)arg2;
- (void)setToolTip:(id)arg1 forSegment:(long)arg2;
- (void)setMenu:(id)arg1 forSegment:(long)arg2;

@end

