/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TableViewManager.h"

@interface TableViewManager (AppleScript)
+ (id)_getDarkerThreadBackgroundColorForThread:(id)arg1;
+ (id)_getThreadBackgroundColorForThread:(id)arg1;
- (int)_columnForAppleScriptColumn:(int)arg1;
- (int)appleScriptSortColumn;
- (void)setAppleScriptSortColumn:(int)arg1;
- (id)appleScriptVisibleColumns;
- (void)setAppleScriptVisibleColumns:(id)arg1;
@end

