/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSMenuDelegate-Protocol.h"

@class NSArray;

@interface TextEncodingMenuDelegate : NSObject <NSMenuDelegate>
{
    NSArray *_displayedCharsets;
}

- (void)dealloc;
- (id)displayedCharsets;
- (void)setDisplayedCharsets:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (BOOL)menuHasKeyEquivalent:(id)arg1 forEvent:(id)arg2 target:(id *)arg3 action:(SEL *)arg4;

@end

