/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSCell;

@interface ToDoTitleCell : NSTextFieldCell
{
    NSCell *titleCell;
    NSCell *linkCell;
    BOOL _mouseDownInLinkButton;
    SEL _linkButtonAction;
    BOOL _expanding;
}

+ (void)initialize;
+ (BOOL)prefersTrackingUntilMouseUp;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)_toDoTitleCellCommonInit;
- (void)setLineBreakMode:(unsigned long)arg1;
- (void)setAlignment:(unsigned long)arg1;
- (void)setFont:(id)arg1;
- (void)setBackgroundStyle:(long)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (SEL)linkButtonAction;
- (void)setLinkButtonAction:(SEL)arg1;
- (struct CGRect)linkButtonRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (id)attributedTitle;
- (void)drawTitleWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawLinkButtonWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)expansionFrameWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithExpansionFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (struct CGRect)contentsFrameForCellFrame:(struct CGRect)arg1;
- (unsigned long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long)arg5 length:(long)arg6;
- (void)addTrackingAreasForView:(id)arg1 inRect:(struct CGRect)arg2 withUserInfo:(id)arg3 mouseLocation:(struct CGPoint)arg4;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)accessibilityPerformAction:(id)arg1;

@end

