/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSMenuDelegate-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class ChildWindowController, NSFont, NSMenu, NSMutableSet, ToDoListDatePanel, ToDoListView, ToDoMall;

@interface ToDoListController : NSObject <NSMenuDelegate, NSTableViewDelegate>
{
    ToDoListView *_listView;
    ToDoMall *_todoMall;
    id _delegate;
    NSMutableSet *_selection;
    NSFont *_font;
    NSFont *_boldFont;
    NSMenu *_headerMenu;
    NSMenu *_contextMenu;
    NSMenu *_calendarMenu;
    NSMenu *_priorityMenu;
    NSMenu *_dueDateMenu;
    NSMenu *_completeDateMenu;
    struct {
        unsigned int showAlertForPastDue:1;
        unsigned int showIncompleteInBold:1;
        unsigned int allowSubjectEditing:1;
        unsigned int allowDateDueEditing:1;
        unsigned int allowDateCompletedEditing:1;
        unsigned int allowPriorityEditing:1;
        unsigned int allowCalendarEditing:1;
        unsigned int isShowingSearchResults:1;
        unsigned int allowTableEditingWhenShowingDetails:1;
        unsigned int reserved:23;
    } _flags;
    BOOL _applyingUserDefaults;
    ChildWindowController *_childController;
    int _childWindowAttachmentRow;
    BOOL _userDidEditText;
    ToDoListDatePanel *_datePanel;
}

- (void)_initCalendarMenu;
- (void)_initPriorityMenu;
- (void)_updatePriorityMenu:(id)arg1 withEffectivePriorities:(id)arg2;
- (void)_updateSelection;
- (void)_updateColumnInfo;
- (id)_selectedCalendars;
- (id)_disabledGrayTextForNoPriority;
- (id)undoManager;
- (void)deleteToDosWithUndo:(id)arg1;
- (void)addAndSelectToDosWithUndo:(id)arg1;
- (void)_setDetailsWindowRelatedColumnsEditable:(BOOL)arg1;
- (BOOL)selectNextToDoMovingDownward:(BOOL)arg1;
- (void)copyToDos:(id)arg1 toPasteboard:(id)arg2;
- (unsigned long)addToDosFromPasteboard:(id)arg1;
- (void)_setColumnWithTag:(unsigned long)arg1 visible:(BOOL)arg2;
- (id)_sortDescriptorsFromArchivedData:(id)arg1;
- (BOOL)_todosHaveAlarms:(id)arg1;
- (BOOL)_canAddAlarmForToDos:(id)arg1;
- (void)_applyDateFromUserSheetWithMessage:(id)arg1 forToDos:(id)arg2 applyDateSelector:(SEL)arg3;
- (void)_changeDueDate:(id)arg1 forToDos:(id)arg2;
- (void)_changeCompletedDate:(id)arg1 forToDos:(id)arg2;
- (void)_editToDo:(id)arg1 withTableColumn:(id)arg2;
- (BOOL)_selectionCanChangeToEffectivePriority:(int)arg1;
- (id)init;
- (void)awakeFromNib;
- (void)finalizeSetupAndAttachMall:(id)arg1;
- (void)setCalendarMenu:(id)arg1;
- (id)calendarMenu;
- (void)setPriorityMenu:(id)arg1;
- (id)priorityMenu;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)readDefaultsFromDictionary:(id)arg1;
- (void)writeDefaultsToDictionary:(id)arg1;
- (void)setMailboxUids:(id)arg1;
- (BOOL)showCompleted;
- (void)setShowCompleted:(BOOL)arg1;
- (void)reload:(id)arg1;
- (id)selectedItems;
- (BOOL)selectionIsEditable;
- (id)font;
- (id)boldFont;
- (void)setFont:(id)arg1;
- (float)fontSize;
- (void)setFontSize:(float)arg1;
- (BOOL)showsAlertForPastDue;
- (void)setShowsAlertForPastDue:(BOOL)arg1;
- (BOOL)showsIncompleteItemsInBold;
- (void)sethowsIncompleteItemsInBold:(BOOL)arg1;
- (void)changeCalendar:(id)arg1;
- (void)changePriority:(id)arg1;
- (void)changeDateDue:(id)arg1;
- (void)changeDateComplete:(id)arg1;
- (void)removeAlarms:(id)arg1;
- (void)editAlarms:(id)arg1;
- (void)deleteSelected:(id)arg1;
- (void)toggleCompleted:(id)arg1;
- (void)showToDoMessageReference:(id)arg1 inSeparateWindow:(BOOL)arg2;
- (void)jumpToMessage:(id)arg1;
- (void)toggleColumnVisible:(id)arg1;
- (void)selectItems:(id)arg1;
- (void)selectToDo:(id)arg1;
- (void)editSelectedToDo:(id)arg1;
- (void)editSelectedToDoAndDisplayDetails:(id)arg1;
- (void)editToDo:(id)arg1;
- (void)jumpToiCal:(id)arg1;
- (void)clearSearch;
- (BOOL)isShowingSearchResults;
- (void)searchForString:(id)arg1 in:(int)arg2 withSelectedMailboxes:(id)arg3 withOptions:(int)arg4;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)viewerPreferencesChanged:(id)arg1;
- (void)applySettingsFromDefaults:(id)arg1;
- (void)saveSettingsToDefaults:(id)arg1;
- (long)numberOfRowsInTableView:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long)arg4;
- (void)tableView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldMakeFocusedCell:(id)arg2;
- (BOOL)tableView:(id)arg1 writeRowsWithIndexes:(id)arg2 toPasteboard:(id)arg3;
- (unsigned long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long)arg3 proposedDropOperation:(unsigned long)arg4;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long)arg3 dropOperation:(unsigned long)arg4;
- (void)controlTextDidBeginEditing:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)moveLeft:(id)arg1;
- (void)toDoListContentsWillCompletelyChange;
- (void)toDoListContentsDidCompletelyChange;
- (void)toDoListWasSorted;
- (void)toDosAddedAtIndexes:(id)arg1;
- (void)toDosDeletedAtIndexes:(id)arg1;
- (void)toDosUpdatedAtIndexes:(id)arg1;
- (BOOL)selectionShouldChangeInTableView:(id)arg1;
- (void)tableView:(id)arg1 didClickTableColumn:(id)arg2;
- (void)tableView:(id)arg1 didDragTableColumn:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldEditTableColumn:(id)arg2 row:(long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long)arg2;
- (BOOL)tableView:(id)arg1 shouldSelectTableColumn:(id)arg2;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long)arg4;
- (void)tableViewBoundsDidChange:(id)arg1;
- (void)tableViewFrameDidChange:(id)arg1;
- (void)tableViewColumnDidMove:(id)arg1;
- (void)tableViewColumnDidResize:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)sortByTagOfSender:(id)arg1;
- (void)makeToDoListFirstResponder;
- (id)detailsWindowController:(id)arg1 undoManagerForWindow:(id)arg2;
- (void)displayAlarmsWindowForRows:(id)arg1;
- (void)displayDetailsWindowForRow:(long)arg1;
- (void)_childController;
- (BOOL)childWindowIsVisible;
- (void)closeChildWindow;
- (id)childWindowController;
- (void)setChildWindowController:(id)arg1;
- (void)windowDidSelectNextKeyView:(id)arg1;
- (void)childWindowDidBecomeKey:(id)arg1;
- (void)childWindowWillClose:(id)arg1;
- (void)listViewBoundsOrFrameDidChange:(id)arg1;
- (struct CGPoint)childWindowController:(id)arg1 bestFrameOriginForWindow:(id)arg2;
- (void)cut:(id)arg1;
- (void)copy:(id)arg1;
- (void)paste:(id)arg1;
- (BOOL)canInsertFromPasteboard;

@end

