/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDatePicker, NSTextField, ToDoListView;

@interface ToDoListDatePanel : NSObject
{
    ToDoListView *_listView;
    SEL _selectorToApply;
    id _target;
    NSArray *_todos;
    NSTextField *_messageTextField;
    NSDatePicker *_datePicker;
}

- (id)initWithListView:(id)arg1;
- (void)dealloc;
- (void)requestDateWithMessage:(id)arg1 forToDos:(id)arg2 applyDateSelector:(SEL)arg3 toTarget:(id)arg4;
- (void)confirm:(id)arg1;
- (void)cancel:(id)arg1;

@end

