/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class MailboxUid, MessageStore, NSArray, NSMutableArray;

@interface TransferOperation : NSObject
{
    MessageStore *_sourceStore;
    MailboxUid *_destinationMailboxUid;
    NSArray *_unreadSourceMessages;
    NSArray *_destinationMessageIDs;
    NSMutableArray *_sourceMessages;
    NSMutableArray *_documentIDs;
    BOOL _editableDocuments;
}

- (void)dealloc;
- (id)initWithSourceStore:(id)arg1 destinationMailboxUid:(id)arg2 editableDocuments:(BOOL)arg3;
- (id)sourceLibraryStore;
- (id)documentIDs;
- (id)sourceMessages;
- (void)setSourceMessages:(id)arg1;
- (void)addSourceMessage:(id)arg1;
- (void)removeSourceMessages:(id)arg1;
- (BOOL)editableDocuments;
- (id)destinationMessageIDs;
- (void)setDestinationMessageIDs:(id)arg1;
- (id)unreadSourceMessages;
- (void)setUnreadSourceMessages:(id)arg1;
- (id)destinationMailboxUid;
- (id)sourceStore;

@end

