/*
 *     Generated by class-dump 3.2 (32 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "WebHTMLView.h"

@interface WebHTMLView (ToReplaceViewWithOurOwn)
+ (id)allocWithZone:(struct _NSZone *)arg1;
@end

