/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (FontAdditions)
+ (double)headerFontSize;
+ (id)messageNumberAttributes;
+ (id)selectionBlueHeaderAttributes;
+ (id)lightGrayHeaderAttributes;
+ (id)fixedPitchAttributes;
+ (id)headerAttributes;
+ (id)linkHeaderAttributes;
+ (id)blueHeaderAttributes;
+ (id)mediumWhiteHeaderAttributes;
+ (id)bigBoldWhiteHeaderAttributes;
+ (id)boldGrayHeaderAttributes;
+ (id)boldHeaderAttributes;
+ (void)resetMimeHeaderAttributes;
@end

