/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSOutlineViewDataSource.h"
#import "NSOutlineViewDelegate.h"

@class FavoritesMenuOutlineView, MFMailbox, NSScrollView, NSTimer, NSView, NSWindow;

@interface FavoritesMenuController : NSObject <NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    NSWindow *_window;
    NSWindow *_parentWindow;
    MFMailbox *_mailbox;
    NSScrollView *_scrollView;
    FavoritesMenuOutlineView *_outlineView;
    id _mouseClickedMonitor;
    BOOL _isOpeningMenu;
    NSView *_upScrollHoverView;
    NSView *_downScrollHoverView;
    BOOL _needsScrollers;
    NSTimer *_scrollTimer;
    BOOL _isScrolling;
    id _delegate;
}

+ (void)closeExitingMenu;
@property(readonly) BOOL isScrolling; // @synthesize isScrolling=_isScrolling;
@property id delegate; // @synthesize delegate=_delegate;
- (void)stopScrolling:(unsigned long long)arg1;
- (void)stopScrolling;
- (void)startScrolling:(unsigned long long)arg1;
- (void)updateScrollArrows;
- (void)_scrollToNextPoint:(id)arg1;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (BOOL)_canDragMessageIntoMailbox:(id)arg1;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (unsigned long long)_dragOperationForCurrentEvent;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)_nibForFavoriteMenuItemView;
- (id)_titleForTopLevelMailbox:(id)arg1;
- (void)presentPopupAtLocation:(struct CGPoint)arg1;
- (void)_insertOutlineViewInScrollView;
- (void)_constrainWindowToScreen;
- (void)_sizeWindowToFitCells;
- (struct CGSize)_windowSizeForOutlineViewSize:(struct CGSize)arg1;
- (void)_mouseClickedInApplicationWithEvent:(id)arg1;
- (void)_dragEnded:(id)arg1;
- (void)_applicationShouldClosePopup:(id)arg1;
- (void)closePopup;
- (void)dealloc;
- (void)_cleanupMenu;
- (id)initWithMailbox:(id)arg1 atWindow:(id)arg2;

@end

