/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol StackDataSource
- (void)stackController:(id)arg1 loadDataForItem:(id)arg2 inLayer:(id)arg3;
- (BOOL)stackController:(id)arg1 isDataLoadedForItem:(id)arg2 inLayer:(id)arg3;
- (id)stackController:(id)arg1 layerForItem:(id)arg2;
- (id)stackContainerView;
- (id)stackContainerLayerForStackController:(id)arg1;
@end

