/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying.h"

@class MFSyncedFile, NSData, NSString;

@interface Signature : NSObject <NSCopying>
{
    NSString *_name;
    NSData *_webArchiveData;
    BOOL _isRich;
    BOOL _isSavedAsRich;
    BOOL _isDirty;
    NSString *_uniqueId;
    MFSyncedFile *_syncedFile;
}

@property(readonly, nonatomic) MFSyncedFile *syncedFile; // @synthesize syncedFile=_syncedFile;
@property(nonatomic) BOOL isDirty; // @synthesize isDirty=_isDirty;
@property(readonly, nonatomic) BOOL isSavedAsRich; // @synthesize isSavedAsRich=_isSavedAsRich;
@property(readonly, copy, nonatomic) NSString *uniqueId; // @synthesize uniqueId=_uniqueId;
- (void).cxx_destruct;
- (id)signaturePath;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic) BOOL isRich;
- (void)setWebArchive:(id)arg1;
- (id)webArchive;
- (id)_sanitizeSignatureFileData:(id)arg1;
- (void)_makeWebArchiveDataIfNeeded;
- (id)webArchiveData;
- (void)reloadFromDisk;
@property(copy, nonatomic) NSString *name;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)dictionaryRepresentation;
- (void)removeContentFromDisk;
- (BOOL)saveContentToDisk;
- (id)initWithDictionary:(id)arg1;
- (id)init;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 uniqueId:(id)arg2;
- (id)objectSpecifier;
- (void)setSignatureContents:(id)arg1;
- (id)signatureContents;
- (void)setSignatureName:(id)arg1;
- (id)signatureName;

@end

