/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface TableViewScrollState : NSObject
{
    long long _type;
    long long _pinnedRow;
    double _offsetFromTop;
}

@property(nonatomic) double offsetFromTop; // @synthesize offsetFromTop=_offsetFromTop;
@property(nonatomic) long long pinnedRow; // @synthesize pinnedRow=_pinnedRow;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

