/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MCCIDURLProtocolDataProvider.h"

@class NSData, NSImage, NSString, NSURL;

@interface _MUIWebAttachmentIconPrintingDataProvider : NSObject <MCCIDURLProtocolDataProvider>
{
    NSImage *_iconImage;
    NSURL *_cidURL;
}

@property(retain) NSURL *cidURL; // @synthesize cidURL=_cidURL;
@property(retain) NSImage *iconImage; // @synthesize iconImage=_iconImage;
@property(readonly) NSData *data;
@property(readonly) NSString *mimeType;
- (void)dealloc;
- (id)initWithImage:(id)arg1;

// Remaining properties
@property(readonly) long long fileSize;

@end

