/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/AccountSetupEnabler.h>

#import "NSURLConnectionDelegate-Protocol.h"

@interface _GoogleAccountSetupEnabler : AccountSetupEnabler <NSURLConnectionDelegate>
{
    BOOL _isEnabling;
}

+ (BOOL)_canHandleHostname:(id)arg1;
- (void)synchronouslyEnable;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;

@end

