/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/ThrowingInvocationOperation.h>

@class NSMutableSet, NSString;

@interface _WriteSyncStateOperation : ThrowingInvocationOperation
{
    NSMutableSet *_itemIdStrings;
    NSString *_syncState;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (id)initWithStore:(id)arg1 syncState:(id)arg2;
- (void)dealloc;
- (void)setIdStrings:(id)arg1;
- (void)removeIdStringsForItemIdTypes:(id)arg1;
- (void)removeIdStringsForMessages:(id)arg1;
- (void)cancel;
- (BOOL)isReady;
- (id)description;
@property(retain, nonatomic) NSString *syncState; // @synthesize syncState=_syncState;

@end

