/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABLDAP_ResultElement.h"

@interface ABLDAP_ResultElement (MessageAdditions)
- (BOOL)isGroup;
- (int)recordType;
- (id)middleName;
- (id)nickname;
- (id)extension;
- (id)firstAndMiddleNames;
- (id)lastNameAndExtension;
- (id)compoundName;
- (id)_fullName;
- (id)compoundNameAndEmail;
- (BOOL)exactlyMatchesString:(id)arg1;
@end

