/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSEnumerator.h"

@class NSArray, NSDictionary;

@interface ConnectionEnumerator : NSEnumerator
{
    NSDictionary *_connectionsByMailboxName;
    NSArray *_allMailboxNames;
    id _lastObjectKey;
    unsigned long long _allMailboxNamesCount;
    unsigned long long _positionInMailboxNames;
    NSEnumerator *_nullEnumerator;
}

- (void)dealloc;
- (id)initWithConnectionDictionary:(id)arg1;
- (id)init;
- (id)nextObject;
- (id)lastObjectKey;

@end

