/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class NSData;

@interface DataScanner : NSObject
{
    NSData *_myData;
    unsigned long long _myLocation;
}

+ (id)scannerWithData:(id)arg1;
- (id)initWithData:(id)arg1;
- (void)dealloc;
- (id)data;
- (unsigned long long)scanLocation;
- (void)setScanLocation:(unsigned long long)arg1;
- (BOOL)isAtEnd;
- (BOOL)scanByte:(char *)arg1;
- (BOOL)scanInteger:(long long *)arg1;
- (BOOL)scanData:(id)arg1 intoData:(id *)arg2;
- (BOOL)scanCString:(const char *)arg1 intoData:(id *)arg2;
- (BOOL)_scanBytes:(const void *)arg1 length:(unsigned long long)arg2 intoData:(id *)arg3;
- (BOOL)scanBytesFromSet:(id)arg1 intoData:(id *)arg2;
- (BOOL)scanUpToData:(id)arg1 intoData:(id *)arg2;
- (BOOL)scanUpToCString:(const char *)arg1 intoData:(id *)arg2;
- (BOOL)_scanUpToBytes:(const void *)arg1 length:(unsigned long long)arg2 intoData:(id *)arg3;
- (BOOL)scanUpToBytesFromSet:(id)arg1 intoData:(id *)arg2;

@end

