/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/EWSCreateItemRequestOperation.h>

#import "NSCoding-Protocol.h"

@class EWSGetItemsResponseOperation, Message, NSData, NSDictionary, NSString;

@interface EWSCreateMessageRequestOperation : EWSCreateItemRequestOperation <NSCoding>
{
    EWSGetItemsResponseOperation *_getItemsResponse;
    Message *_message;
    NSData *_data;
    NSString *_sender;
    NSString *_existingItemIdString;
    NSDictionary *_recipientsByHeaderKey;
    unsigned int _flags;
}

- (id)initWithMessage:(id)arg1 data:(id)arg2 folderIdString:(id)arg3 messageType:(BOOL)arg4 flags:(unsigned int)arg5 existingItemIdString:(id)arg6 sender:(id)arg7 recipientsByHeaderKey:(id)arg8 disposition:(long long)arg9 gateway:(id)arg10 errorHandler:(id)arg11;
- (void)_ewsCreateMessageRequestOperationCommonInitWithMessage:(id)arg1 data:(id)arg2 flags:(unsigned int)arg3 existingItemIdString:(id)arg4 sender:(id)arg5 recipientsByHeaderKey:(id)arg6;
- (id)initWithFolderIdString:(id)arg1 messageType:(BOOL)arg2 disposition:(long long)arg3 gateway:(id)arg4 errorHandler:(id)arg5;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)prepareRequest;
@property(retain, nonatomic) EWSGetItemsResponseOperation *getItemsResponse; // @synthesize getItemsResponse=_getItemsResponse;
@property(retain, nonatomic) NSDictionary *recipientsByHeaderKey; // @synthesize recipientsByHeaderKey=_recipientsByHeaderKey;
@property(copy, nonatomic) NSString *existingItemIdString; // @synthesize existingItemIdString=_existingItemIdString;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) unsigned int flags; // @synthesize flags=_flags;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) Message *message; // @synthesize message=_message;

@end

