/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "NSCoding-Protocol.h"

@class EWSAccount, EWSConnection, NSDictionary, NSMutableArray, NSMutableDictionary, NSOperationQueue;

@interface EWSGateway : NSObject <NSCoding>
{
    EWSAccount *_account;
    NSOperationQueue *_requestResponseQueue;
    NSMutableArray *_offlineRequests;
    NSDictionary *_savedOfflineToRealEWSIdStrings;
    NSMutableDictionary *_pendingSyncOperations;
    NSMutableDictionary *_headersByItemIdStringForSync;
    NSOperationQueue *_syncOperationQueue;
    NSOperationQueue *_rulesQueue;
}

+ (id)newTemporaryItemId;
- (id)initWithAccount:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)addRequest:(id)arg1;
- (void)addResponse:(id)arg1;
- (void)addError:(id)arg1 withHandler:(id)arg2;
- (void)sendMessage:(id)arg1 forRequest:(id)arg2;
- (void)takeRequestOffline:(id)arg1 error:(id)arg2;
- (id)fetchDistinguishedFolderIdsWithConnection:(id)arg1;
- (void)saveRequestToOfflineCache:(id)arg1;
- (void)_saveOfflineCache;
- (void)_addCreateRequestToOfflineCache:(id)arg1;
- (void)_addDeleteRequestToOfflineCache:(id)arg1;
- (void)playbackRequestsFromOfflineCacheWithConnection:(id)arg1 error:(id *)arg2;
- (BOOL)writeMessageToOfflineCache:(id)arg1 data:(id)arg2 forItemIdString:(id)arg3;
- (void)retrieveMessageFromOfflineCache:(id *)arg1 data:(id *)arg2 forItemIdString:(id)arg3;
- (void)removeMessageAndDataFromOfflineCacheForEWSItemIdString:(id)arg1;
- (id)_offlineCachePath;
- (id)_offlineCachePathForMessageWithItemIdString:(id)arg1;
- (id)_offlineCachePathForDataWithItemIdString:(id)arg1;
@property(readonly) EWSConnection *connection;
- (id)syncFolderHierarchyWithSyncState:(id)arg1;
- (id)_syncFolderHierarchyWithSyncState:(id)arg1 includesLastItem:(char *)arg2;
- (id)syncFolderItemsFromFolderIdString:(id)arg1 syncState:(id)arg2 forStore:(id)arg3;
- (id)_syncFolderItemsFromTargetFolderIdType:(id)arg1 syncState:(id)arg2 forStore:(id)arg3 includesLastItem:(char *)arg4;
- (void)_handleSyncedMessagesWithoutHeaders:(id)arg1 inFolderIdString:(id)arg2 store:(id)arg3 newSyncState:(id)arg4;
- (void)setEWSIdStringsBlockingSyncCompletion:(id)arg1 syncState:(id)arg2 forFolderIdString:(id)arg3;
- (void)setHeaders:(id)arg1 forItemIdString:(id)arg2;
- (void)routeMessagesAndAddToLibrary:(id)arg1 toStore:(id)arg2;
- (void)updateMessagesLocallyFromSync:(id)arg1 inStore:(id)arg2 withFolderIdString:(id)arg3 newMessageIDs:(id)arg4 newSyncState:(id)arg5;
- (void)_updateMessagesLocallyFromSync:(id)arg1 inStore:(id)arg2 withFolderIdString:(id)arg3 newMessageIDs:(id)arg4 newSyncState:(id)arg5;
- (void)cancelSyncOfFolderItemsFromFolderIdString:(id)arg1;
- (void)removeIdStringsForMessagesThatSynced:(id)arg1 fromFolderWithIdString:(id)arg2;
- (void)_cancelWriteSyncStateOperationForFolderIdString:(id)arg1 withSyncState:(id)arg2;
- (void)_saveData:(id)arg1 forMessage:(id)arg2 isPartial:(BOOL)arg3 updateMetadata:(BOOL)arg4;
- (id)fetchMimeDataForMessage:(id)arg1 errorHandler:(id)arg2;
- (id)_EWSItemTypesWithBodyDataForMessages:(id)arg1 errorHandler:(id)arg2;
- (void)cacheDataForLibraryMessages:(id)arg1 store:(id)arg2 folderIdString:(id)arg3 errorHandler:(id)arg4;
- (void)_cacheDataForLibraryMessages:(id)arg1 store:(id)arg2 folderIdString:(id)arg3 errorHandler:(id)arg4;
- (id)appendMessage:(id)arg1 withData:(id)arg2 toEWSFolderWithIdString:(id)arg3 messageType:(BOOL)arg4 flags:(unsigned int)arg5 sender:(id)arg6 recipientsByHeaderKey:(id)arg7 send:(BOOL)arg8 errorHandler:(id)arg9;
- (void)deleteMessagesWithEWSItemIds:(id)arg1 fromFolderWithEWSIdString:(id)arg2 synchronously:(BOOL)arg3;
- (void)setFlagsFromDictionary:(id)arg1 forMessages:(id)arg2 inFolderWithEWSIdString:(id)arg3 errorHandler:(id)arg4;
- (id)copyMessagesWithEWSItemIds:(id)arg1 fromFolderWithIdString:(id)arg2 toFolderWithIdString:(id)arg3 synchronously:(BOOL)arg4 errorHandler:(id)arg5;
- (void)sendResponseType:(BOOL)arg1 forMeetingMessage:(id)arg2 inStore:(id)arg3 errorHandler:(id)arg4;
- (void)undeleteMessageForFailedCreateEventResponse:(id)arg1;
- (void)_fetchMeetingRequestMessages:(id)arg1 errorHandler:(id)arg2;
- (void)_fetchMeetingCancellationMessages:(id)arg1 errorHandler:(id)arg2;
- (id)createMailboxWithParentEWSFolderIdString:(id)arg1 name:(id)arg2 mailboxType:(int)arg3 error:(id *)arg4;
- (BOOL)renameMailboxWithEWSFolderIdString:(id)arg1 to:(id)arg2 error:(id *)arg3;
- (BOOL)moveMailboxWithEWSFolderIdString:(id)arg1 to:(id)arg2 error:(id *)arg3;
- (BOOL)deleteMailboxWithEWSFolderIdString:(id)arg1 error:(id *)arg2;
- (id)resolvedIdStringForIdString:(id)arg1;
- (void)addOfflineToRealEWSIdStrings:(id)arg1 forRequest:(id)arg2;
- (CDStruct_d3e19d9e)fetchUsageInfoForEWSFolderIdString:(id)arg1;
- (void)getOofSettings;
- (void)setOofState:(long long)arg1 internalReply:(id)arg2 externalReply:(id)arg3 startTime:(id)arg4 endTime:(id)arg5 externalAudienceType:(long long)arg6;
- (void)_chunkItemsToSend:(id)arg1 applyToBlock:(id)arg2;
- (unsigned long long)_maxRequestsToSend;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_logPendingSyncOperations:(id)arg1;
- (id)fetchCopyOfSyncIssuesEntryID;
@property(retain, nonatomic) NSOperationQueue *rulesQueue; // @synthesize rulesQueue=_rulesQueue;
@property(retain, nonatomic) NSDictionary *savedOfflineToRealEWSIdStrings; // @synthesize savedOfflineToRealEWSIdStrings=_savedOfflineToRealEWSIdStrings;
@property(retain, nonatomic) NSMutableArray *offlineRequests; // @synthesize offlineRequests=_offlineRequests;
@property(retain, nonatomic) NSOperationQueue *syncOperationQueue; // @synthesize syncOperationQueue=_syncOperationQueue;
@property(retain, nonatomic) NSOperationQueue *requestResponseQueue; // @synthesize requestResponseQueue=_requestResponseQueue;
@property(nonatomic) EWSAccount *account; // @synthesize account=_account;

@end

