/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

@class NSArray;

@interface EWSGetFolderRequestOperation : EWSRequestOperation
{
    NSArray *_EWSFolderIds;
    BOOL _fetchEntryIDs;
}

+ (Class)classForResponse;
- (id)initWithEWSFolderIds:(id)arg1 gateway:(id)arg2 errorHandler:(id)arg3 fetchEntryIDs:(BOOL)arg4;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (void)dealloc;
- (id)activityString;
- (BOOL)isFolderRequest;
- (id)prepareRequest;
@property(retain, nonatomic) NSArray *EWSFolderIds; // @synthesize EWSFolderIds=_EWSFolderIds;

@end

