/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

#import "NSCoding-Protocol.h"

@class EWSGetFolderResponseOperation, NSArray, NSString;

@interface EWSMoveFolderRequestOperation : EWSRequestOperation <NSCoding>
{
    NSString *_destinationEWSFolderIdString;
    NSArray *_originEWSFolderIdStrings;
    EWSGetFolderResponseOperation *_changeKeysResponse;
}

+ (Class)classForResponse;
- (id)initWithEWSFolderIdString:(id)arg1 originEWSFolderIdStrings:(id)arg2 gateway:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (void)dealloc;
- (id)activityString;
- (BOOL)isFolderRequest;
- (id)prepareRequest;
- (void)setupOfflineResponse;
@property(retain, nonatomic) NSArray *originEWSFolderIdStrings; // @synthesize originEWSFolderIdStrings=_originEWSFolderIdStrings;
@property(retain, nonatomic) EWSGetFolderResponseOperation *changeKeysResponse; // @synthesize changeKeysResponse=_changeKeysResponse;
@property(copy, nonatomic) NSString *destinationEWSFolderIdString; // @synthesize destinationEWSFolderIdString=_destinationEWSFolderIdString;

@end

