/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class NSMutableArray;

@interface IMAPCommandPipeline : NSObject
{
    id _imapCommandPipelineLock;
    unsigned int _chunkSize;
    unsigned int _expectedSize;
    BOOL _isSending;
    BOOL _isFull;
    NSMutableArray *_fetchUnits;
    double _startedSendingTime;
}

- (void)dealloc;
- (id)init;
- (id)imapCommandPipelineLock;
- (void)addFetchCommandForUid:(unsigned int)arg1 fetchItem:(id)arg2 expectedLength:(unsigned int)arg3;
- (void)_removeFetchUnitMatchingResponse:(id)arg1;
- (id)failureResponsesFromSendingCommandsWithGateway:(id)arg1 responseHandler:(id)arg2 highPriority:(BOOL)arg3;
- (id)_lockedNewOperationsAssigningResponseHandler:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property double startedSendingTime; // @synthesize startedSendingTime=_startedSendingTime;
@property(retain) NSMutableArray *fetchUnits; // @synthesize fetchUnits=_fetchUnits;
@property BOOL isFull; // @synthesize isFull=_isFull;
@property BOOL isSending; // @synthesize isSending=_isSending;
@property unsigned int expectedSize; // @synthesize expectedSize=_expectedSize;
@property unsigned int chunkSize; // @synthesize chunkSize=_chunkSize;

@end

