/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/IMAPSingleClientOperation.h>

@class NSMutableArray;

@interface IMAPClientFetchOperation : IMAPSingleClientOperation
{
    CDStruct_f792af56 _range;
    NSMutableArray *_dataItems;
    id <IMAPResponseHandler> _responseHandler;
}

+ (id)_headersToFetch;
+ (id)_fetchDataItemsForMessageSkeletonsWithHeaders:(id)arg1;
- (id)init;
- (id)initWithRange:(CDStruct_f792af56)arg1;
- (void)dealloc;
- (id)commandTypeString;
- (void)addDataItem:(id)arg1;
- (void)addMessageSkeletonDataItemsWithAdditionalHeaderFields:(id)arg1;
- (void)addMessageUidsAndFlagsDataItemsWithAdditionalHeaderFields:(id)arg1;
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;
- (BOOL)executeOnConnection:(id)arg1;
- (id)_newMessageSetCommandString;
- (id)_fetchDataItemsForMessageSkeletonsWithAdditionalHeaderFields:(id)arg1;
@property(retain) id <IMAPResponseHandler> responseHandler; // @synthesize responseHandler=_responseHandler;
@property(retain) NSMutableArray *dataItems; // @synthesize dataItems=_dataItems;
@property CDStruct_f792af56 range; // @synthesize range=_range;

@end

