/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/RemoteStoreSizeEngine.h>

@class NSMutableDictionary, NSMutableSet;

@interface IMAPSizeEngine : RemoteStoreSizeEngine
{
    unsigned long long _workerThreadCount;
    NSMutableDictionary *_mailboxesByQuotaRoot;
    NSMutableSet *_quotasToFetch;
    NSMutableSet *_observedIMAPMailboxes;
    NSMutableSet *_observedIMAPQuotaRoots;
    int _quotaStatus;
}

- (id)initWithAccount:(id)arg1;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_addUsageInfoFromMailbox:(id)arg1;
- (void)_addQuotaRootsFromMailbox:(id)arg1;
- (BOOL)_changeUsageInfo:(CDStruct_d3e19d9e *)arg1 forMailboxUid:(id)arg2 refetchQuotas:(BOOL)arg3;
- (void)_changeQuotaRoots:(id)arg1 forMailboxUid:(id)arg2;
- (void)_mailboxBecameInvalid:(id)arg1;
- (void)_getSizeForMailboxUid:(id)arg1;
- (void)_runWorkerThread;
- (BOOL)_shouldStartWorkerThread;
- (int)quotaStatus;
- (id)quotaNames;
- (id)usageForQuotaName:(id)arg1;
- (id)mutableCopyOfMailboxesForQuotaName:(id)arg1;
- (BOOL)mailbox:(id)arg1 usesQuotaName:(id)arg2;

@end

