/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "IMAPResponseHandler-Protocol.h"

@class NSMutableArray;

@interface IMAPDownloadCache : NSObject <IMAPResponseHandler>
{
    NSMutableArray *_downloads;
}

- (void)dealloc;
- (struct _NSRange)_lockedFindRangeOfDownloadsWithUid:(unsigned int)arg1;
- (id)downloadForMessage:(id)arg1;
- (id)_getDownloadForUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(int)arg3 length:(unsigned int)arg4 estimatedLength:(unsigned int)arg5;
- (id)downloadForUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(int)arg3 length:(unsigned int)arg4;
- (id)downloadForUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(int)arg3 expectedLength:(unsigned int)arg4;
- (void)_lockedUpdateDownloadsInRange:(struct _NSRange)arg1 fetchResults:(id)arg2 error:(id)arg3;
- (BOOL)handleResponse:(id)arg1 forOperation:(id)arg2;
- (void)handleFetchResponse:(id)arg1 forUid:(unsigned int)arg2;
- (void)handleFetchResponses:(id)arg1;
- (void)processResultsForUid:(unsigned int)arg1;
- (void)cleanUpDownloadsForUid:(unsigned int)arg1;
- (void)addDownload:(id)arg1 forUid:(unsigned int)arg2;
- (void)_lockedAddDownload:(id)arg1 atIndex:(unsigned long long)arg2 forUid:(unsigned int)arg3;
- (void)addCommandsForDownload:(id)arg1 toPipeline:(id)arg2;

@end

