/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSOperationQueue.h"

@class NSPort;

@interface InvocationQueue : NSOperationQueue
{
    NSPort *_runLoopCancelPort;
}

+ (void)cancelAllMonitoredItems;
+ (BOOL)didCancelAllMonitoredItems;
- (id)init;
- (id)initWithMaxConcurrentOperationCount:(long long)arg1;
- (void)dealloc;
- (void)finalize;
- (void)addInvocation:(id)arg1;
- (void)runInvocationOnQueueSynchronously:(id)arg1;
- (id)_newOperationWithInvocation:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

