/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/MessageCriterion.h>

@class MessageRule;

@interface MessageRuleCriterion : MessageCriterion
{
    MessageRule *_rule;
}

+ (id)noJunkCriterion;
+ (id)noTrashCriterion;
+ (id)noSentCriterion;
+ (id)conversationsCriterion;
- (void)dealloc;
- (void)setRuleType:(int)arg1;
- (void)setRuleQualifier:(int)arg1;
- (void)setRuleExpression:(id)arg1;
- (void)setMessageRule:(id)arg1;
- (void)setCriterionIdentifier:(id)arg1;
- (id)objectSpecifier;
- (BOOL)performPostSyncingValidation;

@end

