/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSArray.h"

@class NSDictionary;

@interface NSArray (MessagesFromMixedStoresConvenience)
@property(readonly) NSDictionary *dictionaryWithMessagesSortedByStore;
@property(readonly) NSDictionary *dictionaryWithMessagesSortedByMailbox;
@end

