/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (MessageFrameworkAdditions)
- (id)attachments;
- (id)attachmentsInRange:(struct _NSRange)arg1;
- (id)mimeTextAttachments;
- (struct _NSRange)rangeOfAttachment:(id)arg1;
- (BOOL)containsRichTextInRange:(struct _NSRange)arg1;
- (BOOL)containsRichText;
@end

