/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (UuEnDecode)
- (id)uudecodedDataIntoFile:(id *)arg1 mode:(unsigned int *)arg2;
- (id)uuencodedDataWithFile:(id)arg1 mode:(unsigned int)arg2;
@end

