/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSSound.h"

@interface NSSound (MessageAdditions)
+ (void)_playNextSound;
+ (void)_playSound;
+ (void)sound:(id)arg1 didFinishPlaying:(BOOL)arg2;
+ (void)_setupPlayList;
+ (void)_addSoundOrPathToPlayList:(id)arg1 playImmediately:(BOOL)arg2;
+ (void)addSoundToPlayList:(id)arg1 playImmediately:(BOOL)arg2;
+ (void)addSoundPathToPlayList:(id)arg1 playImmediately:(BOOL)arg2;
+ (id)validPathToSound:(id)arg1;
+ (id)systemLibrarySoundsDirs;
+ (id)librarySoundsDirs;
+ (id)networkLibrarySoundsDirs;
+ (id)tildeLibrarySoundsDirs;
+ (id)appendSoundsToPaths:(id)arg1;
+ (id)soundsAtPaths:(id)arg1;
- (void)_playAsMailSound;
@end

