/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@interface ParentalControlSettings : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
+ (BOOL)isEmail:(id)arg1 inEmailList:(id)arg2;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (void)_updateCachedDataForEnabledState:(BOOL)arg1 approvedList:(BOOL)arg2 postNotification:(BOOL)arg3;
- (void)_reallyHandleDefaultsChange;
- (void)_defaultsDidChange;
- (void)_approveEmailListChanged:(id)arg1;
- (BOOL)isInSpamProtectionMode;
- (id)parentEmails;
- (BOOL)isParentEmail:(id)arg1;
- (BOOL)_isSelfEmail:(id)arg1;
- (id)_approvedEmails;
- (BOOL)hasEmailBeenApproved:(id)arg1;
- (BOOL)haveEmailsBeenApproved:(id)arg1 unapprovedOnes:(id)arg2;
- (id)_dictionaryFromEmail:(id)arg1;
- (BOOL)_approveEmail:(id)arg1;
- (id)approveEmails:(id)arg1;
- (BOOL)_rejectEmail:(id)arg1;
- (id)rejectEmails:(id)arg1;
- (double)parentalControlEnabledTimeIntervalSince1970;

@end

