/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@class NSMutableArray;

@interface RemoteStoreAccount : MailAccount
{
    NSMutableArray *_mailboxesToSynchronize;
    BOOL _addedEAToAccountFolder;
}

- (id)initWithAccountInfo:(id)arg1;
- (void)dealloc;
- (void)updateFromSyncedDictionary:(id)arg1;
- (void)setDisplayName:(id)arg1;
- (id)_infoForMatchingURL:(id)arg1;
- (void)fetchSynchronously;
- (BOOL)canGoOffline;
- (void)setCachePolicy:(unsigned long long)arg1 permanently:(BOOL)arg2;
- (unsigned long long)cachePolicy;
@property BOOL storeDraftsOnServer;
@property BOOL storeNotesOnServer;
@property BOOL storeJunkOnServer;
@property(readonly) BOOL storeJunkOnServerDefault;
@property BOOL storeSentMessagesOnServer;
@property BOOL storeTrashOnServer;
- (BOOL)_isMailboxTypeStoredLocally:(int)arg1;
- (BOOL)_setStoreSpecialMailboxUidType:(int)arg1 onServer:(BOOL)arg2;
- (void)_renameLocalSpecialMailboxesToName:(id)arg1;
- (id)_localMailboxNameForType:(int)arg1 usingDisplayName:(id)arg2;
- (id)_specialMailboxUidWithType:(int)arg1 create:(BOOL)arg2;
- (id)_specialMailboxUidWithType:(int)arg1 create:(BOOL)arg2 isLocal:(BOOL)arg3;
- (void)_setSpecialMailbox:(id)arg1 forType:(int)arg2;
- (BOOL)_canEmptyMessagesFromMailboxUid:(id)arg1;
- (void)_writeMailboxCache;
- (BOOL)_shouldCacheAggressively;
- (BOOL)canBeSynchronized;
- (void)considerSynchronizingNow;
- (void)nowWouldBeAGoodTimeToStartBackgroundSynchronization;
- (void)_nowWouldBeAGoodTimeToStartBackgroundSynchronizationWithUserInput:(BOOL)arg1;
- (BOOL)needToSynchronizeMailboxCaches;
- (void)_synchronizeAccountWithServerWithUserInput:(id)arg1;
- (BOOL)_synchronizeMailboxListWithUserInput:(BOOL)arg1;
- (BOOL)synchronizesDataWithServer;
- (void)didSynchronizeMailboxCachesAndFoundChanges:(BOOL)arg1;
- (void)_synchronizeMailboxes:(id)arg1;
- (BOOL)_addMailboxesToSynchronize:(id)arg1;
- (BOOL)_shouldSynchronizeMailbox:(id)arg1;
- (void)_synchronizeMailboxesSynchronously;
- (void)_checkForNewMessagesInStore:(id)arg1;
- (id)offlineCacheDirectory;
- (void)presentOverQuotaAlert;
@property BOOL addedEAToAccountFolder; // @synthesize addedEAToAccountFolder=_addedEAToAccountFolder;

@end

