/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/PlaceholderFileWrapper.h>

@class NSURL;

@interface RemotePlaceholderFileWrapper : PlaceholderFileWrapper
{
    NSURL *_url;
}

- (void)dealloc;
- (id)remoteAccessMimeType;
- (id)initWithURL:(id)arg1;
- (id)initDirectoryWithFileWrappers:(id)arg1;
- (id)initRegularFileWithContents:(id)arg1;
- (id)initSymbolicLinkWithDestination:(id)arg1;
- (id)initWithPath:(id)arg1;
- (id)initWithSerializedRepresentation:(id)arg1;
- (BOOL)isRemotelyAccessed;
- (id)symbolicLinkDestination;
- (id)URL;
- (unsigned long long)approximateSize;

@end

