/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/TransientBookmarkItem.h>

@interface TransientBookmarkFolder : TransientBookmarkItem
{
    BOOL _localizedNameNeedRefresh;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (void)setEntity:(id)arg1;
+ (id)entity;
- (id)bookmarkChildren;
- (BOOL)containsFeed;
- (void)setContainsFeed:(BOOL)arg1;
- (void)calculateContainsFeed;
- (id)localizedName;
- (void)setLocalizedName:(id)arg1;
- (id)feedFolderChildren;
- (id)feedChildren;
- (unsigned long long)_feedChildrenCount;
- (unsigned long long)_feedFolderChildrenCount;
- (void)_updateContainsFeed:(BOOL)arg1;
- (void)didTurnIntoFault;

@end

