/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "ABSearchOperationDelegate-Protocol.h"
#import "RecentsSearchOperationDelegate-Protocol.h"

@class ABAddressBook, CompletionController, NSMutableArray;

@interface _AutocompletionResultsAccumulator : NSObject <ABSearchOperationDelegate, RecentsSearchOperationDelegate>
{
    CompletionController *_completionController;
    NSMutableArray *_mailRecents;
    NSMutableArray *_regularRecords;
    long long _numberOfLocalSearches;
    long long _numberOfRemoteSearches;
    ABAddressBook *_addressBook;
}

- (id)init;
- (void)dealloc;
@property CompletionController *completionController;
- (id)copyCompletionController;
- (void)reset;
- (void)expectLocalSearches:(long long)arg1 remoteSearches:(long long)arg2 addressBook:(id)arg3;
- (BOOL)searchOperationIsValid:(id)arg1;
- (id)addressBook;
- (void)searchOperationDidFinish:(id)arg1;
- (void)recentsSearchOperationDidFinish:(id)arg1;
- (void)searchOperation:(id)arg1 foundRecords:(id)arg2;
- (void)recentsSearchOperation:(id)arg1 foundRecords:(id)arg2;
- (void)sendLocalSearchResultsToCompletionController:(id)arg1;

@end

