/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "DOMRange.h"

@interface DOMRange (MailExtras)
- (id)firstNode;
- (id)lastNode;
- (BOOL)isEquivalentToCollapsedRange;
- (BOOL)includeTemporarySelectionMarkers;
- (void)hoistRange;
- (id)stringValue;
- (id)attributedStringWithDocument:(id)arg1;
- (void)getBlockBoundaryParent:(id *)arg1 nextSibling:(id *)arg2 atStart:(BOOL)arg3;
- (void)fixIfEndpointIsAtBeginningOfLine;
- (void)fixIfStartIsAtEndOfContainerNode;
- (void)balanceContainers;
- (id)rangeOfContainingBlock;
- (BOOL)containsRichTextForMessageFont:(id)arg1;
- (id)attachmentsByURLFromDocument:(id)arg1;
- (void)attachments:(id *)arg1 urls:(id *)arg2 fromDocument:(id)arg3;
- (id)attachmentsFromDocument:(id)arg1;
- (id)stringRepresentation;
- (BOOL)isEqualToRange:(id)arg1;
- (BOOL)containsRange:(id)arg1;
- (void)setWithStringRepresentation:(id)arg1;
- (BOOL)isEditable;
- (BOOL)containsListElements;
- (BOOL)runSelectorOnContents:(SEL)arg1;
- (BOOL)hasNoSignificantContentsOrWhitespace;
- (BOOL)hasNoSignificantContentsOtherThanAttachments;
- (BOOL)hasNoSignificantContents;
@end

