/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSImageView.h"

@interface FlagButtonImageView : NSImageView
{
    BOOL _selected;
    BOOL _displayMouseOverStyle;
}

- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) BOOL displayMouseOverStyle; // @synthesize displayMouseOverStyle=_displayMouseOverStyle;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;

@end

