/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSMenuItem.h"

@class NSMenu;

@interface LazySubmenuMenuItem : NSMenuItem
{
    id _lazySubmenuBlock;
    NSMenu *_loadedSubmenu;
    BOOL _enableLoadedSubmenu;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)setLazySubmenuBlock:(id)arg1;
- (BOOL)hasSubmenu;
- (id)submenu;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;

@end

