/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSSplitViewDelegate-Protocol.h"

@protocol MailVerticalSplitViewDelegate <NSSplitViewDelegate>

@optional
- (void)mailVerticalSplitView:(id)arg1 willSetPosition:(double)arg2 ofDividerAtIndex:(long long)arg3 byAnimating:(BOOL)arg4;
@end

