/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "AddressTextViewDelegate-Protocol.h"

@class EmailViewController, HeaderAttachmentsController, MessageHeaderView, NSAttributedString, NSString, SenderImageView;

@interface MessageHeaderDisplay : NSObject <AddressTextViewDelegate, NSLayoutManagerDelegate, NSTextViewDelegate>
{
    MessageHeaderView *_headerView;
    EmailViewController *_parentController;
    SenderImageView *_senderImageView;
    HeaderAttachmentsController *_headerAttachmentsController;
    NSAttributedString *_dateAttributedString;
    NSString *_unloadedSender;
    double _oldHeaderViewWidth;
    struct CGRect _rectOfFromAddress;
    BOOL _isCalculatingAddressLines;
    BOOL _isForPrinting;
    BOOL _isSelected;
    BOOL _isActiveSelection;
    BOOL _displayAsSingleMessage;
    BOOL _viewIsAboutToBeRemoved;
    unsigned long long _messageNumber;
    long long _relatedMessageType;
    BOOL _messageHasBackground;
}

+ (void)_rangeOfAddresses:(struct _NSRange *)arg1 rangeOfLink:(struct _NSRange *)arg2 forKey:(id)arg3 inAttributedString:(id)arg4;
- (void)_loadRSSImages;
- (void)_loadSMIMEImages;
- (void)_loadSenderPlaceHolderImage;
- (id)_newlineAndTabCharacterSet;
- (id)_attributedStringForSecurityHeader;
- (void)_setAttachmentsDescription;
- (id)_expandedAttributedString;
- (id)_simpleAttributedString;
- (id)_detailsLinkAttributedString;
- (void)_setupHeaderAttributedString;
- (void)_loadRecordsForAddresses;
- (id)_attributedLinkForHideShowDetailsWithString:(id)arg1;
- (BOOL)_prepareToDisplayRSSHeadersForMessage:(id)arg1 viewingState:(id)arg2;
- (void)_addAddressesToString:(id)arg1 addressStrings:(id)arg2 shouldUseBoldFont:(BOOL)arg3 plainAddresses:(id)arg4 addressAttachments:(id)arg5 key:(id)arg6 viewingState:(id)arg7 tabPosition:(long long)arg8 range:(struct _NSRange *)arg9;
- (void)_setSendersFromAddressAttachments:(id)arg1;
- (void)_stripTrailingReturns:(id)arg1;
- (id)attachmentsDescriptionForMessage:(id)arg1 viewingState:(id)arg2;
- (id)_formattedAttachmentsSizeForAttachments:(id)arg1;
- (id)formattedAttachmentsSizeForMessage:(id)arg1;
- (unsigned long long)_numberOfAddressesThatFitOnTwoLinesAttachments:(id)arg1 strings:(id)arg2 inTextContainer:(id)arg3 withIndent:(long long)arg4 andVerticalLocation:(long long)arg5 forPrinting:(BOOL)arg6;
- (id)_linkForMoreAddressesCount:(unsigned long long)arg1 headerKey:(id)arg2 font:(id)arg3;
- (id)_paragraphStyleWithLineHeight:(double)arg1;
- (id)_paragraphStyleWithLineHeight:(double)arg1 indent:(double)arg2;
- (id)_paragraphStyleWithLineHeight:(double)arg1 firstLineHeadIndent:(double)arg2 headIndent:(double)arg3;
- (id)_regularParagraphStyleForTabPosition:(long long)arg1;
- (id)_regularParagraphStyleForTabPosition:(long long)arg1 paragraphSpacing:(long long)arg2;
- (id)_addressParagraphStyleForTabPosition:(long long)arg1 withLineBreakMode:(unsigned long long)arg2 forPrinting:(BOOL)arg3;
- (void)_setTabsWithPosition:(long long)arg1 inAttributedString:(id)arg2 withKeys:(id)arg3 addressKeys:(id)arg4 addressAttachments:(id)arg5 forPrinting:(BOOL)arg6;
- (void)dealloc;
- (id)viewingState;
- (void)_setupHeaderView;
- (void)setHeaderView:(id)arg1;
@property(nonatomic) unsigned long long messageNumber;
@property(nonatomic) long long relatedMessageType;
- (void)_setUpWithViewingState:(id)arg1;
- (id)unloadedSender;
- (void)setUnloadedSender:(id)arg1;
@property BOOL displayAsSingleMessage;
@property BOOL isSelected;
- (void)headerViewWasClicked;
- (void)setIsActiveSelection:(BOOL)arg1;
- (void)setIsForPrinting:(BOOL)arg1;
- (void)_updateTextContainerAndOtherOverlapControls;
- (void)display:(id)arg1;
- (id)_senderAddressAttachment;
- (void)toggleShowHideDetails;
- (void)prepareToRemoveView;
- (void)displayAttributedString:(id)arg1;
- (void)headerViewFrameChanged:(id)arg1;
- (void)_recalculateAddressLinesWithDisplay;
- (void)recalculateAddressLinesShouldDisplay:(BOOL)arg1;
- (void)_urlifySubjectAttributedString:(id)arg1;
- (void)updateSecondaryMessageStatus;
- (void)updateNumberOfDuplicates;
- (void)_updateShowHideLink;
- (id)attachmentsDescription;
- (struct CGRect)attachmentsButtonsFrame;
- (id)messageViewer;
- (id)_attributedStringOfLength:(long long)arg1 usingAttachments:(id)arg2 startingAtIndex:(long long)arg3 strings:(id)arg4 newAttachments:(id *)arg5 forPrinting:(BOOL)arg6;
- (void)showAllAddressesForKey:(id)arg1;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)showDuplicates;
- (void)adjustFontSizeBy:(long long)arg1 viewingState:(id)arg2;
- (id)selectedText;
- (void)reloadFlags;
- (void)_addressBookChanged:(id)arg1;
- (void)_addressPhotoLoaded:(id)arg1;
- (id)textView;
- (void)textView:(id)arg1 clickedOnCell:(id)arg2 event:(id)arg3 inRect:(struct CGRect)arg4 atIndex:(unsigned long long)arg5;
- (void)viewerPreferencesChanged;
- (void)layoutManager:(id)arg1 didCompleteLayoutForTextContainer:(id)arg2 atEnd:(BOOL)arg3;
- (BOOL)isHeaderViewFullyVisible;
- (BOOL)shouldDisplayShowInMailboxLink;
- (struct CGRect)rectOfFromAddress;
@property BOOL messageHasBackground; // @synthesize messageHasBackground=_messageHasBackground;
@property(retain) NSAttributedString *dateAttributedString; // @synthesize dateAttributedString=_dateAttributedString;
@property(assign) EmailViewController *parentController; // @synthesize parentController=_parentController;

@end

