/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class CriteriaUIHelper, MailboxUid, NSButton, NSTextField, NSTextView, NSView;

@interface SmartMailboxEditor : NSObject
{
    MailboxUid *_mailboxBeingEdited;
    MailboxUid *_mailboxBeingValidated;
    CriteriaUIHelper *_criteriaUIHelper;
    NSTextField *_nameField;
    NSTextField *_groupNameField;
    NSTextField *_searchStringField;
    NSTextView *_mailboxesTextView;
    NSButton *_includeTrashCheckbox;
    NSButton *_includeSentCheckbox;
    NSView *_criteriaView;
    BOOL _editedMailboxIsNew;
}

+ (BOOL)isEditingInProgress;
+ (BOOL)mailboxIsEditable:(id)arg1;
- (void)dealloc;
- (void)editSmartMailbox:(id)arg1 suggestedName:(id)arg2 isNew:(BOOL)arg3;
- (void)createNewMailboxGroup;
- (void)_sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)okClicked:(id)arg1;
- (void)cancelClicked:(id)arg1;
- (void)_saveEditedMailbox;

@end

