/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@class BannerContainerViewController, HeaderViewController, MessageViewer, MessageWebDocumentView, NSScrollView, NSSegmentedControl, NSTrackingArea;

@interface MessageViewController : NSViewController <NSMenuDelegate>
{
    BOOL _displayAsSingleton;
    double _pageZoom;
    BannerContainerViewController *_bannerContainerViewController;
    HeaderViewController *_headerViewController;
    NSSegmentedControl *_actionButtons;
    NSScrollView *_bodyScrollView;
    MessageWebDocumentView *_webDocumentView;
    NSTrackingArea *_headerTrackingArea;
}

+ (id)keyPathsForValuesAffectingShowingAllHeaders;
+ (id)keyPathsForValuesAffectingLoaded;
@property(retain, nonatomic) NSTrackingArea *headerTrackingArea; // @synthesize headerTrackingArea=_headerTrackingArea;
@property(retain, nonatomic) MessageWebDocumentView *webDocumentView; // @synthesize webDocumentView=_webDocumentView;
@property(retain, nonatomic) NSScrollView *bodyScrollView; // @synthesize bodyScrollView=_bodyScrollView;
@property(retain, nonatomic) NSSegmentedControl *actionButtons; // @synthesize actionButtons=_actionButtons;
@property(retain, nonatomic) HeaderViewController *headerViewController; // @synthesize headerViewController=_headerViewController;
@property(retain, nonatomic) BannerContainerViewController *bannerContainerViewController; // @synthesize bannerContainerViewController=_bannerContainerViewController;
- (void)linkAccessibilityView:(id)arg1;
- (id)viewWhereMessageExists;
- (id)viewWhereMessageIsDisplayed;
- (BOOL)isHeaderViewFullyVisible;
- (id)headerSnapshot;
- (void)bodySnapshotWithSize:(struct CGSize)arg1 completionBlock:(id)arg2;
- (struct CGSize)visibleBodySize;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)viewSource:(id)arg1;
- (void)showMessageInMailbox:(id)arg1;
- (void)showFilteredHeaders:(id)arg1;
- (void)showAllHeaders:(id)arg1;
- (void)exportAttachmentsToiPhoto:(id)arg1;
- (void)saveAllAttachmentsWithoutPrompting:(id)arg1;
- (void)saveAllAttachments:(id)arg1;
- (void)saveAttachment:(id)arg1;
- (void)quickLookAllAttachments:(id)arg1;
- (void)forwardAction:(id)arg1;
- (void)replyAllAction:(id)arg1;
- (void)replyAction:(id)arg1;
- (void)deleteAction:(id)arg1;
- (void)_interpretAction:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)_updateHeaderMouseOver;
- (void)_updateHeaderTrackingArea;
- (void)_updateLoadRemoteContent;
- (void)_updateHeaderFont;
- (void)_updateActionButtons;
- (void)_updateWebDocumentView;
- (void)_viewerPreferencesChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) BOOL showingAllHeaders;
@property(nonatomic) double pageZoom;
@property(readonly, nonatomic) MessageViewer *messageViewer;
@property(readonly, nonatomic) BOOL loaded;
@property(nonatomic) BOOL displayAsSingleton;
- (void)_showLoadingProgress;
- (void)setRepresentedObject:(id)arg1;
- (id)representedObject;
- (void)setView:(id)arg1;
- (id)view;
- (void)dealloc;
- (void)_setupActionButtons;
- (void)_setupBodyScrollView;
- (void)_setupHeaderView;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

