/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSAnimation.h"

@class FullScreenModalCapableWindow, ModalDimmingWindow;

@interface WindowTransformAnimation : NSAnimation
{
    FullScreenModalCapableWindow *_window;
    ModalDimmingWindow *_dimmingWindow;
    long long _dimmingFade;
    struct CGPoint _anchorPoint;
    double _maxScreenPosition;
    BOOL _cancelled;
    long long _animationType;
}

+ (id)windowTransformAnimationWithWindow:(id)arg1 dimmingWindow:(id)arg2 type:(long long)arg3;
@property BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(readonly) long long animationType; // @synthesize animationType=_animationType;
- (void)dealloc;
- (void)setCurrentProgress:(float)arg1;
- (void)cancelAnimation;
- (void)startAnimation;
- (void)setWindowMagnificationForProgress:(double)arg1 anchorPoint:(struct CGPoint)arg2;
- (void)setWindowFlyInTranslationProgress:(double)arg1;
- (unsigned long long)_animationCurveForAnimationType:(long long)arg1;
- (double)_animationDurationForAnimationType:(long long)arg1;
- (id)initWithWindow:(id)arg1 dimmingWindow:(id)arg2 type:(long long)arg3;
- (id)initWithDuration:(double)arg1 animationCurve:(unsigned long long)arg2;

@end

