/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MTMSpecialMailbox.h"

@interface _MTMSubMetaMailbox : MTMSpecialMailbox
{
}

- (id)messageListFont;
- (id)messageListColor;
- (id)_severalMessagesString;
- (id)_oneMesageString;
- (id)displayNameInMessageList;
- (id)displayNameForList;
- (id)defaultMessageColumnAttributesKey;
- (id)messageColumnConfiguration;
- (id)restoreString;
- (id)restoreMode;
- (id)identifier;
- (id)recoverDisplayName;
- (id)displayName;

@end

