/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSActionCell.h"

@class MFMailAccount, NSImage, NSString;

@interface AccountCell : NSActionCell
{
    NSString *_subtitle;
    MFMailAccount *_account;
    NSImage *_icon;
}

- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property(retain, nonatomic) NSImage *icon; // @synthesize icon=_icon;
- (id)title;
- (id)subtitle;
- (void)setSubtitle:(id)arg1;
- (void)setAccount:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initTextCell:(id)arg1;

@end

