/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@class MCActivityAggregate, NSButton, NSProgressIndicator, NSTextField;

@interface ActivityAggregateView : NSView
{
    NSTextField *_nameTextField;
    NSTextField *_statusTextField;
    NSButton *_stopButton;
    NSProgressIndicator *_progressIndicator;
    double _nameTextFieldSpace;
    double _statusTextFieldSpace;
    double _progressIndicatorSpace;
    MCActivityAggregate *_activityAggregate;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_updateNameTextField;
- (void)awakeFromNib;
- (void)setActivityAggregate:(id)arg1;
- (id)activityAggregate;
- (void)dealloc;
- (void)_activityAggregateViewCommonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

