/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class NSButton, NSImage, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSSearchField, NSString, NSTableView, NSWindow;

@interface AddressHistoryController : NSObject <NSTableViewDataSource, NSTableViewDelegate>
{
    NSMutableArray *_historyRecords;
    NSString *_sortColumn;
    BOOL _sortIsAscending;
    NSImage *_addressBookPersonImage;
    NSTableView *_historyTableView;
    NSButton *_addToContactsButton;
    NSWindow *_window;
    NSSearchField *_searchField;
    NSMutableDictionary *_abRecordMap;
    NSOperationQueue *_fetchQueue;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(readonly) NSOperationQueue *fetchQueue; // @synthesize fetchQueue=_fetchQueue;
@property(retain, nonatomic) NSMutableDictionary *abRecordMap; // @synthesize abRecordMap=_abRecordMap;
@property(nonatomic) NSSearchField *searchField; // @synthesize searchField=_searchField;
@property(retain, nonatomic) NSWindow *window; // @synthesize window=_window;
@property(nonatomic) NSButton *addToContactsButton; // @synthesize addToContactsButton=_addToContactsButton;
@property(nonatomic) NSTableView *historyTableView; // @synthesize historyTableView=_historyTableView;
- (id)_recordForAddress:(id)arg1;
- (void)_addressBookDidChange:(id)arg1;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)_showColumnSortIndicator;
- (void)_sortHistoryData;
- (void)tableView:(id)arg1 didClickTableColumn:(id)arg2;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)openContacts:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)_cancelSearch:(id)arg1;
- (void)search:(id)arg1;
- (void)searchIndex:(id)arg1;
- (void)deleteFromHistory:(id)arg1;
- (void)addToContacts:(id)arg1;
- (void)showAddressHistory;
- (void)_fetchRecentsDataWithCompletionBlock:(id)arg1;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (void)dealloc;
- (id)init;

@end

