/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "ComposeViewControllerDelegate.h"
#import "NSWindowDelegate.h"

@class ComposeViewController;

@interface ComposeWindowController : NSWindowController <ComposeViewControllerDelegate, NSWindowDelegate>
{
    BOOL _userWantsToCloseWindow;
    ComposeViewController *_composeViewController;
}

+ (void)initialize;
@property(nonatomic) BOOL userWantsToCloseWindow; // @synthesize userWantsToCloseWindow=_userWantsToCloseWindow;
@property(retain, nonatomic) ComposeViewController *composeViewController; // @synthesize composeViewController=_composeViewController;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)composeViewDidSaveSuccessfully:(BOOL)arg1;
- (BOOL)composeViewShouldAllowUserToIgnoreSaveFailure;
- (void)composeViewDidSend;
- (void)composeViewFinishedEditing;
- (void)setRepresentedObject:(id)arg1;
- (id)representedObject;
- (void)awakeFromNib;
- (id)windowNibName;
- (void)dealloc;
- (id)init;

@end

