/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@class ComposeViewController, MUIAddressField, MUIWebDocumentView, NSButton, NSLayoutConstraint, NSPopUpButton, NSTextField;

@interface ComposeView : NSView
{
    BOOL _allowShowingOfCcBccFromField;
    NSView *_headerView;
    MUIWebDocumentView *_webDocumentView;
    ComposeViewController *_controller;
    MUIAddressField *_toField;
    NSView *_ccBccFromView;
    NSTextField *_ccBccFromField;
    NSLayoutConstraint *_ccBccFromHeightConstraint;
    NSLayoutConstraint *_ccBccFromCurrentHeightConstraint;
    NSView *_ccView;
    MUIAddressField *_ccField;
    NSLayoutConstraint *_ccHeightConstraint;
    NSLayoutConstraint *_ccCurrentHeightConstraint;
    NSView *_bccView;
    MUIAddressField *_bccField;
    NSLayoutConstraint *_bccHeightConstraint;
    NSLayoutConstraint *_bccCurrentHeightConstraint;
    NSView *_replyToView;
    MUIAddressField *_replyToField;
    NSLayoutConstraint *_replyToHeightConstraint;
    NSLayoutConstraint *_replyToCurrentHeightConstraint;
    NSView *_subjectView;
    NSTextField *_subjectField;
    NSLayoutConstraint *_subjectTrailingConstraint;
    NSView *_fromView;
    NSPopUpButton *_fromPopupButton;
    NSPopUpButton *_deliveryPopupButton;
    NSLayoutConstraint *_fromHeightConstraint;
    NSLayoutConstraint *_fromCurrentHeightConstraint;
    NSView *_signatureView;
    NSLayoutConstraint *_signatureHeightConstraint;
    NSLayoutConstraint *_signatureCurrentHeightConstraint;
    NSLayoutConstraint *_signatureTrailingConstraint;
    NSPopUpButton *_priorityPopupButton;
    NSLayoutConstraint *_priorityWidthConstraint;
    NSLayoutConstraint *_priorityCurrentWidthConstraint;
    NSView *_securityView;
    NSButton *_encryptButton;
    NSButton *_signButton;
    NSLayoutConstraint *_securityWidthConstraint;
    NSLayoutConstraint *_securityCurrentWidthConstraint;
    NSPopUpButton *_fieldSelectorPopupButton;
    NSLayoutConstraint *_bottomMostElementTrailingToFieldsSelectorConstraint;
    NSButton *_sendButton;
}

@property(nonatomic) NSButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) NSLayoutConstraint *bottomMostElementTrailingToFieldsSelectorConstraint; // @synthesize bottomMostElementTrailingToFieldsSelectorConstraint=_bottomMostElementTrailingToFieldsSelectorConstraint;
@property(nonatomic) NSPopUpButton *fieldSelectorPopupButton; // @synthesize fieldSelectorPopupButton=_fieldSelectorPopupButton;
@property(retain, nonatomic) NSLayoutConstraint *securityCurrentWidthConstraint; // @synthesize securityCurrentWidthConstraint=_securityCurrentWidthConstraint;
@property(retain, nonatomic) NSLayoutConstraint *securityWidthConstraint; // @synthesize securityWidthConstraint=_securityWidthConstraint;
@property(nonatomic) NSButton *signButton; // @synthesize signButton=_signButton;
@property(nonatomic) NSButton *encryptButton; // @synthesize encryptButton=_encryptButton;
@property(nonatomic) NSView *securityView; // @synthesize securityView=_securityView;
@property(retain, nonatomic) NSLayoutConstraint *priorityCurrentWidthConstraint; // @synthesize priorityCurrentWidthConstraint=_priorityCurrentWidthConstraint;
@property(retain, nonatomic) NSLayoutConstraint *priorityWidthConstraint; // @synthesize priorityWidthConstraint=_priorityWidthConstraint;
@property(nonatomic) NSPopUpButton *priorityPopupButton; // @synthesize priorityPopupButton=_priorityPopupButton;
@property(retain, nonatomic) NSLayoutConstraint *signatureTrailingConstraint; // @synthesize signatureTrailingConstraint=_signatureTrailingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *signatureCurrentHeightConstraint; // @synthesize signatureCurrentHeightConstraint=_signatureCurrentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *signatureHeightConstraint; // @synthesize signatureHeightConstraint=_signatureHeightConstraint;
@property(nonatomic) NSView *signatureView; // @synthesize signatureView=_signatureView;
@property(retain, nonatomic) NSLayoutConstraint *fromCurrentHeightConstraint; // @synthesize fromCurrentHeightConstraint=_fromCurrentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *fromHeightConstraint; // @synthesize fromHeightConstraint=_fromHeightConstraint;
@property(nonatomic) NSPopUpButton *deliveryPopupButton; // @synthesize deliveryPopupButton=_deliveryPopupButton;
@property(nonatomic) NSPopUpButton *fromPopupButton; // @synthesize fromPopupButton=_fromPopupButton;
@property(nonatomic) NSView *fromView; // @synthesize fromView=_fromView;
@property(retain, nonatomic) NSLayoutConstraint *subjectTrailingConstraint; // @synthesize subjectTrailingConstraint=_subjectTrailingConstraint;
@property(nonatomic) NSTextField *subjectField; // @synthesize subjectField=_subjectField;
@property(nonatomic) NSView *subjectView; // @synthesize subjectView=_subjectView;
@property(retain, nonatomic) NSLayoutConstraint *replyToCurrentHeightConstraint; // @synthesize replyToCurrentHeightConstraint=_replyToCurrentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *replyToHeightConstraint; // @synthesize replyToHeightConstraint=_replyToHeightConstraint;
@property(nonatomic) MUIAddressField *replyToField; // @synthesize replyToField=_replyToField;
@property(nonatomic) NSView *replyToView; // @synthesize replyToView=_replyToView;
@property(retain, nonatomic) NSLayoutConstraint *bccCurrentHeightConstraint; // @synthesize bccCurrentHeightConstraint=_bccCurrentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *bccHeightConstraint; // @synthesize bccHeightConstraint=_bccHeightConstraint;
@property(nonatomic) MUIAddressField *bccField; // @synthesize bccField=_bccField;
@property(nonatomic) NSView *bccView; // @synthesize bccView=_bccView;
@property(retain, nonatomic) NSLayoutConstraint *ccCurrentHeightConstraint; // @synthesize ccCurrentHeightConstraint=_ccCurrentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *ccHeightConstraint; // @synthesize ccHeightConstraint=_ccHeightConstraint;
@property(nonatomic) MUIAddressField *ccField; // @synthesize ccField=_ccField;
@property(nonatomic) NSView *ccView; // @synthesize ccView=_ccView;
@property(retain, nonatomic) NSLayoutConstraint *ccBccFromCurrentHeightConstraint; // @synthesize ccBccFromCurrentHeightConstraint=_ccBccFromCurrentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *ccBccFromHeightConstraint; // @synthesize ccBccFromHeightConstraint=_ccBccFromHeightConstraint;
@property(nonatomic) NSTextField *ccBccFromField; // @synthesize ccBccFromField=_ccBccFromField;
@property(nonatomic) NSView *ccBccFromView; // @synthesize ccBccFromView=_ccBccFromView;
@property(nonatomic) MUIAddressField *toField; // @synthesize toField=_toField;
@property(nonatomic) ComposeViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) MUIWebDocumentView *webDocumentView; // @synthesize webDocumentView=_webDocumentView;
@property(nonatomic) NSView *headerView; // @synthesize headerView=_headerView;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;
- (void)controlTextDidBeginEditing:(id)arg1;
- (void)_setupKeyViewLoop;
- (void)animateCcBccFromChange;
- (void)toggleSecurity:(id)arg1;
- (void)togglePriority:(id)arg1;
- (void)toggleSignature:(id)arg1;
- (void)toggleReplyTo:(id)arg1;
- (void)_synchronizeCcBccFromUI;
- (BOOL)_isShowingFromField;
- (BOOL)_isShowingBccField;
- (BOOL)_isShowingCcField;
- (BOOL)_isShowingCcBccFromField;
- (id)_fieldInFocus;
- (BOOL)_showCcBccFromField;
@property(nonatomic) BOOL allowShowingOfCcBccFromField;
- (void)_synchronizeSecurityUI;
- (BOOL)_isShowingSecurityControls;
@property(nonatomic) BOOL showSecurityControls;
- (void)_synchronizePriorityUI;
- (BOOL)_isShowingPriorityControl;
@property(nonatomic) BOOL showPriorityControl;
- (void)_synchronizeSignatureUI;
- (BOOL)_isShowingSignatureField;
@property(nonatomic) BOOL showSignatureField;
- (void)_synchronizeReplyToUI;
- (BOOL)_isShowingReplyToField;
@property(nonatomic) BOOL showReplyToField;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (void)awakeFromNib;
- (void)dealloc;

@end

