/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "TilingWebView.h"

#import "NSInspectorBarClient.h"
#import "NSTextInputClient.h"

@class DOMHTMLElement, DOMNode;

@interface EditingMessageWebView : TilingWebView <NSInspectorBarClient, NSTextInputClient>
{
    DOMHTMLElement *_contentElement;
    DOMNode *_cursorPositionNode;
    struct {
        unsigned int delegateRespondsToCanInsertFromDraggingInfo:1;
        unsigned int delegateRespondsToCanInsertFromPasteboard:1;
    } _flags;
}

+ (id)insertablePasteboardTypes;
- (unsigned long long)characterIndexForPoint:(struct CGPoint)arg1;
- (struct CGRect)firstRectForCharacterRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (id)validAttributesForMarkedText;
- (id)attributedSubstringForProposedRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (BOOL)hasMarkedText;
- (struct _NSRange)markedRange;
- (struct _NSRange)selectedRange;
- (void)unmarkText;
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2 replacementRange:(struct _NSRange)arg3;
- (void)doCommandBySelector:(SEL)arg1;
- (void)insertText:(id)arg1 replacementRange:(struct _NSRange)arg2;
- (id)textInput;
- (id)inspectorBarItemIdentifiers;
- (BOOL)validateUserInterfaceItem:(id)arg1 fallThrough:(char *)arg2;
- (BOOL)validateMenuItem:(id)arg1 fallThrough:(char *)arg2;
- (BOOL)selectionIsInEmptyListItem;
- (BOOL)selectionIsInList;
- (BOOL)selectionIsInListTypes:(id)arg1;
- (BOOL)selectionIsInListType:(id)arg1;
- (void)increaseListNestingLevel:(id)arg1;
- (void)insertListWithNumbers:(BOOL)arg1 undoTitle:(id)arg2;
- (void)decreaseListNestingLevel:(id)arg1;
- (void)convertToBulletedList:(id)arg1;
- (void)convertToNumberedList:(id)arg1;
- (void)convertListFromType:(id)arg1 toType:(id)arg2 undoTitle:(id)arg3;
- (void)layoutResizingAttachmentViews;
- (void)viewDidEndLiveResize;
- (void)changeDocumentBackgroundColorToColor:(id)arg1;
- (void)viewWillStartLiveResize;
- (void)makeFontSmaller:(id)arg1;
- (void)makeFontBigger:(id)arg1;
- (void)removeFragmentBlockQuote:(id)arg1;
- (void)removeBlockQuoteFromTree:(id)arg1;
- (long long)compareRange:(id)arg1 toEndOfNode:(id)arg2;
- (void)splitUpBlockQuotesOverlappingEndOfRange:(id)arg1;
- (void)splitUpBlockQuotesOverlappingStartOfRange:(id)arg1;
- (void)changeQuoteLevel:(id)arg1;
- (BOOL)removeAllQuotingFromTree:(id)arg1;
- (void)changeIndentation:(long long)arg1;
- (void)changeIndentationIfAllowed:(long long)arg1;
- (void)decreaseIndentation:(id)arg1;
- (void)increaseIndentation:(id)arg1;
- (void)addHorizontalRule:(id)arg1;
- (void)removeLink:(id)arg1;
- (void)editLink:(id)arg1;
- (BOOL)becomeFirstResponder;
- (void)setCursorPositionNode:(id)arg1;
- (void)pasteWithCurrentStyle:(id)arg1;
- (void)pasteAsQuotation:(id)arg1;
- (void)paste:(id)arg1;
- (void)redo:(id)arg1;
- (void)undo:(id)arg1;
- (void)dragImage:(id)arg1 at:(struct CGPoint)arg2 offset:(struct CGSize)arg3 event:(id)arg4 pasteboard:(id)arg5 source:(id)arg6 slideBack:(BOOL)arg7;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)concludeDragOperation:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)saveMessageToDrafts:(id)arg1;
- (void)registerForDraggedTypes:(id)arg1;
- (id)insertablePasteboardTypes;
- (void)insertNode:(id)arg1 atRange:(id)arg2;
- (void)saveSelectionForUndo;
- (void)setSelectionStart:(id)arg1 offset:(int)arg2 end:(id)arg3 offset:(int)arg4 affinity:(unsigned long long)arg5;
- (id)selectedContainerWithNameInArray:(id)arg1;
- (BOOL)isFirstLineOfDocument;
- (id)selectedAnchor;
- (id)temporaryStartingSelectionMarker;
- (id)temporaryEndingSelectionMarker;
- (void)deleteTemporarySelectionMarkersFromDocument:(id)arg1;
- (void)restoreSelectionFromTemporaryMarkers:(BOOL)arg1;
- (void)restoreSelectionFromTemporaryMarkers;
- (void)insertTemporarySelectionMarkersForRange:(id)arg1;
- (BOOL)isAutomaticLinkDetectionEnabled;
- (void)removeAllFormatting;
- (BOOL)resetMainDocumentBodyAttributes;
- (BOOL)removeNonBodyChildrenAndAttributesFromMainDocumentElement;
- (BOOL)removeFormattingFromTree:(id)arg1 forDocument:(id)arg2 hasDocumentContext:(BOOL)arg3 imageStrippingMode:(int)arg4;
- (BOOL)removeHeadFromDocument:(id)arg1;
- (void)setMainDocumentURI:(id)arg1;
- (void)setStyleProperty:(id)arg1 value:(id)arg2 priority:(id)arg3 ofElement:(id)arg4;
- (void)setValue:(id)arg1 forAttribute:(id)arg2 ofElement:(id)arg3;
- (void)insertNode:(id)arg1 parent:(id)arg2 offset:(int)arg3;
- (void)insertNode:(id)arg1 parent:(id)arg2 nextSibling:(id)arg3;
- (void)replaceNode:(id)arg1 oldNode:(id)arg2;
- (void)deleteRange:(id)arg1;
- (void)deleteNode:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)selectionCouldBeMadeIntoALink;
- (BOOL)isSelectionInContentElement;
- (void)dealloc;
- (void)setContentElement:(id)arg1;
- (id)contentElement;
- (BOOL)isContentEditable;
- (BOOL)replaceSelectionWithFragment:(id)arg1 attachments:(id)arg2 pasteboard:(id)arg3 types:(id)arg4 action:(int)arg5 options:(int)arg6 isPlainText:(BOOL)arg7;
- (BOOL)replaceSelectionUsingContext:(id)arg1;
- (BOOL)_replaceSelectionWithPasteboardContentsDraggingInfo:(id)arg1 pasteboard:(id)arg2 pasteboardType:(id)arg3 action:(int)arg4 options:(int)arg5;
- (BOOL)_replaceSelectionWithContentsOfWebpage:(id)arg1;
- (BOOL)replaceSelectionWithPasteboardContentsDraggingInfo:(id)arg1 pasteboardType:(id)arg2 action:(int)arg3 options:(int)arg4;
- (BOOL)replaceSelectionWithPasteboardContentsPasteboard:(id)arg1 pasteboardType:(id)arg2 action:(int)arg3 options:(int)arg4;
- (unsigned long long)pastedGraphicCounter;
- (void)setEditingDelegate:(id)arg1;
- (id)editingDelegate;
- (id)mailPreferredPboardTypeFromTypes:(id)arg1 pasteboard:(id)arg2 isForDrag:(BOOL)arg3 preferHTML:(BOOL)arg4;
- (BOOL)isActive;
- (BOOL)maintainsInactiveSelection;

@end

