/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "Importer.h"

@class NSArray, NSData, NSString;

@interface EmailImporter : Importer
{
    NSString *_attachmentBeingSearchedFor;
    NSString *_rootFolderPath;
    NSArray *_sourceFolderPaths;
    NSArray *_sourcePaths;
    NSString *_destinationFolderName;
    NSString *_lastDirectoryFound;
    NSString *_temporaryImportFolderPath;
    char *_lineDelimiter;
    char *_fromSpaceSeparator;
    NSData *_newline;
    NSData *_greaterThanSign;
    NSData *_fromSpace;
    BOOL _errorsDuringImport;
}

- (void)dealloc;
- (id)mailboxForImportItem:(id)arg1;
- (id)mailboxNameForImportItem:(id)arg1;
- (id)_fromSpace;
- (id)_greaterThanSign;
- (id)_newline;
- (id)copyAttachmentsToMailFolder:(id)arg1;
- (BOOL)isAttachmentBeingSearchedFor:(id)arg1;
- (id)locateAttachments:(id)arg1 inFolder:(id)arg2;
- (id)createAttachmentText:(id)arg1 isHTML:(BOOL)arg2;
- (id)regenerateMessageData:(id)arg1 isHTML:(BOOL)arg2 isRich:(BOOL)arg3;
- (id)longestCommonPathForItems:(id)arg1;
- (id)uniqueDirectoriesForItems:(id)arg1;
- (id)searchForValidItemInsideDirectory:(id)arg1 validitySelector:(SEL)arg2 searchDepth:(long long)arg3;
- (id)searchForValidItemsInsideDirectory:(id)arg1 validitySelector:(SEL)arg2 limit:(unsigned long long)arg3 searchDepth:(long long)arg4;
- (id)validItemsFromPaths:(id)arg1 validitySelector:(SEL)arg2;
- (void)convertChar:(BOOL)arg1 toChar:(BOOL)arg2 inBytes:(char *)arg3 length:(long long)arg4;
- (void)updateSubjectStringForMessageHeaders:(id)arg1;
- (void)addMessagesToLibrary:(id)arg1 withMailbox:(id)arg2;
- (id)messageWithImporterData:(id)arg1;
- (BOOL)errorsDuringImport;
- (void)setErrorsDuringImport:(BOOL)arg1;
- (BOOL)isValidMailbox:(id)arg1;
- (void)setSourceList:(id)arg1;
- (id)sourceList;
- (void)setSourceFolders:(id)arg1;
- (id)sourceFolders;
- (void)setRootFolder:(id)arg1;
- (id)rootFolder;
- (void)setFromSpaceSeparator:(char *)arg1;
- (char *)fromSpaceSeparator;
- (void)setLineDelimiter:(char *)arg1;
- (id)destinationFolderName;
- (id)regexForAttachmentName:(id)arg1;
- (char *)lineDelimiter;
- (id)preProcessSourceData:(id)arg1;
- (void)importMailbox:(id)arg1;
- (void)processUserSelection;
- (void)readMailbox:(id)arg1 intoMailbox:(id)arg2;
- (void)cleanup;
- (id)statusLine;
- (id)importFinishedText;
- (void)importFinished;
- (void)revealMailbox:(id)arg1;
- (void)performImport;
- (id)init;

@end

