/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSScriptCommand.h"

@interface ExtractNameCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;
- (id)executeCommand;
- (id)_getAddressDisplayNameForObject:(id)arg1;

@end

