/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSButtonCell.h"

@interface GlassButtonCell : NSButtonCell
{
}

- (void)setBackgroundStyle:(long long)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)setEnabled:(BOOL)arg1;
- (id)attributedTitle;
- (id)_titleAttributes;

@end

