/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ImportItem : NSObject
{
    NSString *_fullPath;
    NSString *_relativePath;
    long long _itemCount;
    id _identifier;
    long long _subfolderCount;
    id _importFields;
    BOOL _isEnabled;
    NSString *_displayName;
    double _progressValue;
    double _progressStart;
}

- (void)setImportFields:(id)arg1;
- (id)importFields;
- (void)setSubfolderCount:(long long)arg1;
- (long long)subfolderCount;
- (void)setIdentifier:(id)arg1;
- (id)identifier;
- (void)setItemCount:(long long)arg1;
- (long long)itemCount;
- (void)setRelativePath:(id)arg1;
- (id)relativePath;
- (void)setFullPath:(id)arg1;
- (id)fullPath;
- (void)setProgressStart:(double)arg1;
- (double)progressStart;
- (void)setProgressValue:(double)arg1;
- (double)progressValue;
- (void)setDisplayName:(id)arg1;
- (id)displayName;
- (void)setIsEnabled:(BOOL)arg1;
- (BOOL)isEnabled;
- (void)dealloc;

@end

