/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DynamicErrorWindowDelegate.h"

@interface IOErrorWindowDelegate : NSObject <DynamicErrorWindowDelegate>
{
}

- (void)rightActionSelectedWithDiagnosis:(long long)arg1;
- (void)leftActionSelectedWithDiagnosis:(long long)arg1;
- (unsigned long long)helpTopicForDiagnosis:(long long)arg1;
- (id)rightButtonTextForErrorDiagnosis:(long long)arg1;
- (id)leftButtonTextForErrorDiagnosis:(long long)arg1;
- (id)errorDescriptionForErrorDiagnosis:(long long)arg1;
- (id)errorMessageForErrorDiagnosis:(long long)arg1;
- (BOOL)displayIndeterminateProgress;

@end

