/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "BannerViewController.h"

@class BannerImageView, NSButton, NSLayoutConstraint;

@interface LoadImagesBannerViewController : BannerViewController
{
    NSButton *_loadImagesButton;
    NSLayoutConstraint *_messageFieldToLoadImagesButtonHorizontalSpacing;
    BannerImageView *_icon;
}

@property(nonatomic) BannerImageView *icon; // @synthesize icon=_icon;
@property(nonatomic) NSLayoutConstraint *messageFieldToLoadImagesButtonHorizontalSpacing; // @synthesize messageFieldToLoadImagesButtonHorizontalSpacing=_messageFieldToLoadImagesButtonHorizontalSpacing;
@property(nonatomic) NSButton *loadImagesButton; // @synthesize loadImagesButton=_loadImagesButton;
- (void)loadImages:(id)arg1;
- (void)updateWantsDisplay;
- (void)updateBannerContents;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setRepresentedObject:(id)arg1;
- (void)awakeFromNib;
@property(readonly, nonatomic) BOOL shouldDisplayToLoadImages;
@property(readonly, nonatomic) CDStruct_3c058996 iconAlignmentRectInsets;
- (id)backgroundColor;
- (void)dealloc;
- (id)nibName;

@end

