/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSSplitView.h"

@class NSString;

@interface MailSplitView : NSSplitView
{
    long long _dividerToolTipTag;
    NSString *_toolTipString;
    BOOL _isDividerHidden;
    NSString *_oldAutosaveName;
}

@property(nonatomic) BOOL isDividerHidden; // @synthesize isDividerHidden=_isDividerHidden;
@property(copy, nonatomic) NSString *oldAutosaveName; // @synthesize oldAutosaveName=_oldAutosaveName;
- (double)dividerThickness;
- (struct CGRect)_dividerRect;
- (void)setDividerToolTip:(id)arg1;
- (BOOL)isFirstViewVisible;
- (BOOL)isSecondViewVisible;
- (BOOL)_isSubviewAtIndexVisible:(unsigned long long)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (void)setAutosaveName:(id)arg1;
- (void)windowLayoutDidExitFullScreen:(id)arg1;
- (void)windowLayoutWillExitFullScreen:(id)arg1;
- (void)windowLayoutDidEnterFullScreen:(id)arg1;
- (void)windowLayoutWillEnterFullScreen:(id)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)dealloc;

@end

