/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageMall.h"

@class MessageMiniMall, NSString;

@interface MessageMegaMall : NSObject <MessageMall>
{
    MessageMiniMall *_mailboxesMiniMall;
    MessageMiniMall *_searchMiniMall;
    MessageMiniMall *_currentMiniMall;
    MessageMiniMall *_alternateMiniMall;
    long long _activeSearchField;
    int _activeSearchTarget;
    NSString *_lastQueryStringFragment;
}

+ (id)expandedMailboxes:(id)arg1;
+ (id)notificationQueue;
+ (id)notificationCenter;
- (id)uniquedString:(id)arg1;
- (void)flushAllCaches;
- (void)invalidateMessage:(id)arg1;
- (void)sendResponseType:(BOOL)arg1 forMeetingMessage:(id)arg2;
- (id)undeleteMessages:(id)arg1 movedToStore:(id)arg2 newMessageIDs:(id)arg3;
- (void)undeleteMessages:(id)arg1;
- (void)deleteMessages:(id)arg1 moveToTrash:(BOOL)arg2;
- (void)saveSnippetsForMessages:(id)arg1;
- (id)snippetsForMessages:(id)arg1;
- (BOOL)supportsSnippets;
- (void)setNumberOfAttachments:(unsigned int)arg1 isSigned:(BOOL)arg2 isEncrypted:(BOOL)arg3 forMessage:(id)arg4;
- (id)attachmentsDirectoryForMessage:(id)arg1;
- (void)setColor:(id)arg1 highlightTextOnly:(BOOL)arg2 forMessages:(id)arg3;
- (id)async_setJunkMailLevel:(long long)arg1 forMessages:(id)arg2 trainJunkMailDatabase:(BOOL)arg3 userRecorded:(BOOL)arg4;
- (id)async_setJunkMailLevel:(long long)arg1 forMessages:(id)arg2 trainJunkMailDatabase:(BOOL)arg3;
- (id)async_setJunkMailLevel:(long long)arg1 forMessages:(id)arg2;
- (void)messageFlagsDidChange:(id)arg1 flags:(id)arg2;
- (id)async_setFlagWithKey:(id)arg1 state:(BOOL)arg2 forMessages:(id)arg3;
- (id)async_setFlagsFromDictionary:(id)arg1 forMessages:(id)arg2;
- (id)dataForMimePart:(id)arg1;
- (BOOL)hasCachedDataForMimePart:(id)arg1;
- (id)fullBodyDataForMessage:(id)arg1 andHeaderDataIfReadilyAvailable:(id *)arg2 fetchIfNotAvailable:(BOOL)arg3;
- (id)fullBodyDataForMessage:(id)arg1 andHeaderDataIfReadilyAvailable:(id *)arg2;
- (id)fullBodyDataForMessage:(id)arg1;
- (id)bodyDataForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2 allowPartial:(BOOL)arg3;
- (id)bodyForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2 updateFlags:(BOOL)arg3 allowPartial:(BOOL)arg4;
- (id)bodyForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2 updateFlags:(BOOL)arg3;
- (id)bodyForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2;
- (id)headerDataForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2 allowPartial:(BOOL)arg3;
- (id)headerDataForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2;
- (id)headerDataForMessage:(id)arg1;
- (id)headersForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2;
- (id)headersForMessage:(id)arg1;
- (id)mailbox;
- (id)account;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)routeMessages:(id)arg1 fromMailboxes:(id)arg2;
- (void)routeMessages:(id)arg1;
- (void)reload:(id)arg1;
- (void)setDisplayingToColumn:(BOOL)arg1;
- (BOOL)displayingToColumn;
- (void)doCompact;
- (BOOL)canCompact;
- (void)rebuildTableOfContentsAsynchronously;
- (BOOL)canRebuild;
- (BOOL)isOpened;
@property(readonly) BOOL isReadOnly;
- (id)messageForMessageID:(id)arg1;
- (unsigned long long)totalCount;
- (unsigned long long)unreadCount;
- (id)smartMailboxMemberMessagesForMessages:(id)arg1;
- (id)allMessagesForConversationID:(long long)arg1;
- (id)primaryMessagesForConversationID:(long long)arg1;
- (BOOL)hasNonDuplicateRelatedMessages:(id)arg1;
- (id)allRelatedMessagesForMessage:(id)arg1;
- (id)originalOfMessage:(id)arg1;
- (id)messagesIncludingHiddenCopies:(id)arg1;
- (void)hideAllCopiesOfMessages:(id)arg1;
- (id)messageIDsToShowAllCopiesOf;
- (void)showAllCopiesOfMessage:(id)arg1;
- (unsigned int)loadOptions;
- (BOOL)messageIsPartOfAThread:(id)arg1;
- (id)threadForMessageID:(id)arg1;
- (id)unfilteredThreadForMessage:(id)arg1;
- (id)filteredThreadForMessage:(id)arg1;
- (id)parentOfMessage:(id)arg1;
- (id)repliesToMessage:(id)arg1;
- (void)addMessagesInSameThreadAsMessage:(id)arg1 toSet:(id)arg2;
- (void)closeAllThreads;
- (void)openAllThreads;
- (BOOL)openThreadsWithIDs:(id)arg1;
- (id)quietlyCloseThreadAtIndex:(unsigned long long)arg1;
- (BOOL)closeThreadAtIndex:(long long)arg1 focusRow:(long long)arg2 animate:(BOOL)arg3;
- (id)quietlyOpenThreadAtIndex:(unsigned long long)arg1;
- (BOOL)openThreadAtIndex:(long long)arg1 andSelectMessage:(id)arg2 animate:(BOOL)arg3;
- (void)prepareToDisplayThread:(id)arg1;
- (void)toggleThreadedMode;
- (void)setIsInThreadedMode:(BOOL)arg1;
- (BOOL)isInThreadedModeExcludingSearch;
- (BOOL)isInThreadedMode;
- (void)sortMessages:(id)arg1;
- (BOOL)isSortedAscending;
- (id)sortOrder;
- (void)setSortOrder:(id)arg1 ascending:(BOOL)arg2;
- (void)setIncludeDeleted:(BOOL)arg1;
- (BOOL)includeDeleted;
- (id)stores;
- (id)expandedSelectedMailboxesAllowingSearch;
- (id)expandedSelectedMailboxes;
- (id)selectedMailboxes;
- (id)allMailboxes;
- (void)setMailboxes:(id)arg1;
- (BOOL)deletedFlagForMessage:(id)arg1;
- (id)unhideMessages:(id)arg1;
- (id)hideMessages:(id)arg1;
- (int)currentSearchTarget;
- (long long)currentSearchField;
- (BOOL)isStillSearching;
- (BOOL)isShowingSearchResults;
- (unsigned int)messageFlagsForMessage:(id)arg1 size:(unsigned long long *)arg2 appliedFlagColors:(id *)arg3;
- (unsigned long long)sizeForMessage:(id)arg1;
- (id)criterionForString:(id)arg1 type:(long long)arg2 scope:(int)arg3;
- (id)criterionForAttachmentType:(id)arg1;
- (void)searchForString:(id)arg1 in:(int)arg2 withOptions:(long long)arg3;
- (id)queryStringFragmentFromSuggestions:(id)arg1;
- (void)searchForSuggestions:(id)arg1 in:(int)arg2 withOptions:(long long)arg3 fromSuggestionsSearchField:(id)arg4;
- (void)clearPreviousQueryString;
- (void)_searchForCriterion:(id)arg1;
- (BOOL)supportsSearching;
- (void)setFocusedMessages:(id)arg1;
- (BOOL)isFocused;
- (BOOL)filteredListIncludesAllMessages;
- (void)clearFilteredMessagesAndUpdateImmediately:(BOOL)arg1;
- (void)clearFilteredMessages;
- (void)clearSearch;
- (id)filteredThreads;
- (unsigned long long)indexOfMessage:(id)arg1;
- (id)numberForMessage:(id)arg1;
- (id)filteredMessageAtIndex:(unsigned long long)arg1 isChildOfThread:(char *)arg2;
- (unsigned long long)indexOfFilteredDocument:(id)arg1;
- (unsigned long long)indexOfFilteredMessage:(id)arg1;
- (id)filteredMessagesInRange:(struct _NSRange)arg1;
- (id)filteredMessages;
- (id)filteredMessagesAtIndexes:(id)arg1;
- (id)filteredMessageAtIndex:(unsigned long long)arg1;
- (unsigned long long)filteredMessagesCount;
- (void)_handleMiniMallNotification:(id)arg1;
- (void)_updateUseLibraryIDNumbering;
- (void)setUsingSearchMiniMall:(BOOL)arg1;
- (BOOL)isUsingSearchMiniMall;
- (id)alternateMiniMall;
- (id)currentMiniMall;
- (void)unregisterForNotifications;
- (id)description;
- (void)dealloc;
- (id)init;

@end

