/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MCActivityTarget.h"

@class Conversation, MCInvocationQueue, MCMessage, MCMessageHeaders, MCMutableMessageHeaders, MFDeliveryAccount, MUIWebDocument, NSArray, NSDate, NSString, NSTimer, NSUUID;

@interface MessageDraft : NSObject <MCActivityTarget>
{
    MCMutableMessageHeaders *_headers;
    BOOL _hasChanges;
    BOOL _hasBeenSavedByUser;
    BOOL _isRedirected;
    BOOL _canEncryptMessage;
    BOOL _canSignMessage;
    unsigned long long _encoding;
    Conversation *_conversation;
    MCMessage *_originalMessage;
    MCInvocationQueue *_saveQueue;
    NSTimer *_saveTimer;
    id _completionBlock;
    MUIWebDocument *_webDocument;
}

+ (int)convertSaveOrSendResultFromResultCodeT:(long long)arg1;
+ (id)_saveTaskName;
@property(nonatomic) BOOL canSignMessage; // @synthesize canSignMessage=_canSignMessage;
@property(nonatomic) BOOL canEncryptMessage; // @synthesize canEncryptMessage=_canEncryptMessage;
@property(readonly) BOOL isRedirected; // @synthesize isRedirected=_isRedirected;
@property(readonly) MUIWebDocument *webDocument; // @synthesize webDocument=_webDocument;
@property(readonly) MCMessageHeaders *headers; // @synthesize headers=_headers;
@property(copy) id completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSTimer *saveTimer; // @synthesize saveTimer=_saveTimer;
@property(readonly) MCInvocationQueue *saveQueue; // @synthesize saveQueue=_saveQueue;
@property(readonly) MCMessage *originalMessage; // @synthesize originalMessage=_originalMessage;
@property(retain, nonatomic) Conversation *conversation; // @synthesize conversation=_conversation;
@property(nonatomic) unsigned long long encoding; // @synthesize encoding=_encoding;
@property(nonatomic) BOOL hasBeenSavedByUser; // @synthesize hasBeenSavedByUser=_hasBeenSavedByUser;
@property BOOL hasChanges; // @synthesize hasChanges=_hasChanges;
- (id)fromAccount;
- (void)_asyncGenerateMessageAsDraft:(BOOL)arg1 completionHandler:(id)arg2;
- (void)asyncGenerateMessage:(id)arg1;
- (void)_discardInBackgroundWithDocumentId:(id)arg1 account:(id)arg2;
- (void)discard;
- (void)_saveInBackgroundWithMessage:(id)arg1 account:(id)arg2;
- (void)_addBackgroundSaveInvocationToQueue;
- (void)saveWithCompletionBlock:(id)arg1;
- (void)_markDirtyAndSave;
@property(nonatomic) BOOL signMessage;
@property(nonatomic) BOOL encryptMessage;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)_updateCcOrBccMyselfFieldWithSender:(id)arg1 oldSender:(id)arg2;
@property(copy, nonatomic) NSUUID *documentId;
@property(copy, nonatomic) NSString *messageId;
@property(copy, nonatomic) NSString *subject;
@property(retain, nonatomic) MFDeliveryAccount *deliveryAccount;
@property(nonatomic) long long priority;
@property(copy, nonatomic) NSString *from;
@property(readonly) NSArray *allRecipients;
@property(retain, nonatomic) NSArray *replyTo;
@property(retain, nonatomic) NSArray *bcc;
@property(retain, nonatomic) NSArray *cc;
@property(retain, nonatomic) NSArray *to;
@property(retain, nonatomic) NSDate *date;
- (id)_webDocumentForMessage:(id)arg1;
- (id)_webDocumentForMessage:(id)arg1 webDocument:(id)arg2 type:(unsigned long long)arg3;
- (void)_addAddresses:(id)arg1 toAddresses:(id)arg2;
- (id)_addresses:(id)arg1 withoutAddresses:(id)arg2;
- (id)_bccRecipientsWithMessage:(id)arg1 type:(unsigned long long)arg2;
- (id)_ccRecipientsWithMessage:(id)arg1 type:(unsigned long long)arg2;
- (id)_toRecipientsWithMessage:(id)arg1 type:(unsigned long long)arg2;
- (id)_subjectWithMessage:(id)arg1 type:(unsigned long long)arg2;
- (id)_fromAccountWithMessage:(id)arg1;
- (void)dealloc;
- (id)_initWithType:(unsigned long long)arg1 message:(id)arg2 webDocument:(id)arg3;
- (id)initWithType:(unsigned long long)arg1 message:(id)arg2;
- (id)initWithType:(unsigned long long)arg1 messages:(id)arg2;
- (id)initWithType:(unsigned long long)arg1 conversationMember:(id)arg2;
- (id)init;

@end

