/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MCActivityTarget.h"

@class NSArray, NSButton, NSPopUpButton, NSSavePanel, NSSet, NSURL, NSView, NSWindow;

@interface MessageSaver : NSObject <MCActivityTarget>
{
    NSArray *_messages;
    NSSet *_stores;
    NSSavePanel *_savePanel;
    NSWindow *_window;
    NSURL *_saveDestination;
    unsigned int _haveAttachments:1;
    unsigned int _hideExtension:1;
    unsigned int _includeAttachments:1;
    unsigned int _saveFormat:4;
    unsigned int _headerDetailLevel:4;
    NSView *_accessoryView;
    NSPopUpButton *_formatPopup;
    NSButton *_includeAttachmentsSwitch;
}

+ (void)saveMessages:(id)arg1 headerDetailLevel:(long long)arg2 preferredFormat:(int)arg3 window:(id)arg4;
+ (void)initialize;
@property(nonatomic) NSButton *includeAttachmentsSwitch; // @synthesize includeAttachmentsSwitch=_includeAttachmentsSwitch;
@property(nonatomic) NSPopUpButton *formatPopup; // @synthesize formatPopup=_formatPopup;
@property(retain, nonatomic) NSView *accessoryView; // @synthesize accessoryView=_accessoryView;
- (id)_separator;
- (void)changeIncludeAttachments:(id)arg1;
- (void)changeFormat:(id)arg1;
- (void)_handleSaveError:(id)arg1;
- (void)_saveMessages;
- (void)_updateSavePanelUI;
- (void)_runSavePanel;
- (void)_runSavePanelForStationery;
- (void)_savePanelDidEndWithFileHandlingResult:(long long)arg1;
- (void)_setWindow:(id)arg1;
- (void)_setSaveFormat:(int)arg1;
- (void)_setHeaderDetailLevel:(long long)arg1;
- (void)_setMessages:(id)arg1;
- (void)saveMessagesWithoutPrompting:(id)arg1 toFilePath:(id)arg2 headerDetailLevel:(long long)arg3 format:(int)arg4;
- (void)dealloc;

@end

