/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSFormatter.h"

@interface MTMBytesFormatter : NSFormatter
{
}

- (id)stringForObjectValue:(id)arg1;
- (void)dealloc;
- (id)init;

@end

