/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MFUIMailbox.h"

@class NSArray, NSColor, NSDictionary, NSEnumerator, NSFont, NSMutableArray, NSMutableDictionary, NSString, NSURL;

@interface MTMMailbox : NSObject <MFUIMailbox>
{
    NSDictionary *_mailboxDict;
    NSMutableArray *_subMailboxes;
    NSMutableArray *_messages;
    BOOL _messagesLoaded;
    NSEnumerator *_messageEnumerator;
    BOOL _updatePaused;
    NSMutableArray *_pendingMessages;
    MTMMailbox *_parentMailbox;
    id <MTMMailboxControllerProtocol> _controller;
    NSMutableDictionary *_messageColumnAttributes;
}

+ (id)keyPathsForValuesAffectingType;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (Class)mailboxClassForMailboxDictionary:(id)arg1;
+ (void)setSectionOrder:(id)arg1;
- (unsigned long long)numberOfMessage:(id)arg1;
- (void)discardMailbox;
- (void)resumeMailboxUpdate;
- (void)pauseMailboxUpdate;
- (void)loadNextMessagesWithControllingMailbox:(id)arg1 andFetcher:(id)arg2;
- (void)_updateMessages:(id)arg1;
- (BOOL)needsToLoadMessagesInBackground;
- (id)description;
@property(readonly) NSFont *messageListFont;
@property(readonly) NSColor *messageListColor;
@property(readonly) NSString *subRestoreString;
@property(readonly) NSString *restoreString;
@property(readonly) NSString *defaultMessageColumnAttributesKey;
@property(readonly) NSDictionary *messageColumnAttributes;
- (BOOL)_addAttributesFromInfo:(id)arg1;
@property(readonly) NSString *messageColumnConfiguration;
@property(readonly) NSString *restoreMode;
@property(readonly) NSString *displayMode;
@property(readonly) BOOL canCollapse;
@property(readonly) BOOL showSender;
@property(readonly) NSString *senderTitleString;
@property(readonly) NSString *dateTitleString;
- (long long)compareIndexInOutline:(id)arg1;
- (long long)_compareName:(id)arg1;
- (void)sortSubMailboxes;
@property(readonly) SEL sortSelector;
- (unsigned long long)indexInOutline;
- (id)_messagesFolderPathFromMailboxFolderPath:(id)arg1;
- (void)reloadMessages;
- (id)messageWithIdentifier:(id)arg1;
@property(readonly) NSArray *messages;
- (void)_loadMessages;
- (BOOL)isDescendantOfMailboxWithType:(int)arg1;
- (void)_addSubMailbox:(id)arg1;
- (void)_addSubMailboxesFromDictionaries:(id)arg1;
- (id)_sortedMaiboxDictsForMailboxDicts:(id)arg1;
- (BOOL)_shouldSortMailboxes;
- (BOOL)hasChildren;
- (unsigned long long)numberOfChildren;
- (id)subMailboxWithIdentifier:(id)arg1;
- (id)children;
@property(readonly) NSArray *subMailboxes;
@property(readonly) MTMMailbox *parentMailbox;
- (BOOL)isPlaceholder;
- (BOOL)isSmartMailbox;
- (BOOL)isStore;
- (unsigned long long)displayCount;
- (BOOL)isContainer;
@property(readonly) NSString *displayNameInMessageList;
@property(readonly) NSString *displayNameInTitleBar;
- (id)_severalMessagesFormatString;
- (id)_oneMesageString;
- (id)extendedDisplayName;
@property(readonly) NSString *displayNameForList;
- (id)displayName;
@property(readonly) NSArray *paths;
@property(readonly) NSURL *timeMachineURL;
@property(readonly) NSString *path;
- (id)accountURLString;
- (id)account;
@property(readonly) BOOL enabled;
@property(readonly) BOOL asyncLoading;
@property int type;
@property(readonly) long long backupType;
@property(readonly) id revisionID;
- (id)persistentIdentifier;
@property(readonly) id identifier;
- (id)mailboxWithMailboxPath:(id)arg1;
- (id)mailboxPath;
- (id)mailboxWithIndexPath:(id)arg1;
- (id)indexPathFromMailbox:(id)arg1;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1 controller:(id)arg2;
@property(nonatomic) id <MTMMailboxControllerProtocol> controller;

@end

