/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSOutlineView;

@interface OutlineViewProgressIndicatorsController : NSObject
{
    NSOutlineView *_outlineView;
    NSMutableDictionary *_progressIndicators;
    NSMutableDictionary *_fractionsDone;
    NSMutableDictionary *_origins;
    NSMutableDictionary *_roundDeterminateColors;
    NSMutableSet *_scheduledUpdates;
    NSMutableSet *_scheduledRemovals;
    BOOL _updateScheduled;
}

- (void)_removeProgressIndicatorForKey:(id)arg1;
- (void)_updateProgressIndicatorForKey:(id)arg1;
- (void)_processUpdates;
- (void)_scheduleUpdate;
- (void)_setNeedsToRemoveProgressIndicatorForKey:(id)arg1;
- (void)_setNeedsToUpdateProgressIndicatorForKey:(id)arg1;
- (id)_progressIndicatorForKey:(id)arg1 createIfNeeded:(BOOL)arg2;
- (id)_itemForKey:(id)arg1;
- (id)_keyForItem:(id)arg1;
- (void)setRoundDeterminateColor:(id)arg1 forProgressIndicatorForItem:(id)arg2;
- (void)positionProgressIndicatorForItem:(id)arg1 inRect:(struct CGRect)arg2;
- (void)removeOrphanProgressIndicators;
- (void)removeProgressIndicatorForItem:(id)arg1;
- (void)showDeterminateProgressIndicatorForItem:(id)arg1 fractionDone:(double)arg2;
- (void)showIndeterminateProgressIndicatorForItem:(id)arg1;
- (void)dealloc;
- (id)initWithOutlineView:(id)arg1;
- (id)init;

@end

