/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSImageCell.h"

@class NSProgressIndicator;

@interface ProgressIndicatorCell : NSImageCell
{
    NSProgressIndicator *_progressIndicator;
}

- (void)dealloc;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setProgressIndicator:(id)arg1;

@end

