/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSOperationQueue;

@interface RedundantContentIdentificationManager : NSObject
{
    NSOperationQueue *_workQueue;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
- (id)_messageWithMessageIDHeaderString:(id)arg1 inConversation:(id)arg2;
- (id)mostRecentAncestorForRedundantTextComparisonForMessage:(id)arg1 inConversation:(id)arg2;
- (id)redundantContentMarkupForMessage:(id)arg1 inConversation:(id)arg2;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (void)dealloc;
- (id)init;

@end

