/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTableRowView.h"

@class NSTableView;

@interface RichTableRowView : NSTableRowView
{
    unsigned long long _rowStyle;
    BOOL _isThreadCollapsing;
    NSTableView *_tableView;
}

@property(nonatomic) BOOL isThreadCollapsing; // @synthesize isThreadCollapsing=_isThreadCollapsing;
@property(nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) unsigned long long rowStyle;
- (void)setEmphasized:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)_drawThreadSeparatorInRect:(struct CGRect)arg1;
- (void)_drawBasicSeparatorInRect:(struct CGRect)arg1;
- (void)drawSeparatorInRect:(struct CGRect)arg1;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
- (BOOL)_isChildOfThread;
- (BOOL)_isInternalThreadChild;
- (BOOL)_isExpandedThreadParent;
- (id)_rowBelow;
- (id)_rowAbove;
- (id)_threadChildBackgroundColor;
- (id)_threadParentBackgroundColor;
- (id)_separatorColor;
- (BOOL)shouldSetFontSmoothingBackgroundColor;
- (id)initWithFrame:(struct CGRect)arg1;

@end

