/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@class NSImage;

@interface SourceListBackgroundView : NSView
{
    NSImage *_fullBackground;
}

@property(retain, nonatomic) NSImage *fullBackground; // @synthesize fullBackground=_fullBackground;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (void)_updateFullBackgroundImage;
- (void)windowMainStateChanged:(id)arg1;
- (void)_superViewFrameChanged:(id)arg1;
- (void)dealloc;
- (void)_sourceListBackgroundViewCommonInit;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

