/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface StationeryDynamicElement : NSObject
{
    unsigned long long _type;
    NSString *_dateFormat;
}

+ (id)dynamicElementFromDOMElement:(id)arg1;
- (id)description;
- (id)fragmentToReplaceHTMLObjectBackEnd:(id)arg1;
- (void)setDateFormat:(id)arg1;
- (unsigned long long)type;
- (void)dealloc;
- (id)initWithType:(unsigned long long)arg1;

@end

