/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSMatrix.h"

@interface ThumbnailMatrix : NSMatrix
{
    BOOL _shouldShowButtons;
}

- (BOOL)_performDragFromMouseDown:(id)arg1;
- (struct CGRect)frameOfThumbnailAtIndex:(long long)arg1;
- (void)_addButtonAtIndex:(long long)arg1;
- (void)showDeleteButtons:(BOOL)arg1 beginningAtIndex:(long long)arg2;
- (void)highlightCell:(BOOL)arg1 atRow:(long long)arg2 column:(long long)arg3;
- (void)awakeFromNib;

@end

