/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTokenAttachmentDelegate.h"

@protocol MUIAddressTokenAttachmentDelegate <NSTokenAttachmentDelegate>
- (id)immediateActionAnimationControllerForAddressTokenAttachment:(id)arg1 inTextView:(id)arg2;
@end

