/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSTextField.h"

@class MessageHeaderDisplay;

@interface _DupsLinkView : NSTextField
{
    MessageHeaderDisplay *_linkHandler;
}

- (void)resetCursorRects;
@property MessageHeaderDisplay *linkHandler; // @synthesize linkHandler=_linkHandler;

@end

