/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@interface _MessageViewerLazyPopUpButtonCell : NSPopUpButtonCell
{
}

- (void)accessibilityPerformAction:(id)arg1;
- (void)_drawIndicatorWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

