/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "_MTMStoredMetaMailbox.h"

@interface _MTMDraftsMailbox : _MTMStoredMetaMailbox
{
}

- (id)displayName;
- (id)recoverDisplayName;
- (id)restoreMode;
- (id)messageColumnConfiguration;
- (id)defaultMessageColumnAttributesKey;
- (id)_oneMesageString;
- (id)_severalMessagesString;

@end

