/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class ActivityMonitor, NSPanel, NSProgressIndicator, NSTextField, NSTimer;

@interface ActivityProgressPanel : NSObject
{
    NSPanel *_progressPanel;
    NSProgressIndicator *_progressBar;
    NSTextField *_statusMessage;
    ActivityMonitor *_monitor;
    NSTimer *_timer;
}

- (id)init;
- (void)_invalidateTimer;
- (void)dealloc;
- (id)activityMonitor;
- (void)setActivityMonitor:(id)arg1;
- (id)statusMessage;
- (void)setStatusMessage:(id)arg1;
- (id)panel;
- (void)_updateProgressBar;
- (void)_activityStarted:(id)arg1;
- (void)_activityEnded:(id)arg1;
- (void)cancel:(id)arg1;

@end

