/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class AuthScheme;

@interface AuthSchemeBindingProxy : NSObject
{
    AuthScheme *_authScheme;
    BOOL _isSeparator;
}

+ (id)noneProxy;
+ (id)separatorProxy;
- (id)init;
- (id)initWithAuthScheme:(id)arg1;
- (void)dealloc;
- (id)humanReadableName;
- (id)name;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
@property BOOL isSeparator; // @synthesize isSeparator=_isSeparator;
@property(retain) AuthScheme *authScheme; // @synthesize authScheme=_authScheme;

@end

