/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSView.h"

@class NSColor;

@interface ContainerView : NSView
{
    struct CGSize _shadowOffset;
    NSColor *_marginColor;
    struct CGColor *_shadowColor;
    double _minMarginTop;
    double _minMarginBottom;
    double _minMarginLeft;
    double _minMarginRight;
    NSView *_contentView;
}

- (id)contentView;
- (void)setContentView:(id)arg1;
- (double)minMarginTop;
- (void)setMinMarginTop:(double)arg1;
- (double)minMarginBottom;
- (void)setMinMarginBottom:(double)arg1;
- (double)minMarginLeft;
- (void)setMinMarginLeft:(double)arg1;
- (double)minMarginRight;
- (void)setMinMarginRight:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateContentFrame:(struct CGRect)arg1;
- (void)updateContentFrame;
- (void)setFrame:(struct CGRect)arg1;

@end

