/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSPopUpButton.h"

@class NSArray, NSURL;

@interface DefaultApplicationPopUpButton : NSPopUpButton
{
    NSURL *_appURL;
    long long _index;
    NSArray *_schemes;
}

- (void)dealloc;
- (id)_mainScheme;
- (void)_setHandler:(id)arg1 forScheme:(id)arg2;
- (id)_imageForURL:(id)arg1;
- (long long)_addItemToPopup:(id)arg1;
- (void)_populateSchemeHandlerPopupWithURL:(id)arg1;
- (id)_copyDefaultURLForScheme:(id)arg1;
- (void)_selectDefaultMailClientAtIndex:(long long)arg1;
- (void)_selectItemInPopup:(id)arg1;
- (void)_setNewApplication:(id)arg1;
- (void)_selectNewAppSelected:(id)arg1;
- (void)configurePopUpForURLSchemes:(id)arg1 usingExampleURLString:(id)arg2;

@end

