/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "DOMDocumentFragment.h"

@interface DOMDocumentFragment (MailExtras)
@property(readonly) DOMDocumentFragment *unwrappedFragment;
- (void)insertTextAtBeginning:(id)arg1 atEnd:(id)arg2;
@end

