/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSView.h"

@class NSImage, NSTrackingArea;

@interface FavoriteMenuScrollHoverView : NSView
{
    NSTrackingArea *_trackingArea;
    unsigned long long _direction;
    NSImage *_arrowImage;
    id _delegate;
}

- (id)initWithDirection:(unsigned long long)arg1;
- (void)updateTrackingAreas;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
@property id delegate; // @synthesize delegate=_delegate;
@property(readonly) unsigned long long direction; // @synthesize direction=_direction;

@end

