/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "AccountDetails.h"

@class NSButton, NSPopUpButton, NSTextField;

@interface IMAPAccountDetails : AccountDetails
{
    NSButton *_compactWhenClosing;
    NSPopUpButton *_messageCaching;
    NSTextField *_serverPathPrefix;
    BOOL _warnedAboutCachingAndIndexing;
    NSButton *_useIDLECommand;
}

- (void)dealloc;
- (Class)accountClass;
- (void)setupUIFromValuesInAccount:(id)arg1;
- (void)setupAccountFromValuesInUI:(id)arg1 forValidation:(BOOL)arg2;
- (void)setUIElementsEnabled:(BOOL)arg1;
- (BOOL)isAccountInformationDirty:(id)arg1;
- (void)didDisplayTabViewItem:(id)arg1;
- (void)_confirmCacheChangeSheetEnded:(id)arg1 alertReturn:(long long)arg2 context:(void *)arg3;
- (void)cachePolicyChanged:(id)arg1;

@end

