/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "Assistant.h"

@class EmailImporter, NSArray, NSDictionary, NSMatrix, NSMutableArray, NSProgressIndicator, NSTabView, NSTableView, NSTextField, NSView;

@interface ImportAssistant : Assistant
{
    NSView *_topView;
    NSTabView *_tabView;
    NSMatrix *_importClients;
    NSTextField *_explanatoryTextInImportClientTab;
    NSProgressIndicator *_progressWheelInImportClientTab;
    NSTextField *_statusLineInImportClientTab;
    NSMatrix *_importTypes;
    NSTextField *_explanatoryText;
    NSProgressIndicator *_progressWheel;
    NSTextField *_statusLine;
    NSTableView *_tableView;
    NSProgressIndicator *_progressBar;
    NSTextField *_textFieldAbove;
    NSTextField *_textFieldBelow;
    NSTextField *_importFinished;
    NSArray *_clients;
    NSDictionary *_client;
    int _currentTab;
    EmailImporter *_importer;
    NSMutableArray *_importers;
    NSMutableArray *_startingImporters;
    double _currentTime;
    double _referenceTime;
}

- (id)initWithAssistentManager:(id)arg1;
- (void)dealloc;
- (id)windowTitle;
- (void)start;
- (BOOL)shouldStop;
- (void)stop;
- (void)goForward;
- (void)goBackward;
- (void)importClientSelected:(id)arg1;
- (void)createNewImporter;
- (void)runImporter;
- (void)presentAlertSheetWithString:(id)arg1;
- (void)moveToTab:(int)arg1;
- (void)importFinished;
- (void)askForMailboxLocation;
- (void)askForMailboxLocationAllowedFileTypes:(id)arg1 allowsMultipleSelection:(BOOL)arg2;
- (void)setStatusLine:(id)arg1;
- (void)clearStatusLine;
- (void)updateTextField:(id)arg1 withValue:(id)arg2;
- (void)setTextFieldAbove:(id)arg1;
- (void)setTextFieldBelow:(id)arg1;
- (void)setExplanatoryText:(id)arg1;
- (void)reloadTableView;
- (void)initializeProgressIndicator;
- (void)_updateProgressIndicatorByValue:(id)arg1;
- (void)_updateProgressIndicatorToValue:(id)arg1;
- (void)_setProgressStartOnItem:(id)arg1;
- (void)updateProgressIndicatorWithFraction:(double)arg1 ofItem:(id)arg2;
- (void)updateProgressIndicatorWithItem:(id)arg1;
- (void)updateProgressIndicatorByValue:(double)arg1;
- (BOOL)shouldUpdateTextFields;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)tableView:(id)arg1 didClickTableColumn:(id)arg2;

@end

