/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

#import "SyncableDataInterestedParty-Protocol.h"

@class NSButton, NSColor, NSMatrix;

@interface JunkPreferences : NSPreferencesModule <SyncableDataInterestedParty>
{
    NSButton *_advancedButton;
    NSMatrix *_junkMailMode;
    NSButton *_junkMailOnOffSwitch;
    NSMatrix *_junkMailWhitelist;
    long long _junkMailBehavior;
}

+ (id)keyPathsForValuesAffectingLabelColor;
+ (id)keyPathsForValuesAffectingIsEnabled;
+ (id)keyPathsForValuesAffectingIsAdvancedEnabled;
- (void)moduleWillBeRemoved;
- (void)moduleWasInstalled;
- (BOOL)isResizable;
- (void)_messageRuleChanged:(id)arg1;
- (id)titleForIdentifier:(id)arg1;
- (id)windowTitle;
- (id)imageForPreferenceNamed:(id)arg1;
- (BOOL)dataWillBeSynced;
- (void)dataWasSynced;
@property(readonly) NSColor *labelColor;
- (void)initializeFromDefaults;
- (void)junkMailToggled:(id)arg1;
- (void)whitelistChanged:(id)arg1;
@property long long junkMailBehavior;
@property(readonly) BOOL isEnabled;
@property(readonly) BOOL isAdvancedEnabled;
- (void)changeJunkMailBehavior:(id)arg1;
- (void)resetJunkMailMap:(id)arg1;
- (void)showCustomJunkMailSettings:(id)arg1;

@end

