/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSTableView.h"

@interface MailTableView : NSTableView
{
    struct {
        unsigned int delegateProvidesDragImage:1;
        unsigned int delegateDoesCommandBySelector:1;
        unsigned int delegateDragWillEndOperation:1;
        unsigned int delegateDraggedImageMovedTo:1;
        unsigned int delegateProvidesBackgroundShadedRegions:1;
        unsigned int delegateProvidesHighlightStyle:1;
        unsigned int delegateRespondsToWillDrawRowsInRange:1;
        unsigned int delegateRespondsToDidDrawRowsInRange:1;
        unsigned int delegateApprovesScrolling:1;
        unsigned int delegateRespondsToGotEvent:1;
        unsigned int delegateRespondsToMouseDown:1;
        unsigned int delegateRespondsToWillMoveToWindow:1;
        unsigned int delegateRespondsToDidMoveToWindow:1;
        unsigned int delegateRespondsToWillStartLiveResize:1;
        unsigned int delegateRespondsToDidEndLiveResize:1;
        unsigned int delegateRespondsToDidBecomeFirstResponder:1;
        unsigned int delegateRespondsToDidResignFirstResponder:1;
        unsigned int delegateRespondsToTopLineColor:1;
        unsigned int delegateApprovesRemoveColumn:1;
        unsigned int delegateApprovesAddColumn:1;
    } _extendedTableViewFlags;
    long long _mfClickedRow;
    BOOL _didLazyLoadMenu;
}

- (id)_extendedDelegate;
- (id)menuForEvent:(id)arg1;
- (void)_mailTableViewCommonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)viewWillStartLiveResize;
- (void)viewDidEndLiveResize;
- (void)keyDown:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)menu;
- (void)drawBackgroundOverhangInRect:(struct CGRect)arg1;
- (void)showTableColumnsFromArray:(id)arg1 allColumns:(id)arg2;
- (void)scrollRowToVisible:(long long)arg1;
- (void)setTableColumn:(id)arg1 toVisible:(BOOL)arg2 atPosition:(long long)arg3;
- (void)moveColumn:(long long)arg1 toColumn:(long long)arg2;
- (void)removeTableColumn:(id)arg1;
- (void)addTableColumn:(id)arg1;
- (id)dragImageForRowsWithIndexes:(id)arg1 tableColumns:(id)arg2 event:(id)arg3 offset:(struct CGPoint *)arg4;
- (void)draggedImage:(id)arg1 endedAt:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
- (void)draggedImage:(id)arg1 movedTo:(struct CGPoint)arg2;
- (BOOL)shouldUseSecondaryHighlightColor;
- (void)_highlightRect:(struct CGRect)arg1 withColor:(id)arg2 usingStyle:(int)arg3;
- (void)_colorizeRow:(long long)arg1 inRect:(struct CGRect)arg2 clipRect:(struct CGRect)arg3;
- (void)drawBackgroundInClipRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawRow:(long long)arg1 clipRect:(struct CGRect)arg2;
- (long long)clickedRow;
- (void)_setMFClickedRow:(long long)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)_postEventNotification:(id)arg1 fromCell:(id)arg2;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidMoveToWindow;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (long long)firstSelectedRow;
- (long long)lastSelectedRow;
- (BOOL)isSelectionVisible;
- (void)showSelectionAndCenter:(BOOL)arg1;
- (void)scrollRowToVisible:(long long)arg1 position:(int)arg2;
- (BOOL)isViewBased;

@end

