/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSToolbar.h"

@interface MailToolbar : NSToolbar
{
    unsigned long long _previousDisplayMode;
    long long _temporaryItemTag;
    BOOL _stateIsTemporary;
    BOOL _previousVisible;
    BOOL _neverShowsBaselineSeparator;
    BOOL _frozen;
}

+ (id)_plistForToolbarWithIdentifier:(id)arg1;
+ (void)upgradeToolbarWithIdentifier:(id)arg1 usingBlock:(id)arg2;
+ (void)upgradeToolbarWithIdentifier:(id)arg1 toDisplayMode:(unsigned long long)arg2;
- (BOOL)_allowsSizeMode:(unsigned long long)arg1;
- (id)_customMetrics;
- (void)setTemporaryDisplayMode:(unsigned long long)arg1 visible:(BOOL)arg2 requiredItemTag:(long long)arg3 identifier:(id)arg4;
- (void)revertTemporaryStateIfAny;
- (void)setDisplayMode:(unsigned long long)arg1;
- (void)setVisible:(BOOL)arg1;
- (void)insertItemWithItemIdentifier:(id)arg1 atIndex:(long long)arg2;
- (void)removeItemAtIndex:(long long)arg1;
- (BOOL)showsBaselineSeparator;
- (void)setShowsBaselineSeparator:(BOOL)arg1;
- (void)setNeverShowsBaselineSeparator:(BOOL)arg1;
- (void)freeze;
- (void)unfreeze;
- (void)validateVisibleItems;

@end

