/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "MVMailboxSelectionOwner-Protocol.h"
#import "MailboxListCellDelegate-Protocol.h"
#import "MailboxesOutlineViewDelegate-Protocol.h"
#import "NSOutlineViewDataSource-Protocol.h"

@class MailboxListCell, MailboxUid, MailboxesOutlineView, NSMutableDictionary, NSTextFieldCell, OutlineViewProgressIndicatorsController;

@interface MailboxesOutlineViewController : NSObject <MailboxesOutlineViewDelegate, MailboxListCellDelegate, MVMailboxSelectionOwner, NSOutlineViewDataSource>
{
    MailboxesOutlineView *_outlineView;
    id <MailboxesOutlineViewControllerDelegate> _delegate;
    long long _reloadingCount;
    long long _wantsToEditInlineCount;
    MailboxUid *_clickedMailbox;
    NSTextFieldCell *_textCell;
    MailboxListCell *_mailboxCell;
    NSMutableDictionary *_trackingAreasByItem;
    OutlineViewProgressIndicatorsController *_progressIndicatorsControllers;
    id _rolledOverItem;
    int _rolledOverIndicator;
    BOOL _mouseIsDown;
    double _idealOutlineViewWidth;
}

- (id)init;
- (void)awakeFromNib;
@property id <MailboxesOutlineViewControllerDelegate> delegate;
- (void)dealloc;
- (void)clearDelegateBecauseWindowIsClosing;
@property(readonly, nonatomic) double minimizedOutlineViewWidth;
@property(readonly, nonatomic) double minimumWidthNeededToUseMailboxes;
@property(readonly, nonatomic) double idealOutlineViewWidth;
- (void)makeMailboxesListFirstResponder;
- (void)editNameOfMailbox:(id)arg1;
- (BOOL)canSelectMailbox:(id)arg1;
@property(readonly) BOOL isReloading;
- (void)_beginReloading;
- (void)_endReloading;
@property(readonly) BOOL wantsToEditInline;
- (void)_beginWantsToEditInline;
- (void)_endWantsToEditInline;
- (double)_adjustWidthForScroller:(double)arg1;
- (id)_firstChildIfCollapsedSpecialMailbox:(id)arg1;
- (unsigned long long)_badgeCountForItem:(id)arg1;
- (int)_alertStateForItem:(id)arg1;
- (void)_clearTrackingAreasForItem:(id)arg1;
- (void)_clearAllTrackingAreas;
- (BOOL)_shouldShowProgressIndicatorForItem:(id)arg1;
- (void)_redisplayRowsForItems:(id)arg1;
- (id)_copyActivityMonitorsForMailbox:(id)arg1 finishedCount:(unsigned long long *)arg2 includingDescendants:(BOOL)arg3;
- (void)_updateProgressIndicatorForMailbox:(id)arg1;
- (void)_configureCell:(id)arg1 forItem:(id)arg2;
- (void)_saveSelectionAndReloadItem:(id)arg1 reloadChildren:(BOOL)arg2;
- (BOOL)_isTopLevelItem:(id)arg1;
- (id)_keyObjectForItem:(id)arg1;
- (id)_itemForKeyObject:(id)arg1;
- (void)cell:(id)arg1 didAddTrackingAreas:(id)arg2;
- (void)cell:(id)arg1 positionProgressIndicatorInRect:(struct CGRect)arg2 withRoundDeterminateColor:(id)arg3;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (BOOL)handleMouseDown:(id)arg1;
- (BOOL)handleMouseUp:(id)arg1;
- (void)_subscriptionClickedForItem:(id)arg1;
- (void)_alertClickedForItem:(id)arg1;
- (void)_offlineAlertSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_toggleShowsUnderInboxForItem:(id)arg1;
- (void)_accountAdded:(id)arg1;
- (void)_accountOfflineStatusDidChange:(id)arg1;
- (void)_mailboxListingDidChange:(id)arg1;
- (void)_mailboxPublicStatusDidChange:(id)arg1;
- (void)_sectionListingDidChange:(id)arg1;
- (void)_mailboxesActivityDidChange:(id)arg1;
- (void)_displayCountDidChange:(id)arg1;
- (void)_userInfoDidChange:(id)arg1;
- (void)_viewerPreferencesChanged:(id)arg1;
- (void)_mailboxPendingNameDidChange:(id)arg1;
- (id)selectedMailboxes;
- (id)selectedMailbox;
- (BOOL)isSelectedMailboxSpecial;
- (void)selectPathsToMailboxes:(id)arg1;
- (void)selectPathsToMailboxes:(id)arg1 scrollToVisible:(BOOL)arg2;
- (BOOL)mailboxIsExpanded:(id)arg1;
- (BOOL)sectionIsExpanded:(id)arg1;
- (id)expandedItems;
- (id)sortedSectionItemsForTimeMachine;
- (void)revealMailbox:(id)arg1;
- (void)_revealMailbox:(id)arg1;
- (id)mailboxSelectionWindow;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (void)_renameFailureSheetEnded:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2;
- (id)outlineView:(id)arg1 persistentObjectForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)pasteboard:(id)arg1 provideDataForType:(id)arg2;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (unsigned long long)_outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4 allowStoreCreation:(BOOL)arg5;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)_scrollOutlineViewRectToVisible:(id)arg1;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)selectAllInOutlineView:(id)arg1;
- (void)setFirstResponderAfterMouseDownOnOutlineView:(id)arg1;
- (void)outlineView:(id)arg1 willShowContextMenu:(id)arg2;
- (void)_menuDidEndTracking:(id)arg1;
- (BOOL)outlineView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)outlineView:(id)arg1 willEditTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewDidReload:(id)arg1;
@property(retain) MailboxUid *clickedMailbox; // @synthesize clickedMailbox=_clickedMailbox;
@property(retain) MailboxesOutlineView *outlineView; // @synthesize outlineView=_outlineView;

@end

