/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSInspectorBar.h"

@class NSView, NSWindow;

@interface MailInspectorBar : NSInspectorBar
{
    NSWindow *_window;
    NSView *_separatorView;
}

+ (Class)standardItemControllerClass;
- (void)dealloc;
- (id)loadedNib;
- (void)_setWindow:(id)arg1;
- (id)_inspectorBarView;
- (void)_tile;

@end

