/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "MessageContentDisplay-Protocol.h"

@class ActivityMonitor, MFError, Message, MimeBody, NSArray, NSAttributedString, NSDictionary, NSIndexSet, NSSet, NSString;

@interface MessageViewingState : NSObject
{
    NSAttributedString *_simpleHeadersString;
    NSAttributedString *_expandedHeadersString;
    NSAttributedString *_headerSecurityString;
    NSDictionary *_addressAttachments;
    NSDictionary *_plainAddresses;
    NSSet *_expandedAddressKeys;
    NSAttributedString *_attachmentsDescription;
    NSArray *_attachments;
    Message *_message;
    NSString *_finalizedMessageHtml;
    ActivityMonitor *_monitor;
    MimeBody *_mimeBody;
    id _document;
    MFError *_error;
    long long _headerIndent;
    long long _headerFontAdjustmentDebt;
    long long _headerFontAdjustment;
    long long _preferredAlternative;
    BOOL _accountWasOffline;
    BOOL _dontCache;
    BOOL _showAllHeaders;
    BOOL _showDefaultHeaders;
    BOOL _isForPrinting;
    BOOL _downloadRemoteURLs;
    BOOL _triedToDownloadRemoteURLs;
    BOOL _messageIsFromMicrosoft;
    BOOL _messageIsOldestInConversation;
    BOOL _isChildRequestForSenders;
    BOOL _isReadyToDisplay;
    BOOL _quotedTextIsVisible;
    long long _relatedMessageType;
    BOOL _isShowingHeaderDetails;
    unsigned long long _numberOfDuplicates;
    int _displayType;
    unsigned int _preferredEncoding;
    NSString *_sender;
    NSString *_senderName;
    NSString *_inReplyToSenderName;
    BOOL _matchedEntireInReplyToMessage;
    NSString *_childAddress;
    NSArray *_requestedAddressesFromChild;
    id <MessageContentDisplay> _displayer;
    id _editor;
    NSIndexSet *_expandedRedundantContentAbbreviatorIndexes;
}

+ (void)initialize;
- (void)release;
- (void)dealloc;
- (id)init;
@property(retain) id editor;
- (void)_editorClosed:(id)arg1;
@property(retain, nonatomic) MimeBody *mimeBody; // @synthesize mimeBody=_mimeBody;
@property(readonly) NSArray *attachments;
@property(nonatomic) BOOL isShowingHeaderDetails;
@property(readonly) NSAttributedString *headerAttributedString;
@property(retain) NSDictionary *plainAddresses;
@property(retain) NSDictionary *addressAttachments;
@property(retain) NSSet *expandedAddressKeys;
@property(retain) NSAttributedString *attachmentsDescription;
@property(readonly) long long headerDetailLevel;
- (id)description;
@property(retain) ActivityMonitor *monitor; // @synthesize monitor=_monitor;
@property(retain) Message *message; // @synthesize message=_message;
@property(copy) NSIndexSet *expandedRedundantContentAbbreviatorIndexes; // @synthesize expandedRedundantContentAbbreviatorIndexes=_expandedRedundantContentAbbreviatorIndexes;
@property(retain) NSAttributedString *headerSecurityString; // @synthesize headerSecurityString=_headerSecurityString;
@property(retain) NSAttributedString *expandedHeadersString; // @synthesize expandedHeadersString=_expandedHeadersString;
@property(retain) NSAttributedString *simpleHeadersString; // @synthesize simpleHeadersString=_simpleHeadersString;
@property(retain, nonatomic) NSArray *requestedAddressesFromChild; // @synthesize requestedAddressesFromChild=_requestedAddressesFromChild;
@property(copy, nonatomic) NSString *childAddress; // @synthesize childAddress=_childAddress;
@property(nonatomic) BOOL matchedEntireInReplyToMessage; // @synthesize matchedEntireInReplyToMessage=_matchedEntireInReplyToMessage;
@property(copy, nonatomic) NSString *inReplyToSenderName; // @synthesize inReplyToSenderName=_inReplyToSenderName;
@property(copy, nonatomic) NSString *senderName; // @synthesize senderName=_senderName;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) unsigned int preferredEncoding; // @synthesize preferredEncoding=_preferredEncoding;
@property(nonatomic) int displayType; // @synthesize displayType=_displayType;
@property(nonatomic) BOOL isChildRequestForSenders; // @synthesize isChildRequestForSenders=_isChildRequestForSenders;
@property(nonatomic) BOOL messageIsOldestInConversation; // @synthesize messageIsOldestInConversation=_messageIsOldestInConversation;
@property(nonatomic) BOOL messageIsFromMicrosoft; // @synthesize messageIsFromMicrosoft=_messageIsFromMicrosoft;
@property(nonatomic) unsigned long long numberOfDuplicates; // @synthesize numberOfDuplicates=_numberOfDuplicates;
@property(nonatomic) long long relatedMessageType; // @synthesize relatedMessageType=_relatedMessageType;
@property(nonatomic) BOOL quotedTextIsVisible; // @synthesize quotedTextIsVisible=_quotedTextIsVisible;
@property BOOL isReadyToDisplay; // @synthesize isReadyToDisplay=_isReadyToDisplay;
@property(nonatomic) BOOL triedToDownloadRemoteURLs; // @synthesize triedToDownloadRemoteURLs=_triedToDownloadRemoteURLs;
@property(nonatomic) BOOL downloadRemoteURLs; // @synthesize downloadRemoteURLs=_downloadRemoteURLs;
@property(nonatomic) BOOL isForPrinting; // @synthesize isForPrinting=_isForPrinting;
@property(nonatomic) BOOL showDefaultHeaders; // @synthesize showDefaultHeaders=_showDefaultHeaders;
@property(nonatomic) BOOL showAllHeaders; // @synthesize showAllHeaders=_showAllHeaders;
@property(nonatomic) BOOL dontCache; // @synthesize dontCache=_dontCache;
@property(nonatomic) BOOL accountWasOffline; // @synthesize accountWasOffline=_accountWasOffline;
@property(nonatomic) long long preferredAlternative; // @synthesize preferredAlternative=_preferredAlternative;
@property(nonatomic) long long headerFontAdjustment; // @synthesize headerFontAdjustment=_headerFontAdjustment;
@property(nonatomic) long long headerFontAdjustmentDebt; // @synthesize headerFontAdjustmentDebt=_headerFontAdjustmentDebt;
@property(nonatomic) long long headerIndent; // @synthesize headerIndent=_headerIndent;
@property(retain, nonatomic) MFError *error; // @synthesize error=_error;
@property(retain, nonatomic) id document; // @synthesize document=_document;
@property(copy, nonatomic) NSString *finalizedMessageHtml; // @synthesize finalizedMessageHtml=_finalizedMessageHtml;

@end

