/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class MessageViewingState, NSMutableArray, NSMutableSet, NSPrintInfo, NSPrintOperation, NSString, NSWindow, SingleMessageViewer;

@interface MessagePrinter : NSObject
{
    SingleMessageViewer *_offscreenViewer;
    NSWindow *_onscreenWindow;
    MessageViewingState *_modelViewingState;
    NSMutableArray *_messages;
    NSMutableSet *_messageStores;
    unsigned long long _messageIndex;
    NSString *_originalFilename;
    NSPrintInfo *_printInfo;
    NSPrintOperation *_printOperation;
    unsigned long long _scalingBehavior;
}

+ (id)sharedPrintInfo;
+ (unsigned long long)_scalingBehaviorFromDefaults;
+ (void)_setScalingBehaviorInDefaults:(unsigned long long)arg1;
- (id)initWithMessages:(id)arg1 forOnscreenWindow:(id)arg2 modelViewingState:(id)arg3;
- (void)dealloc;
- (void)print;
- (void)_messageForPrintingFinishedLoading:(id)arg1;
- (void)_printOperationDidRun:(id)arg1 success:(BOOL)arg2 contextInfo:(void *)arg3;
- (void)_cleanUp;
- (void)_printInfoDidChange:(id)arg1;
- (id)_messageTitleForMessage:(id)arg1;
@property(nonatomic) unsigned long long scalingBehavior;
- (void)_setMessages:(id)arg1;
- (unsigned int)_displayIDForWindow:(id)arg1;
- (struct CGRect)_windowFrameForBehavior:(unsigned long long)arg1 printInfo:(id)arg2;
@property(retain, nonatomic) SingleMessageViewer *offscreenViewer; // @synthesize offscreenViewer=_offscreenViewer;
@property(retain, nonatomic) NSPrintOperation *printOperation; // @synthesize printOperation=_printOperation;
@property(retain, nonatomic) NSPrintInfo *printInfo; // @synthesize printInfo=_printInfo;

@end

