/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSTextContainer.h"

@interface MessageTextContainer : NSTextContainer
{
    struct CGRect _senderImageRect;
    struct CGRect _messageNumberMailboxNameRect;
    struct CGRect _duplicatesLinkRect;
    struct CGRect _attachmentsDescriptionRect;
    struct CGRect _detailsLinkRect;
}

- (id)initWithContainerSize:(struct CGSize)arg1;
- (BOOL)isSimpleRectangularTextContainer;
- (struct CGRect)convertRectFromViewToContainerCoordinates:(struct CGRect)arg1;
@property(nonatomic) struct CGRect messageNumberMailboxNameRect;
@property(nonatomic) struct CGRect duplicatesLinkRect;
@property(nonatomic) struct CGRect senderImageRect;
@property(nonatomic) struct CGRect detailsLinkRect;
- (BOOL)containsPoint:(struct CGPoint)arg1;
- (struct CGRect)lineFragmentRectForProposedRect:(struct CGRect)arg1 sweepDirection:(unsigned long long)arg2 movementDirection:(unsigned long long)arg3 remainingRect:(struct CGRect *)arg4;
@property struct CGRect attachmentsDescriptionRect; // @synthesize attachmentsDescriptionRect=_attachmentsDescriptionRect;

@end

