/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSImageCell.h"

@class NSString, NSTextFieldCell;

@interface MessageListCell : NSImageCell
{
    NSTextFieldCell *_textCell;
    NSString *_stringValue;
    double _maxHeight;
    double _maxWidth;
    int _contentType;
    unsigned long long _contentCount;
}

- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)_textCell;
- (void)setTextColor:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setMaxHeight:(double)arg1;
- (double)maxHeight;
- (void)setMaxWidth:(double)arg1;
- (double)maxWidth;
- (struct CGSize)_imageSizeForCellFrame:(struct CGRect)arg1;
- (struct CGPoint)_drawOriginForSize:(struct CGSize)arg1 inRect:(struct CGRect)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setObjectValue:(id)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)setContentType:(int)arg1;
- (void)setContentCount:(unsigned long long)arg1;
- (id)contentValue;
- (BOOL)isRepresentedAsStaticText;
- (BOOL)isRepresentedAsButton;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityActionNames;

@end

