/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class MTMMailbox, NSConditionLock, NSMutableArray;

@interface MTMMailboxFetcher : NSObject
{
    MTMMailbox *_processingMailbox;
    NSMutableArray *_inactiveMailboxes;
    NSConditionLock *_lock;
    BOOL _threadLaunched;
    MTMMailbox *_loadingMailbox;
}

+ (id)sharedFetcher;
- (id)init;
- (void)dealloc;
- (void)_lock;
- (void)_lockWhenThereIsWorkToDo;
- (void)_unlockAndNotify;
- (void)_workerThread;
- (void)startFetchingMailbox:(id)arg1;
- (void)stopFetchingMailbox:(id)arg1;
- (void)startFetchingInactiveMailbox:(id)arg1;
- (void)stopFetchingInactiveMailbox:(id)arg1;
- (void)_protectedSmartAddMailboxToInactiveMailboxes:(id)arg1;
- (BOOL)shouldContinueFetchingMailbox:(id)arg1;
- (void)waitForActiveMailboxToBeLoadedWithTimeOut:(double)arg1;

@end

