/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (AtomicAddress)
- (id)atomicAddressesOfType:(int)arg1;
- (id)attributedStringOfAddressesAttachments:(id *)arg1 type:(int)arg2;
@end

