/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (AtomicAddress)
+ (id)atomicAddressFromDictionary:(id)arg1;
- (BOOL)containsOnlyAtoms;
- (id)unatomicAddress;
- (id)dictionaryRepresentation;
- (id)atomicAddresses;
- (id)allAddresses;
- (id)addressAttachments;
- (id)unatomicAddresses;
- (id)replaceAttachmentsWithAddressesIncludeName:(BOOL)arg1;
- (BOOL)containsAddressAttachments;
- (id)stringWithAtomsExpanded;
- (id)stringOfAddressesWithAtomsExpandedIncludeName:(BOOL)arg1;
- (id)mutableCopyWithNewAttachments:(id *)arg1;
- (struct _NSRange)convertPlainTextRange:(struct _NSRange)arg1;
- (struct _NSRange)convertToPlainTextRange:(struct _NSRange)arg1;
- (void)testSpotlighting;
- (BOOL)knownToHaveNoRecord;
- (id)addressBookRecord;
- (void)displayCommasExceptAtEnd;
- (void)displayCommasForAllAddresses;
@end

