/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (FindPanelSupport)
- (struct _NSRange)findString:(id)arg1 selectedRange:(struct _NSRange)arg2 options:(unsigned long long)arg3 wrap:(BOOL)arg4;
@end

