/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "PDFView.h"

@class MessageAttachmentViewController;

@interface PDFAttachmentView : PDFView
{
    MessageAttachmentViewController *_attachmentViewController;
    struct CGSize _documentSize;
    BOOL _isSizingToFit;
}

+ (void)initialize;
+ (id)viewForAttachmentViewController:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 viewController:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)doDrawPageContent;
- (BOOL)_isForEditing;
- (BOOL)shouldDisplayInline;
- (struct CGSize)desiredSizeWithMaximumWidth:(double)arg1;
- (id)menuForEvent:(id)arg1;
- (void)dealloc;
- (void)sizeToFit;
- (void)_scaleFactorDidChange:(id)arg1;
- (void)_pageDidChange:(id)arg1;
- (void)setDisplayMode:(long long)arg1;
- (void)documentDidUnlock:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
@property MessageAttachmentViewController *attachmentViewController; // @synthesize attachmentViewController=_attachmentViewController;

@end

