/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "GenericAttachmentFetcher.h"

@interface PhotoExporter : GenericAttachmentFetcher
{
}

+ (BOOL)isPhotoAttachment:(id)arg1;
+ (void)exportPhotoAttachments:(id)arg1;
- (void)_exportAttachments:(id)arg1;
- (void)downloadedAllAttachments;

@end

