/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "RedundantContentAbbreviator.h"

@class DOMHTMLElement;

@interface PullQuoteAbbreviator : RedundantContentAbbreviator
{
    DOMHTMLElement *_quoteWrapper;
    DOMHTMLElement *_quoteComponentWrapper;
    DOMHTMLElement *_quoteContent;
    DOMHTMLElement *_openQuote;
    DOMHTMLElement *_closeQuote;
    DOMHTMLElement *_expandLink;
    BOOL _doNotCollapseContent;
}

- (void)dealloc;
- (double)_minimumHeightForCollapsion;
- (BOOL)_insideElementWithBorderOrBackground;
- (id)_colorStringForQuoteMarks;
- (void)_calibrateQuoteMarksForText:(id)arg1;
- (BOOL)_blockquoteStructureLostDuringQuoteConversion;
- (BOOL)abbreviate;
- (BOOL)expand;
- (void)webViewResized;
- (double)verticalFoldPosition;
@property(nonatomic) BOOL doNotCollapseContent; // @synthesize doNotCollapseContent=_doNotCollapseContent;

@end

