/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "AccountInfoTabOwner-Protocol.h"

@class NSProgressIndicator, NSTableView, NSTextField, NSTimer, NSView, SizeEngine;

@interface Quota : NSObject <AccountInfoTabOwner>
{
    NSView *_view;
    NSTableView *_quotaTable;
    NSProgressIndicator *_progressIndicator;
    NSTextField *_progressField;
    NSTextField *_usageField;
    SizeEngine *_sizeEngine;
    NSTimer *_statusTimer;
}

+ (id)quotaForMailAccount:(id)arg1;
- (id)initWithAccount:(id)arg1;
- (id)init;
- (void)dealloc;
- (Class)engineClass;
- (void)_accountOfflineStatusDidChange:(id)arg1;
- (id)view;
- (void)engineDidStart;
- (void)engineDidFinish;
- (void)updateProgress:(id)arg1;
- (void)_updateProgress:(id)arg1;
- (void)_stopProgress:(id)arg1;
- (void)engineUpdated:(id)arg1;
- (unsigned long long)numberOfSortDescriptors;
- (const struct QuotaSimpleSortDescriptor *)sortDescriptorAtIndex:(unsigned long long)arg1;
- (void)accountInfoWillHideView:(id)arg1;
- (void)accountInfoWillShowView:(id)arg1;
@property(retain, nonatomic) SizeEngine *sizeEngine; // @synthesize sizeEngine=_sizeEngine;

@end

