/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class NSImageView, NSSecureTextField, NSTextField, NSURLAuthenticationChallenge, RSSNonBlockingPanel;

@interface RSSAuthenticationPanel : NSObject
{
    NSTextField *_mainLabel;
    RSSNonBlockingPanel *_panel;
    NSSecureTextField *_password;
    NSTextField *_smallLabel;
    NSTextField *_username;
    NSImageView *_imageView;
    BOOL _nibLoaded;
    BOOL _usingSheet;
    id _callback;
    id _context;
    SEL _selector;
    NSURLAuthenticationChallenge *_challenge;
}

- (id)initWithCallback:(id)arg1 selector:(SEL)arg2 context:(id)arg3;
- (id)init;
- (void)dealloc;
- (void)cancel:(id)arg1;
- (void)logIn:(id)arg1;
- (BOOL)loadNib;
- (void)setUpForChallenge:(id)arg1;
- (void)runAsModalDialogWithChallenge:(id)arg1;
- (void)runAsSheetOnWindow:(id)arg1 withChallenge:(id)arg2;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;

@end

