/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSView.h"

#import "SlidingAnimationDelegate-Protocol.h"

@class ClippedItemsIndicator, NSMutableArray, SlidingAnimation;

@interface SlidingViewsBar : NSView <SlidingAnimationDelegate>
{
    unsigned long long _dragSourceIndex;
    unsigned long long _dropIndex;
    double _draggedItemWidth;
    NSMutableArray *_buttons;
    ClippedItemsIndicator *_rightClipIndicator;
    SlidingAnimation *_animation;
}

+ (double)buttonBottomOffset;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (unsigned long long)lastNonSlidingViewIndex;
- (double)maxButtonXWithoutClipIndicator;
- (double)maxButtonXWithClipIndicator;
- (double)maxButtonX;
- (double)minButtonX;
- (double)minSlidingViewX;
- (struct CGRect)_constrainProposedButtonFrame:(struct CGRect)arg1;
- (double)paddingBetweenButtons;
- (void)reorderedSlidingView:(id)arg1;
- (void)draggedSlidingView:(id)arg1;
- (void)refreshButtons;
- (unsigned long long)dropIndexFromDraggingInfo:(id)arg1;
- (unsigned long long)dropIndexFromLocalPoint:(struct CGPoint)arg1;
- (void)slideButtonsIntoPlace;
@property(nonatomic) unsigned long long dropIndex;
- (id)_lastDraggedEventFollowing:(id)arg1;
- (id)_lastDraggedOrUpEventFollowing:(id)arg1;
- (BOOL)reorderSlidingView:(id)arg1 fromMouseDownEvent:(id)arg2;
- (void)pauseAnimation;
- (void)resumeAnimation;
- (double)widthOfDraggingInfo:(id)arg1;
- (double)slidingWidthForView:(id)arg1;
- (unsigned long long)updateDropTarget:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (void)draggingEnded:(id)arg1;
- (BOOL)isSliding;
- (void)moveSlidingViewToCurrentDropIndex:(id)arg1;
- (id)viewPinnedToOverflowIndicator;
- (void)viewWillBeginDragging:(id)arg1;
- (BOOL)isFlipped;
- (void)_mainStatusDidChange:(id)arg1;
- (void)_ensureButtonIsInViewHierarchy:(id)arg1;
@property double draggedItemWidth; // @synthesize draggedItemWidth=_draggedItemWidth;
@property(retain) SlidingAnimation *animation; // @synthesize animation=_animation;
@property(retain) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(retain) ClippedItemsIndicator *rightClipIndicator; // @synthesize rightClipIndicator=_rightClipIndicator;
@property unsigned long long dragSourceIndex; // @synthesize dragSourceIndex=_dragSourceIndex;

@end

