/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



#import "AccountStatusDataSourceDelegate-Protocol.h"
#import "NSTableViewDataSource-Protocol.h"

@class AccountStatusDataSource, NSArrayController, NSMutableArray, NSMutableDictionary, NSPanel, NSTableView, NSTextField, SMTPAccount;

@interface SMTPSettings : NSObject <AccountStatusDataSourceDelegate, NSTableViewDataSource>
{
    NSMutableArray *_deliveryAccounts;
    NSArrayController *_deliveryAccountsController;
    SMTPAccount *_selectedDeliveryAccount;
    NSPanel *_panel;
    NSTableView *_accountTable;
    NSTextField *_portField;
    AccountStatusDataSource *_deliveryASDS;
    NSMutableArray *_accountsInConflict;
    NSMutableDictionary *_cachedAccountEmployment;
    NSMutableDictionary *_cachedAccountEmploymentStrings;
    BOOL _didRegisterForNotifications;
}

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedPanel;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)runSheetRelativeToWindow:(id)arg1 selectedAccount:(id)arg2 didEndDelegate:(id)arg3;
- (void)_sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)dismissPanel:(id)arg1;
- (void)_syncBindings;
- (void)_updatePortNumber;
- (void)_updatePortFieldEnabled;
- (BOOL)_validateAccounts;
- (void)_accountInfoDidChange:(id)arg1;
- (BOOL)_checkForConflicts;
- (void)_removeInvalidAccounts;
- (void)_recacheAccountEmployment;
- (void)_restoreMailAccountDefaultAccounts;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
@property(retain) NSMutableArray *deliveryAccounts; // @synthesize deliveryAccounts=_deliveryAccounts;

@end

