/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class Message, MessageTextView, NSAttributedString, NSWindow;

@interface TextMessageDisplay : NSObject <NSTextViewDelegate>
{
    MessageTextView *_textView;
    NSWindow *_singleWindow;
    Message *_message;
    NSAttributedString *_rawSourceString;
    BOOL _showControlCharacters;
}

+ (void)displayRawSourceForMessage:(id)arg1;
+ (void)_removeDisplayForMessage:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)_beginBackgroundLoad;
- (void)_prepareForMessage:(id)arg1;
- (void)_displayRawSource;
- (id)messageTextView:(id)arg1 willReturnMenu:(id)arg2 forEvent:(id)arg3;
- (BOOL)validateMenuItem:(id)arg1;
- (void)bringToFront;
- (void)windowWillClose:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)showPrintPanel:(id)arg1;
- (void)toggleShowControlCharacters:(id)arg1;
- (void)saveAs:(id)arg1;
@property(retain, nonatomic) Message *message; // @synthesize message=_message;

@end

