/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSImageView.h"

@class NSView;

@interface TransparentImageView : NSImageView
{
    NSView *_backgroundView;
}

- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)accessibilityAttributeValue:(id)arg1;

@end

