/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class NSAttributedString, NSMutableArray, NSString;

@interface WebComposeMessageContents : NSObject
{
    long long _composeMode;
    NSAttributedString *_plainText;
    NSString *_topLevelHtmlString;
    NSMutableArray *_attachmentsAndHtmlStrings;
    NSMutableArray *_urlsForAttachmentsAndHtmlStrings;
}

- (void)dealloc;
- (void)addAttachmentOrHtmlString:(id)arg1 withURL:(id)arg2;
- (id)description;
@property(retain, nonatomic) NSMutableArray *urlsForAttachmentsAndHtmlStrings; // @synthesize urlsForAttachmentsAndHtmlStrings=_urlsForAttachmentsAndHtmlStrings;
@property(retain, nonatomic) NSMutableArray *attachmentsAndHtmlStrings; // @synthesize attachmentsAndHtmlStrings=_attachmentsAndHtmlStrings;
@property(retain, nonatomic) NSString *topLevelHtmlString; // @synthesize topLevelHtmlString=_topLevelHtmlString;
@property(retain, nonatomic) NSAttributedString *plainText; // @synthesize plainText=_plainText;
@property(nonatomic) long long composeMode; // @synthesize composeMode=_composeMode;

@end

