/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "WebHTMLView.h"

@interface WebHTMLView (MailExtras)
- (void)takeFindStringFromSelection:(id)arg1;
- (BOOL)findString:(id)arg1 options:(unsigned long long)arg2 wrap:(BOOL)arg3;
- (id)_mail_enclosingEmailView;
@end

