/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/SASLClient.h>

@interface _ExternalSASLClient : SASLClient
{
}

- (id)initWithMechanismName:(id)arg1 account:(id)arg2;
- (id)init;
- (id)initialResponse;
- (id)responseForServerData:(id)arg1;
- (id)newEncryptedDataForBytes:(const char *)arg1 length:(unsigned int)arg2;
- (id)newDecryptedDataForBytes:(const char *)arg1 length:(unsigned int)arg2;

@end

