/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/EWSResponseOperation.h>

@class NSArray, NSMutableArray;

@interface EWSGetItemsResponseOperation : EWSResponseOperation
{
    NSArray *_EWSItemIdsRequested;
    NSMutableArray *_EWSItems;
}

- (void)dealloc;
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;
- (void)executeOperation;
@property(retain) NSArray *EWSItemIdsRequested; // @synthesize EWSItemIdsRequested=_EWSItemIdsRequested;
@property(retain) NSMutableArray *EWSItems; // @synthesize EWSItems=_EWSItems;

@end

