/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class NSMutableArray;

@interface IMAPDownload : NSObject
{
    unsigned int _uid;
    NSMutableArray *_pendingFetchResults;
}

- (void)dealloc;
- (id)initWithUid:(unsigned int)arg1;
- (id)init;
- (id)createCopy;
- (unsigned int)uid;
- (unsigned int)expectedLength;
- (BOOL)isComplete;
- (unsigned int)bytesFetched;
- (id)data;
- (id)error;
- (void)setError:(id)arg1;
- (void)handleFetchResult:(id)arg1;
- (void)processResults;
- (void)addCommandsToPipeline:(id)arg1 withCache:(id)arg2;
- (id)description;

@end

