/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@class MailboxUid;

@interface MFCachedMailboxInfo : NSObject
{
    long long _mailboxID;
    int _mailboxType;
    MailboxUid *_mailbox;
}

- (id)init;
- (void)dealloc;
- (void)updateWithMessage:(id)arg1;
@property(retain, nonatomic) MailboxUid *mailbox; // @synthesize mailbox=_mailbox;
@property(nonatomic) int mailboxType; // @synthesize mailboxType=_mailboxType;
@property(nonatomic) long long mailboxID; // @synthesize mailboxID=_mailboxID;

@end

