/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */



@interface MFZombies : NSObject
{
}

+ (void)initialize;
+ (id)__objectZombieLock;
+ (id)__objectZombieMap;
+ (id)__objectRRLock;
+ (id)__objectRRMap;
+ (id)__stackUniquingLock;
+ (id)__stackUniquingSet;
+ (id)__copyArrayOfStringsForPointers:(id)arg1;
+ (BOOL)__writeZombieStacksToDiskForObject:(id)arg1;
+ (BOOL)__writeAllZombieStacksToDisk;

@end

