/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@class ActivityMonitor, NSLock, POP3FetchStore;

@interface POPAccount : MailAccount
{
    POP3FetchStore *_fetcher;
    ActivityMonitor *_fetchMonitor;
    NSLock *_connectionActivityLock;
    id _seenMessagesManagerLock;
    BOOL _fetcherNeedsReset;
    BOOL _deletingMessages;
    BOOL _hasDoneBackgroundSynchronization;
}

+ (id)accountTypeString;
- (id)initWithAccountInfo:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (BOOL)supportsNotes;
- (BOOL)_configureFetcherObject;
- (void)fetchSynchronously;
- (void)resetFetcher;
- (void)releaseAllConnections;
- (id)iaServiceType;
- (BOOL)canGoOffline;
- (void)setIsOffline:(BOOL)arg1;
- (void)_readCustomInfoFromMailboxCache:(id)arg1;
- (void)updateFromSyncedDictionary:(id)arg1;
- (unsigned int)defaultPortNumber;
- (unsigned int)defaultSecurePortNumber;
- (id)serviceName;
- (id)secureServiceName;
- (id)saslProfileName;
- (BOOL)requiresAuthentication;
- (Class)storeClass;
- (Class)connectionClass;
- (BOOL)isSyncable;
- (id)mailboxPathExtension;
- (id)primaryMailboxUid;
- (BOOL)containsMailboxes;
- (BOOL)canCreateNewMailboxes;
- (BOOL)canMailboxBeRenamed:(id)arg1;
- (BOOL)_setPath:(id)arg1;
- (long long)bigMessageWarningSize;
- (void)setBigMessageWarningSize:(long long)arg1;
- (BOOL)didTryUpgradingToAPOP;
- (void)setDidTryUpgradingToAPOP:(BOOL)arg1;
- (void)setMessageDeletionPolicy:(int)arg1;
- (void)setDelayedMessageDeletionInterval:(unsigned long long)arg1;
- (int)messageDeletionPolicy;
- (unsigned long long)delayedMessageDeletionInterval;
- (BOOL)deletingMessages;
- (void)deleteMessagesNow:(id)arg1;
- (void)deleteSeenMessagesNow;
- (void)insertInMailboxes:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)acquireConnectionActivityLock;
- (void)relinquishConnectionActivityLock;
- (id)archiveMailboxUidCreateIfNeeded:(BOOL)arg1;
- (id)newSeenMessagesManager;
- (void)_addAccountAndSeenMessagesToMessageManager;
- (id)_URLPersistenceScheme;
- (id)_infoForMatchingURL:(id)arg1;
- (id)storeForMailboxUid:(id)arg1 createIfNeeded:(BOOL)arg2;
- (BOOL)deleteMessagesWhenMovedFromInbox;
- (void)setDeleteMessagesWhenMovedFromInbox:(BOOL)arg1;
- (BOOL)deleteMessagesOnServer;
- (void)setDeleteMessagesOnServer:(BOOL)arg1;
- (id)mailboxes;
- (id)objectSpecifierForMailboxUid:(id)arg1;
- (id)valueInMailboxesWithName:(id)arg1;

@end

