/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class MFMailAccount, NSImageCell;

@interface _AccountDisplayCell : NSTextFieldCell
{
    NSTextFieldCell *_descriptionTextCell;
    NSTextFieldCell *_activeTextCell;
    NSImageCell *_imageCell;
    MFMailAccount *_account;
}

@property(retain, nonatomic) MFMailAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) NSImageCell *imageCell; // @synthesize imageCell=_imageCell;
@property(readonly, nonatomic) NSTextFieldCell *activeTextCell; // @synthesize activeTextCell=_activeTextCell;
@property(readonly, nonatomic) NSTextFieldCell *descriptionTextCell; // @synthesize descriptionTextCell=_descriptionTextCell;
- (void).cxx_destruct;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)willBeDisplayed;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (struct CGRect)expansionFrameWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_accountDisplayCellCommonInit;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;

@end

