/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class ComposeWindowController, NSDictionary, NSSet;

@protocol ComposeContext <NSObject>
@property(readonly, nonatomic) BOOL isInteractive;
@property(readonly, copy, nonatomic) NSDictionary *editorSettings;
@property(readonly, copy, nonatomic) NSSet *targetMessages;
@property(readonly, nonatomic) BOOL isMiniaturized;
@property(readonly, nonatomic) long long type;
@property(readonly, nonatomic) BOOL blockRemoteContent;
@property(readonly, nonatomic) BOOL shouldTransientlyActivateApplication;
- (id)windowControllerWithState:(id)arg1;
- (void)controllerWillClose:(id)arg1;
- (void)presentEditor:(id)arg1 completion:(id)arg2;
- (void)loadCompleted:(id)arg1;
- (void)generateQuotedContentWithCompletion:(id)arg1;

@optional
@property(nonatomic) __weak ComposeWindowController *windowController;
@property(readonly, nonatomic) NSDictionary *destinationGeometry;
@property(readonly, nonatomic) NSDictionary *sourceGeometry;
- (void)getDestinationSnapshotParts:(id)arg1;
- (void)getSourceSnapshotParts:(id)arg1;
@end

