/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSViewController.h"

#import "SortTitleSetter.h"

@class NSArray, NSButton, NSLayoutConstraint, NSString, NSTableView, RichMessageListSortView, TableViewManager;

@interface MessageListController : NSViewController <SortTitleSetter>
{
    BOOL _isRichMessageList;
    RichMessageListSortView *_sortView;
    NSTableView *_messagesTableView;
    TableViewManager *_tableViewManager;
    NSButton *_sortButton;
    id <MessageListControllerDelegate> _delegate;
    NSLayoutConstraint *_sortBarTopAlignmentConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *sortBarTopAlignmentConstraint; // @synthesize sortBarTopAlignmentConstraint=_sortBarTopAlignmentConstraint;
@property(nonatomic) __weak id <MessageListControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSButton *sortButton; // @synthesize sortButton=_sortButton;
@property(retain, nonatomic) TableViewManager *tableViewManager; // @synthesize tableViewManager=_tableViewManager;
@property(nonatomic) __weak NSTableView *messagesTableView; // @synthesize messagesTableView=_messagesTableView;
@property(nonatomic) __weak RichMessageListSortView *sortView; // @synthesize sortView=_sortView;
- (void).cxx_destruct;
- (void)keyDown:(id)arg1;
- (void)_mallDidOpen:(id)arg1;
- (void)_registerForStoreNotifications:(id)arg1;
- (void)_unregisterForStoreNotifications:(id)arg1;
- (void)_setMessageMall:(id)arg1;
- (void)dismissController:(id)arg1;
- (void)updateViewConstraints;
- (void)viewDidLoad;
- (void)sortBarClicked:(id)arg1;
- (void)setAccessibilityLinkedUIElementForMessageList:(id)arg1;
@property(copy, nonatomic) NSArray *selectedMessages;
@property(readonly, nonatomic) BOOL isSortedAscending;
@property(readonly, nonatomic) long long sortColumn;
- (void)setSortTitle:(id)arg1;
@property(nonatomic) BOOL isRichMessageList; // @synthesize isRichMessageList=_isRichMessageList;
- (void)_updateSortViewVisibility;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

