/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

#import "NSAccessibilityGroup.h"

@class NSString;

@interface MessageListContainerView : NSView <NSAccessibilityGroup>
{
}

- (id)accessibilityIdentifier;
- (struct CGRect)accessibilityFrame;
- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

