/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageList.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface SingletonMessageList : NSObject <MessageList>
{
    NSMutableArray *_filteredMessages;
    NSMutableDictionary *_messageSortValues;
    id <MessageListDelegate> _delegate;
    id _comparator;
}

@property(copy, nonatomic) id comparator; // @synthesize comparator=_comparator;
@property(readonly, nonatomic) __weak id <MessageListDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned long long)_removeObjectIfPresent:(id)arg1 fromArray:(id)arg2 inSortedRange:(struct _NSRange)arg3 usingComparator:(id)arg4 didRemove:(void)arg5;
- (unsigned long long)_insertObjectIfAbsent:(id)arg1 intoArray:(id)arg2 inSortedRange:(struct _NSRange)arg3 usingComparator:(id)arg4 didInsert:(void)arg5;
- (unsigned long long)_removeMessage:(id)arg1 inSortedRange:(struct _NSRange)arg2 didRemove:(char *)arg3;
- (id)_newSortComparator;
- (id)_refreshedMessageSortValues;
- (id)mutableCopyOfFilteredMessages;
- (id)copyOfFilteredMessages;
- (unsigned long long)adjustedIndexOfMessage:(id)arg1;
- (unsigned long long)indexOfFilteredMessage:(id)arg1;
- (void)enumerateFilteredMessagesUsingBlock:(id)arg1;
- (unsigned long long)filteredMessagesCount;
- (id)filteredMessagesAtIndexes:(id)arg1;
- (id)filteredMessageAtIndex:(unsigned long long)arg1;
- (unsigned long long)removeMessage:(id)arg1;
- (id)removeMessages:(id)arg1;
- (unsigned long long)mergeMessage:(id)arg1;
- (id)mergeMessages:(id)arg1;
- (id)filterOutMessages:(id)arg1 andReplaceMessages:(id)arg2;
- (id)filterInMessages:(id)arg1 secondaryMessages:(id)arg2;
- (void)updateMessages:(id)arg1;
- (void)invert;
- (void)resort;
- (id)init;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

