/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol TabBarViewDelegate <NSObject>
- (BOOL)tabBarView:(id)arg1 acceptDrop:(id)arg2 index:(unsigned long long)arg3;
- (unsigned long long)tabBarView:(id)arg1 validateDrop:(id)arg2;
- (void)tabBarView:(id)arg1 didFinishTransitionAnimationForWindow:(id)arg2;
- (id)tabBarView:(id)arg1 destinationWindowForDetachedTabBarViewItem:(id)arg2;
- (id)tabBarView:(id)arg1 detachedWindowImageForDraggedTabBarViewItem:(id)arg2;
- (BOOL)tabBarView:(id)arg1 acceptTabDrop:(id)arg2 index:(unsigned long long)arg3;
- (unsigned long long)tabBarView:(id)arg1 validateTabDrop:(id)arg2;
- (id)tabBarView:(id)arg1 menuForTabBarViewItem:(id)arg2 event:(id)arg3;
- (void)tabBarView:(id)arg1 didMoveTabBarViewItem:(id)arg2 toIndex:(unsigned long long)arg3;
- (void)tabBarView:(id)arg1 closeTabBarViewItem:(id)arg2;
- (id)selectedTabBarViewItemAfterClosingCurrentTabInTabBarView:(id)arg1;
- (void)tabBarView:(id)arg1 selectTabBarViewItem:(id)arg2;
- (void)createNewTabInTabBarView:(id)arg1;
- (void)tabBarViewDidZoomIn:(id)arg1;
@end

