/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@class NSHashTable, NSImageView;

@interface ViewingPaneView : NSView
{
    NSHashTable *_topAlignedSubviews;
    NSHashTable *_managedConstraints;
    BOOL _isVertical;
    NSView *_singleMessageLoadingView;
    NSImageView *_snapshotView;
    NSView *_contentView;
}

+ (BOOL)automaticallyNotifiesObserversOfContentView;
@property(nonatomic) BOOL isVertical; // @synthesize isVertical=_isVertical;
@property(readonly, nonatomic) NSImageView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(readonly, nonatomic) NSView *singleMessageLoadingView; // @synthesize singleMessageLoadingView=_singleMessageLoadingView;
- (void).cxx_destruct;
- (void)setLoadingOption:(long long)arg1;
- (void)viewDidMoveToWindow;
- (void)updateConstraints;
- (void)_showSnapshot;
- (void)_showSingleMessageLoadingView;
- (void)_hideSnapshot;
- (void)_hideSingleMessageLoadingView;
- (void)setContentView:(id)arg1 titlebarAligned:(BOOL)arg2;
@property(readonly, nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
- (void)_createSnapshotView;
- (void)_createSingleMessageLoadingView;
- (void)_createBackdropView;
- (void)_viewingPaneViewCommonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

