/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateLastViewed : MFMessageSortingValue
{
    double _dateLastViewedAsTimeIntervalSince1970;
}

- (id)description;
- (void)setDateLastViewedAsTimeIntervalSince1970:(double)arg1;
- (double)dateLastViewedAsTimeIntervalSince1970;

@end

