/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Mail/MFMessageSortingValue.h>

@class NSString;

@interface _MFMessageSortingValueSubject : MFMessageSortingValue
{
    NSString *_subject;
    unsigned char _subjectPrefixLength;
}

- (id)description;
- (id)subjectAndPrefixLength:(unsigned long long *)arg1;
- (void)setSubjectPrefixLength:(unsigned char)arg1;
- (void)setSubject:(id)arg1;
- (id)subject;
- (void)dealloc;

@end

