/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSOperationQueue.h"

@interface NSOperationQueue (MCTaskOperation)
- (void)addTaskOperation:(id)arg1 taskName:(id)arg2 priority:(unsigned char)arg3 canCancel:(BOOL)arg4;
@end

