/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_MTMMetaMailbox.h"

@interface _MTMInboxMailbox : _MTMMetaMailbox
{
}

- (id)restoreString;
- (id)recoverDisplayName;
- (id)defaultMessageColumnAttributesKey;
- (id)displayName;

@end

