/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "BannerViewController.h"

@class BannerImageView, NSButton, NSLayoutConstraint, NSTextField;

@interface ChildBannerViewController : BannerViewController
{
    long long _parentalControlMessageState;
    BannerImageView *_icon;
    NSTextField *_messageField;
    NSButton *_helpButton;
    NSButton *_sendButton;
    NSLayoutConstraint *_helpButtonTrailingSpace;
}

@property(nonatomic) __weak NSLayoutConstraint *helpButtonTrailingSpace; // @synthesize helpButtonTrailingSpace=_helpButtonTrailingSpace;
@property(nonatomic) __weak NSButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) __weak NSButton *helpButton; // @synthesize helpButton=_helpButton;
@property(nonatomic) __weak NSTextField *messageField; // @synthesize messageField=_messageField;
@property(nonatomic) __weak BannerImageView *icon; // @synthesize icon=_icon;
@property(nonatomic) long long parentalControlMessageState; // @synthesize parentalControlMessageState=_parentalControlMessageState;
- (void).cxx_destruct;
- (void)sendMessage:(id)arg1;
- (void)updateBannerContents;
- (void)updateWantsDisplay;
- (id)nibName;

@end

