/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

@class NSButton, NSColor, NSMatrix;

@interface JunkPreferences : NSPreferencesModule
{
    long long _junkMailBehavior;
    NSButton *_advancedButton;
    NSMatrix *_junkMailMode;
    NSButton *_junkMailOnOffSwitch;
    NSMatrix *_junkMailWhitelist;
}

+ (id)keyPathsForValuesAffectingIsAdvancedEnabled;
+ (id)keyPathsForValuesAffectingIsEnabled;
+ (id)keyPathsForValuesAffectingLabelColor;
@property(nonatomic) __weak NSMatrix *junkMailWhitelist; // @synthesize junkMailWhitelist=_junkMailWhitelist;
@property(nonatomic) __weak NSButton *junkMailOnOffSwitch; // @synthesize junkMailOnOffSwitch=_junkMailOnOffSwitch;
@property(nonatomic) __weak NSMatrix *junkMailMode; // @synthesize junkMailMode=_junkMailMode;
@property(nonatomic) __weak NSButton *advancedButton; // @synthesize advancedButton=_advancedButton;
- (void).cxx_destruct;
- (void)showCustomJunkMailSettings:(id)arg1;
- (void)resetJunkMailMap:(id)arg1;
- (void)changeJunkMailBehavior:(id)arg1;
@property(readonly, nonatomic) BOOL isAdvancedEnabled;
@property(readonly, nonatomic) BOOL isEnabled;
@property(nonatomic) long long junkMailBehavior;
- (void)whitelistChanged:(id)arg1;
- (void)junkMailToggled:(id)arg1;
- (void)initializeFromDefaults;
@property(readonly, nonatomic) NSColor *labelColor;
- (id)imageForPreferenceNamed:(id)arg1;
- (id)windowTitle;
- (id)titleForIdentifier:(id)arg1;
- (void)_messageRuleChanged:(id)arg1;
- (BOOL)isResizable;
- (void)moduleWasInstalled;
- (void)moduleWillBeRemoved;

@end

