/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MailboxesOutlineViewControllerDelegate <NSObject>
- (long long)viewerNumber;
- (void)focusMessages;
- (void)selectAllMessages;

@optional
- (void)mailboxSelectionChanged:(id)arg1;
@end

