/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@interface NSView (ResizingAnimation)
- (void)setFrame:(struct CGRect)arg1 animate:(BOOL)arg2 repositionOtherSiblings:(BOOL)arg3;
- (void)setFrame:(struct CGRect)arg1 animate:(BOOL)arg2;
@end

