/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSTextFinderAsynchronousDocumentFindMatch.h"

@class ConversationView, ConversationViewFindController, NSArray;

@interface _ConversationFindMatch : NSObject <NSTextFinderAsynchronousDocumentFindMatch>
{
    ConversationView *_containingView;
    id <NSTextFinderAsynchronousDocumentFindMatch> _backingFindMatch;
    unsigned long long _cellIndex;
    NSArray *_textRectsInCellView;
    ConversationViewFindController *_findController;
}

@property(retain, nonatomic) ConversationViewFindController *findController; // @synthesize findController=_findController;
@property(retain, nonatomic) NSArray *textRectsInCellView; // @synthesize textRectsInCellView=_textRectsInCellView;
@property(nonatomic) unsigned long long cellIndex; // @synthesize cellIndex=_cellIndex;
@property(retain, nonatomic) id <NSTextFinderAsynchronousDocumentFindMatch> backingFindMatch; // @synthesize backingFindMatch=_backingFindMatch;
@property(retain, nonatomic) ConversationView *containingView; // @synthesize containingView=_containingView;
- (void)generateTextImage:(id)arg1;
@property(readonly, nonatomic) NSArray *textRects;
- (void)dealloc;

@end

