/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

#import "AccountStatusDataSourceDelegate.h"
#import "MVTerminationHandler.h"
#import "NSTabViewDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class AccountDetails, AccountStatusDataSource, MFMailAccount, NSButton, NSIndexSet, NSMutableArray, NSMutableDictionary, NSPopUpButton, NSSegmentedControl, NSString, NSTabView, NSTableView, NSTextField, NSTextView, NSView;

@interface AccountPreferences : NSPreferencesModule <AccountStatusDataSourceDelegate, MVTerminationHandler, NSTableViewDataSource, NSTableViewDelegate, NSTabViewDelegate>
{
    NSMutableArray *_accounts;
    AccountDetails *_accountDetails;
    NSTabView *_detailTabView;
    NSTableView *_accountsTable;
    NSSegmentedControl *_addRemoveAccountControl;
    NSButton *_helpButton;
    NSButton *_enableAccountCheckbox;
    NSPopUpButton *_accountTypePopup;
    NSTextField *_accountTypeString;
    NSTextField *_accountName;
    NSTextField *_fullNameField;
    NSTextField *_emailAddressField;
    NSTextField *_username;
    NSTextField *_hostnameLabel;
    NSTextField *_hostname;
    NSTextField *_externalHostnameLabel;
    NSTextField *_externalHostname;
    NSTextField *_password;
    AccountStatusDataSource *_deliveryASDS;
    NSTextField *_deliveryAccountLabel;
    NSPopUpButton *_smtpAccountPopup;
    NSButton *_lockDeliveryAccountButton;
    NSView *_outlookWebAccessView;
    NSTextField *_outlookWebAccessServerName;
    NSTextField *_aliasLabel;
    NSPopUpButton *_aliasPopup;
    NSView *_tlsCertificatesView;
    NSPopUpButton *_tlsCertificatesPopup;
    NSButton *_ewsAutodiscoveryCheckbox;
    MFMailAccount *_accountBeingEdited;
    MFMailAccount *_accountBeingValidated;
    BOOL _accountBeingEditedWasEnabledWhenEditingStarted;
    BOOL _creatingNewAccount;
    BOOL _passwordFieldHasBeenTouched;
    long long _indexOfNewAccount;
    struct {
        unsigned int userWantsToQuit:1;
        unsigned int userWantsToClosePrefsPanel:1;
        unsigned int userWantsToChangeSelection:1;
        unsigned int userWantsToCreateNewAccount:1;
        unsigned int userWantsToOpenNewAccountAssistant:1;
    } _flags;
    NSIndexSet *_selectedRows;
    NSString *_selectedToolbarIdentifier;
    BOOL _ignoreTableViewSelectionCallbacks;
    BOOL _registeredForNotifications;
    BOOL _lastPopupSelectionWasAOS;
    NSMutableDictionary *_userEnteredInfo;
    NSTextView *_accountSupportURLField;
    NSTextField *_passwordLabel;
}

+ (id)ispAccountInfoOfSelectedItemInAccountTypePopup:(id)arg1;
+ (Class)accountClassOfSelectedItemInAccountTypePopup:(id)arg1;
+ (void)selectAccoutType:(Class)arg1 inTypePopup:(id)arg2;
+ (void)configureAccountTypePopUp:(id)arg1;
+ (void)editServerList:(id)arg1 selectedAccount:(id)arg2;
+ (void)focusAccount:(id)arg1;
+ (void)initialize;
+ (void)_addAccountType:(id)arg1 class:(Class)arg2;
@property(nonatomic) NSTextField *passwordLabel; // @synthesize passwordLabel=_passwordLabel;
- (Class)_classForNewAccount;
- (id)_nameForNewAccount;
- (void)controlTextDidChange:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (BOOL)selectionShouldChangeInTableView:(id)arg1;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (id)_accountAtRow:(long long)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)editServerList:(id)arg1 selectedAccount:(id)arg2;
- (void)editAliases:(id)arg1;
- (void)setAlias:(id)arg1;
- (void)customAlias:(id)arg1;
- (void)accountTypeChanged:(id)arg1;
- (void)_accountTypePopupWillPopup:(id)arg1;
- (BOOL)_newSettingsAreValid;
- (void)_synchronizeAliasPopup;
- (void)_updateAliasPopup;
- (void)_updateAccountTypePopup;
- (void)_setupAccountFromValuesInUI:(id)arg1 forValidation:(BOOL)arg2;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)_saveAccountBeingEdited;
- (void)_runAccountDetailPanelForAccount:(id)arg1;
- (void)_setupUIForAccountBeingEdited;
- (void)_reloadDeliveryAccountPopup:(id)arg1;
- (void)_clearAccountUI;
- (void)_setUIElementsEnabled:(BOOL)arg1;
- (void)toggleEWSAutodiscovery:(id)arg1;
- (void)_tableDidResize:(id)arg1;
- (BOOL)_allowSwitchingAwayFromSelectedAccount;
- (void)_handleRequestToSwitchAwayFromSelectedAccountWithResponse:(BOOL)arg1;
- (BOOL)_isAccountInformationDirty;
- (void)editMailAccount:(id)arg1;
- (void)editAccount:(id)arg1;
- (void)_removeAccountBeingCreated;
- (void)addRemoveAccountClick:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)toggleIncludeWhenCheckingForNewMail:(id)arg1;
- (void)toggleAccountEnabled:(id)arg1;
- (void)_saveAccountInfo;
- (BOOL)preferencesWindowShouldClose;
- (BOOL)moduleCanBeRemoved;
- (void)moduleWasInstalled;
- (void)nowWouldBeAGoodTimeToTerminate:(id)arg1;
- (void)initializeFromDefaults;
- (id)init;
- (id)imageForPreferenceNamed:(id)arg1;
- (void)_accountDidChange:(id)arg1;
- (void)_accountsDidChange:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (id)windowTitle;
- (id)titleForIdentifier:(id)arg1;

@end

