/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSView;

@interface Assistant : NSObject
{
    NSView *_parentView;
    NSButton *_backButton;
    NSButton *_forwardButton;
    NSButton *_cancelButton;
    NSButton *_helpButton;
    id <AssistantDelegate> _delegate;
}

- (void)setupKeyViewLoop;
- (id)windowTitle;
- (void)weAreDone;
- (BOOL)shouldStop;
- (void)goBackward;
- (void)goForward;
- (void)stop;
- (void)start;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithAssistentManager:(id)arg1;

@end

