/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSViewController.h"

#import "ConversationViewDelegate.h"
#import "NSUserInterfaceValidations.h"

@class ConversationMemberArrayController, ConversationView, ConversationViewFindController, NSMutableDictionary, NSMutableIndexSet, NSMutableOrderedSet, NSUUID, UnfoldAnimationController;

@interface ConversationViewController : NSViewController <ConversationViewDelegate, NSUserInterfaceValidations>
{
    BOOL _automaticallySelectsPinnedMessage;
    BOOL _loaded;
    ConversationView *_conversationView;
    NSMutableOrderedSet *_conversationMembers;
    NSMutableIndexSet *_loadIndexes;
    NSMutableIndexSet *_primaryIndexes;
    NSMutableIndexSet *_unreadIndexes;
    NSMutableIndexSet *_visibleIndexes;
    NSMutableDictionary *_defaultMessageViewingState;
    NSMutableDictionary *_messageViewingStateByLibraryID;
    ConversationMemberArrayController *_arrayController;
    ConversationViewFindController *_findController;
    UnfoldAnimationController *_unfoldAnimationController;
    double _messageHeightBeforeRedundantTextExpansion;
    double _pageZoom;
    NSUUID *_updateUUID;
}

@property(copy, nonatomic) NSUUID *updateUUID; // @synthesize updateUUID=_updateUUID;
@property(nonatomic) double pageZoom; // @synthesize pageZoom=_pageZoom;
@property(nonatomic) double messageHeightBeforeRedundantTextExpansion; // @synthesize messageHeightBeforeRedundantTextExpansion=_messageHeightBeforeRedundantTextExpansion;
@property(nonatomic) BOOL loaded; // @synthesize loaded=_loaded;
@property(nonatomic) BOOL automaticallySelectsPinnedMessage; // @synthesize automaticallySelectsPinnedMessage=_automaticallySelectsPinnedMessage;
@property(retain, nonatomic) UnfoldAnimationController *unfoldAnimationController; // @synthesize unfoldAnimationController=_unfoldAnimationController;
@property(readonly, nonatomic) ConversationViewFindController *findController; // @synthesize findController=_findController;
@property(readonly, nonatomic) ConversationMemberArrayController *arrayController; // @synthesize arrayController=_arrayController;
@property(readonly, nonatomic) NSMutableDictionary *messageViewingStateByLibraryID; // @synthesize messageViewingStateByLibraryID=_messageViewingStateByLibraryID;
@property(readonly, nonatomic) NSMutableDictionary *defaultMessageViewingState; // @synthesize defaultMessageViewingState=_defaultMessageViewingState;
@property(readonly, nonatomic) NSMutableIndexSet *visibleIndexes; // @synthesize visibleIndexes=_visibleIndexes;
@property(readonly, nonatomic) NSMutableIndexSet *unreadIndexes; // @synthesize unreadIndexes=_unreadIndexes;
@property(readonly, nonatomic) NSMutableIndexSet *primaryIndexes; // @synthesize primaryIndexes=_primaryIndexes;
@property(readonly, nonatomic) NSMutableIndexSet *loadIndexes; // @synthesize loadIndexes=_loadIndexes;
@property(readonly, nonatomic) NSMutableOrderedSet *conversationMembers; // @synthesize conversationMembers=_conversationMembers;
@property(readonly, nonatomic) ConversationView *conversationView; // @synthesize conversationView=_conversationView;
- (void)_cancelRedundantTextExpansionAnimation;
- (void)performRedundantTextExpansionForDocumentView:(id)arg1 atClusterIndex:(long long)arg2;
- (void)_startRedundantTextExpansionAnimationForWebDocumentView:(id)arg1;
- (void)_getInitialMetricsAndSnapshotForRedundantTextExpansionForDocumentView:(id)arg1 atClusterIndex:(long long)arg2 completionBlock:(id)arg3;
- (double)_scrollBarWidth;
- (BOOL)validateToolbarItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)performTextFinderAction:(id)arg1;
- (void)makeFontSmaller:(id)arg1;
- (void)makeFontBigger:(id)arg1;
- (void)toggleViewRelatedMessages:(id)arg1;
- (id)actionViewController;
- (id)actionConversationMembers;
- (id)actionMessagesIncludingDuplicates:(BOOL)arg1;
- (id)_actionConversationMemberIndices;
- (void)_updateLastViewedDateAndMarkReadIfNeeded:(id)arg1;
- (void)_prepareToUpdateLastViewedDateAndMarkReadIfNeeded:(id)arg1 index:(unsigned long long)arg2;
- (void)_adjustHorizontalScrollersForCell:(id)arg1 forceShow:(BOOL)arg2;
- (void)_adjustHorizontalScrollersForceShow:(BOOL)arg1;
- (void)_hideAllHorizontalScrollers;
- (void)conversationView:(id)arg1 didEndScrollInScrollView:(id)arg2;
- (void)conversationView:(id)arg1 didScrollInScrollView:(id)arg2;
- (void)conversationView:(id)arg1 didBeginScrollInScrollView:(id)arg2;
- (void)conversationView:(id)arg1 didSelectIndex:(unsigned long long)arg2;
- (void)conversationView:(id)arg1 didRemoveCellView:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)conversationView:(id)arg1 didAddCellView:(id)arg2 atIndex:(unsigned long long)arg3;
- (double)conversationView:(id)arg1 initialHeightOfCellAtIndex:(unsigned long long)arg2;
- (void)_restoreMessageViewingState:(id)arg1;
- (void)_saveMessageViewingState:(id)arg1;
- (void)_updateCellViewAtIndexIfNeeded:(unsigned long long)arg1;
- (void)_cellViewFrameDidChange:(id)arg1;
- (void)_bodyContentViewGeometryDidChange:(id)arg1;
- (void)_loadNextIndex;
- (void)_performInitialPinning;
- (void)_updateConversationMembers:(id)arg1;
- (void)_resetConversationState;
- (void)_updateFirstResponderIfNeeded;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setView:(id)arg1;
- (id)view;
- (void)setRepresentedObject:(id)arg1 withFocusedMessage:(id)arg2;
- (void)setRepresentedObject:(id)arg1;
- (id)representedObject;
- (void)dealloc;
- (void)tearDown;
- (void)loadView;
- (void)_conversationViewControllerCommonInit;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

