/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class ConversationMember, MessageWebDocumentView, NSImage, NSMutableString, NSString;

@interface PrintingHTMLGenerator : NSObject
{
    NSMutableString *_headerTableHTML;
    NSString *_senderImageHTML;
    BOOL _shouldCollapseRedundantText;
    ConversationMember *_conversationMember;
    MessageWebDocumentView *_webDocumentView;
    NSImage *_senderImage;
    PrintingHTMLGenerator *_activeGenerator;
}

@property(retain, nonatomic) PrintingHTMLGenerator *activeGenerator; // @synthesize activeGenerator=_activeGenerator;
@property(retain, nonatomic) NSImage *senderImage; // @synthesize senderImage=_senderImage;
@property(nonatomic) BOOL shouldCollapseRedundantText; // @synthesize shouldCollapseRedundantText=_shouldCollapseRedundantText;
@property(nonatomic) MessageWebDocumentView *webDocumentView; // @synthesize webDocumentView=_webDocumentView;
@property(nonatomic) ConversationMember *conversationMember; // @synthesize conversationMember=_conversationMember;
- (id)_newHTMLAddressStringsFromAddressList:(id)arg1;
@property(readonly, nonatomic) NSString *senderImageHTML;
@property(readonly, nonatomic) NSString *headerTableHTML;
- (id)_newPrintHTMLUsingPrintingData:(id)arg1 base64EncodedDisplayHTML:(id)arg2;
- (id)_javascriptForPrintingData;
- (void)asyncLoadPrintingHTML:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithConversationMember:(id)arg1 webDocumentView:(id)arg2 shouldCollapseRedundantText:(BOOL)arg3;

@end

