#import <Cocoa/Cocoa.h>

#ifdef SNOW_LEOPARD_64

#import "MVTerminationHandler.h"

@interface MessageEditor : NSObject
{
}

+ (void)initialize;
+ (id)sharedMessageEditor;
- (id)init;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (id)objectSpecifier;
- (void)setBackEnd:(id)arg1;

@end

@class WebViewEditor;
@class HeadersEditor;
@class EditingMessageWebView;
@class ComposeBackEnd;
@class EditingWebMessageController;
@class LoadingOverlay;
@class MFUUID;
@class Message;

@interface DocumentEditor : NSObject <NSUserInterfaceValidations, NSWindowDelegate, MVTerminationHandler>
{
    WebViewEditor *webViewEditor;
    HeadersEditor *headersEditor;
    NSWindow *_window;
    EditingMessageWebView *composeWebView;
    ComposeBackEnd *_backEnd;
    NSToolbar *_toolbar;
    NSMutableDictionary *_toolbarItems;
    EditingWebMessageController *webMessageController;
    LoadingOverlay *loadingOverlay;
    NSDictionary *settings;
    struct {
        unsigned int userSavedMessage:1;
        unsigned int userWantsToCloseWindow:1;
        unsigned int userKnowsSaveFailed:1;
        unsigned int registeredForNotifications:1;
        unsigned int alwaysSave:1;
        unsigned int userCanApplyStationery:1;
        unsigned int autoShowEditor:1;
        unsigned int isLoaded:1;
        unsigned int isAutoSaving:1;
    } _flags;
    int _messageType;
    struct CGPoint _originalCascadePoint;
    NSMutableDictionary *_bodiesByAttachmentURL;
    NSOperationQueue *operationQueue;
    NSOperation *finishLoadingEditorOperation;
    id _loadDelegate;
}

+ (void)initialize;
+ (id)autoSaveTimer;
+ (void)setAutosaveTimer:(id)arg1;
+ (id)_documentEditors;
+ (id)documentEditors;
+ (id)typedDocumentEditors;
+ (void)registerDocumentEditor:(id)arg1;
+ (void)unregisterDocumentEditor:(id)arg1;
+ (BOOL)documentType;
+ (id)documentWebPreferencesIdentifierForRichText:(BOOL)arg1;
+ (id)existingEditorForMessage:(id)arg1 editorClass:(Class)arg2;
+ (id)editorsForDocumentID:(id)arg1 editorClass:(Class)arg2;
+ (id)existingEditorForMessage:(id)arg1;
+ (void)saveDefaults;
+ (void)restoreFromDefaults;
+ (void)showEditorWithSavedState:(id)arg1;
+ (void)setNeedsAutosave;
+ (void)autoSaveTimerFired;
@property(readonly) MFUUID *documentID;
- (BOOL)isEditingDocumentID:(id)arg1;
- (id)description;
- (id)initWithType:(int)arg1 settings:(id)arg2 backEnd:(id)arg3;
- (id)init;
@property(readonly) BOOL isLoaded;
- (void)setLoaded:(BOOL)arg1;
@property(readonly) BOOL isAutoSaving;
- (BOOL)load;
- (id)loadInterfaceOperation;
- (id)showInterfaceOperation;
- (id)prepareContentOperation;
- (id)loadInitialDocumentOperation;
- (void)loadInitialDocument;
- (id)finishLoadingEditorOperation;
@property(readonly) BOOL isFinishedLoading;
- (void)performOperationAfterLoad:(id)arg1;
- (void)finishLoadingEditor;
- (Class)backEndClass;
- (void)release;
- (void)dealloc;
- (BOOL)loadEditorNib;
- (id)operationQueue;
- (void)setOperationQueue:(id)arg1;
- (int)editorSharedNib;
- (void)show;
- (void)setHeaders:(id)arg1;
@property(retain) ComposeBackEnd *backEnd;
- (id)webViewEditor;
- (id)headersEditor;
- (id)webMessageDocument;
- (id)toolbar;
- (id)window;
@property BOOL autoShowEditor;
@property BOOL userCanApplyStationery;
@property(readonly) BOOL stationeryPaneIsVisible;
@property BOOL wantsToClose;
- (void)readDefaultsFromDictionary:(id)arg1;
- (void)writeDefaultsToDictionary:(id)arg1;
- (void)saveState;
- (void)_appendDefaultsToArray:(id)arg1;
- (id)_frameSaveName;
- (void)prepareContent;
- (void)backEndDidLoadInitialContent:(id)arg1;
- (id)parsedMessageFromSettings:(id)arg1;
- (void)continueLoadingInitialContent;
- (void)postDocumentEditorDidFinishSetup;
- (void)_registerForNotificationsIfNeeded;
- (void)_setupSpellingAndGrammarChecking;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)backEnd:(id)arg1 didBeginBackgroundLoadActivity:(id)arg2;
- (void)loadingOverlayDidEnd:(id)arg1 returnCode:(long long)arg2;
- (BOOL)autoSave;
@property(readonly) BOOL canSave;
@property(readonly) BOOL shouldSave;
- (void)saveMessageDueToUserAction:(BOOL)arg1;
- (void)backEnd:(id)arg1 willCreateMessageWithHeaders:(id)arg2;
- (BOOL)backEnd:(id)arg1 shouldSaveMessage:(id)arg2;
- (void)setUserSavedMessage:(BOOL)arg1;
@property(readonly) BOOL hasChanges;
- (void)reportSaveFailure:(id)arg1;
@property(readonly) Message *associatedMessage;
- (void)backEnd:(id)arg1 didUpdateMessage:(id)arg2;
- (void)backEndDidSaveMessage:(id)arg1 result:(int)arg2;
- (void)failedToSaveDraftSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)backEndDidChange:(id)arg1;
- (void)webViewDidChange:(id)arg1;
- (void)updateWindowContent;
- (void)updateUIAfterAppleScriptModification:(id)arg1;
- (void)composePrefsChanged;
- (id)mailAttachmentsAdded:(id)arg1;
- (void)openPanelSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)mimeBodyForAttachmentWithURL:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)makeRichText:(id)arg1;
- (void)makePlainText:(id)arg1;
- (void)toggleRich:(id)arg1;
- (void)insertNumberedList:(id)arg1;
- (void)insertBulletedList:(id)arg1;
- (void)convertToNumberedList:(id)arg1;
- (void)convertToBulletedList:(id)arg1;
- (void)increaseListNestingLevel:(id)arg1;
- (void)decreaseListNestingLevel:(id)arg1;
- (void)saveDocument:(id)arg1;
- (void)saveChangedDocument:(id)arg1;
- (void)saveMessageToDrafts:(id)arg1;
- (void)performClose:(id)arg1;
- (void)messageSizeDidChange:(id)arg1;
- (void)insertFile:(id)arg1;
- (void)removeAttachments:(id)arg1;
- (void)createToDo:(id)arg1;
- (void)changeTextEncoding:(id)arg1;
- (void)showPrintPanel:(id)arg1;
- (void)searchIndex:(id)arg1;
- (void)changeSpellCheckingBehavior:(id)arg1;
- (void)toggleCheckGrammarWithSpelling:(id)arg1;
- (void)showAddressPanel:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (id)shouldSaveTitle;
- (id)shouldSaveDescription;
- (id)shouldSaveHelptag;
- (void)beginDocumentMove;
- (void)endDocumentMove;
- (BOOL)windowShouldClose:(id)arg1;
- (void)forceClose;
- (void)closeConfirmSheetDidEnd:(id)arg1 returnCode:(long long)arg2 forSave:(void *)arg3;
- (void)nowWouldBeAGoodTimeToTerminate:(id)arg1;
@property id loadDelegate; // @synthesize loadDelegate=_loadDelegate;
@property(retain) NSDictionary *settings; // @synthesize settings;

@end

@interface DocumentEditor (DocumentEditorToolbar) <NSToolbarDelegate>
- (BOOL)validateToolbarItem:(id)arg1;
- (void)setupToolbar;
- (id)toolbarIdentifier;
- (void)_synchronizeChangeReplyItem:(id)arg1 messageType:(int)arg2;
- (void)toggleReplyType:(int)arg1;
- (void)updateSendButtonStateInToolbar;
- (void)toolbarWillAddItem:(id)arg1;
- (void)configureSegmentedItem:(id)arg1 withDictionary:(id)arg2 forSegment:(long long)arg3;
- (id)previousIdentifierForUpgradingToolbar:(id)arg1;
- (id)toolbar:(id)arg1 upgradedItemIdentifiers:(id)arg2;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)menuForListsItem;
@end

@class AccountStatusDataSourceDelegate;
@class MailDocumentEditor;
@class CompletionController;
@class ComposeHeaderView;
@class AccountStatusDataSource;
@class AddressTextField;
@class DraggingTextView;
@class DeliveryFailure;
@class StationerySelector;

@interface HeadersEditor : NSObject </*AccountStatusDataSourceDelegate, */NSUserInterfaceValidations>
{
    MailDocumentEditor *documentEditor;
    CompletionController *completionController;
    ComposeHeaderView *composeHeaderView;
    NSPopUpButton *fromPopup;
    NSPopUpButton *signaturePopup;
    NSPopUpButton *priorityPopup;
    NSButton *signButton;
    NSButton *encryptButton;
    AccountStatusDataSource *_deliveryASDS;
    NSPopUpButton *deliveryPopUp;
    AddressTextField *toField;
    AddressTextField *ccField;
    NSTextField *subjectField;
    AddressTextField *bccField;
    AddressTextField *replyToField;
    DraggingTextView *addressFieldEditor;
    NSMutableArray *accessoryViewOwners;
    BOOL chatShouldBeEnabled;
    BOOL _hasChanges;
}

+ (id)keyPathsForValuesAffectingDeliveryAccount;
- (void)awakeFromNib;
- (void)setUpFieldsAndButtons;
- (void)finishSetUp;
- (void)setAGoodFirstResponder;
- (void)configureButtonsAndPopUps;
- (void)initializePriorityPopUp;
- (void)composePrefsChanged;
- (void)mailAccountsDidChange;
- (void)accountInfoDidChange:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)updatePriorityPopUpMakeActive:(BOOL)arg1;
- (void)updateSecurityControls;
- (void)updateSignButtonImages;
- (void)updateSignButtonTooltip;
- (void)updateEncryptButtonImages;
- (void)updateEncryptButtonTooltip;
- (void)updateFromAndSignatureControls;
- (void)updateSignatureControlOverridingExistingSignature:(BOOL)arg1;
- (void)updateDeliveryAccountControl;
- (void)configureDeliveryPopupButton;
- (double)deliveryPopUpSizeToFitWidth;
- (void)updateCcOrBccMyselfFieldWithSender:(id)arg1 oldSender:(id)arg2;
- (void)updatePresenceButtonState;
- (void)presenceChanged:(id)arg1;
- (void)presencePreferenceChanged:(id)arg1;
- (void)updatePresenceButtonStateForAddresses:(id)arg1;
- (void)webViewDidLoadStationery:(id)arg1;
- (void)setupAddressField:(id)arg1;
- (void)_setupField:(id)arg1 withAddressesForKey:(id)arg2 visibleSelector:(SEL)arg3;
- (void)_configureTextField:(id)arg1 isAddressField:(BOOL)arg2;
- (id)fieldForHeader:(id)arg1;
- (id)headerKeyForView:(id)arg1;
- (void)enableCompletion:(BOOL)arg1 forTextField:(id)arg2;
- (void)loadHeadersFromBackEnd;
- (void)textFieldBeganOrEndedEditing:(id)arg1;
- (void)recipientsDidChange:(id)arg1;
- (void)subjectChanged;
- (void)addressFieldChanged;
- (BOOL)headerFieldIsNonEmpty:(id)arg1;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)setHeaders:(id)arg1;
- (void)appendAddresses:(id)arg1 toHeader:(id)arg2;
- (void)setInlineSpellCheckingEnabled:(BOOL)arg1;
- (void)setCheckGrammarWithSpelling:(BOOL)arg1;
- (void)turnOffEncryption;
- (void)changeSignatureFrom:(id)arg1 to:(id)arg2;
- (BOOL)messageIsToBeSigned;
- (BOOL)messageIsToBeEncrypted;
- (BOOL)messageHasRecipients;
- (BOOL)canSignFromAnyAccount;
- (BOOL)chatShouldBeEnabled;
- (BOOL)isOkayToSaveMessage:(id)arg1;
- (void)editServerList:(id)arg1 selectedAccount:(id)arg2;
- (void)toggleAccountLock:(id)arg1;
- (void)setSelectedAccount:(id)arg1;
- (id)deliveryAccount;
- (void)setDynamicDeliveryAccountForAccount:(id)arg1;
- (void)setDeliveryAccount:(id)arg1;
- (id)mailAccount;
- (void)accountStatusDidChange:(id)arg1;
- (void)changeHeaderField:(id)arg1;
- (void)changeFromHeader:(id)arg1;
- (void)setMessagePriority:(id)arg1;
- (void)securityControlChanged:(id)arg1;
- (void)_recipientsWithoutKeysSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)chatWithRecipients:(id)arg1;
- (void)editSignatures:(id)arg1;
- (void)changeSignature:(id)arg1;
- (void)composeHeaderViewWillBeginCustomization:(id)arg1;
- (void)composeHeaderViewDidEndCustomization:(id)arg1;
- (BOOL)headerCustomizationIsInProgress;
- (void)addCcHeader:(id)arg1;
- (void)addBccHeader:(id)arg1;
- (void)addReplyToHeader:(id)arg1;
- (void)_clearFieldIfHidden:(id)arg1;
- (void)prepareToCloseWindow;
- (void)dealloc;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)validateToolbarItem:(id)arg1;
- (id)createSenderMarkupStringIncludeBrackets:(BOOL)arg1;
@property BOOL hasChanges; // @synthesize hasChanges=_hasChanges;

@end

@class ColorBackgroundView;

@interface MailDocumentEditor : DocumentEditor <NSAnimationDelegate>
{
    DeliveryFailure *deliveryFailure;
    ColorBackgroundView *stationeryPane;
    StationerySelector *stationerySelector;
    NSTextField *stationeryNameTextField;
    NSButton *stationeryNameSaveButton;
    ColorBackgroundView *borderView;
    NSScroller *fakeScroller;
    NSViewAnimation *stationeryPaneAnimator;
    NSView *imageStatusView;
    NSTextField *imageFileSizeLabel;
    NSTextField *imageFileSizeTextField;
    NSPopUpButton *imageSizePopup;
    NSProgressIndicator *imageResizingProgressWheel;
    NSTextField *imageResizingProgressField;
    NSMutableArray *_imageResizers;
    unsigned long long _textLengthForLastEstimatedMessageSize;
    unsigned long long _encryptionOverhead;
    BOOL sendWhenFinishLoading;
    BOOL hasIncludedAttachmentsFromOriginal;
    NSMutableArray *_unapprovedRecipients;
    NSMutableArray *userActionQueue;
}

+ (BOOL)documentType;
+ (id)documentEditors;
+ (id)createEditorWithType:(int)arg1 settings:(id)arg2;
+ (void)restoreDraftMessage:(id)arg1 withSavedState:(id)arg2;
+ (void)emailAddressesApproved:(id)arg1;
+ (void)emailsRejected:(id)arg1;
+ (void)_emailAddresses:(id)arg1 approvedOrRejected:(BOOL)arg2;
+ (void)_setMessageStatus:(id)arg1 onMessageID:(id)arg2;
+ (void)handleFailedDeliveryOfMessage:(id)arg1 store:(id)arg2 error:(id)arg3;
+ (id)keyPathsForValuesAffectingDeliveryAccount;
- (id)init;
- (id)initWithBackEnd:(id)arg1;
- (id)initWithType:(int)arg1 settings:(id)arg2;
- (id)initWithType:(int)arg1 settings:(id)arg2 backEnd:(id)arg3;
- (BOOL)load;
- (void)finishLoadingEditor;
- (void)dealloc;
- (void)show;
- (int)messageType;
- (void)changeReplyMode:(id)arg1;
- (void)replyMessage:(id)arg1;
- (void)replyAllMessage:(id)arg1;
- (void)loadInitialDocument;
- (void)backEndDidLoadInitialContent:(id)arg1;
- (void)attachmentFinishedDownloading:(id)arg1;
- (id)document;
- (id)webView;
- (id)parsedMessageFromSettings:(id)arg1;
- (void)continueLoadingInitialContent;
- (double)animationDuration;
- (void)showOrHideStationery:(id)arg1;
- (void)animationDidEnd:(id)arg1;
- (BOOL)stationeryPaneIsVisible;
- (id)currentStationery;
- (void)loadStationery:(id)arg1;
- (void)saveAsStationery:(id)arg1;
- (void)continueSaveAsStationery:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)controlTextDidChange:(id)arg1;
- (void)cancelSaveAsStationery:(id)arg1;
- (void)saveSaveAsStationery:(id)arg1;
- (void)saveAsStationeryErrorSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(id)arg3;
- (BOOL)canSave;
- (void)saveMessageToDrafts:(id)arg1;
- (void)backEnd:(id)arg1 willCreateMessageWithHeaders:(id)arg2;
- (BOOL)backEnd:(id)arg1 shouldSaveMessage:(id)arg2;
- (void)backEndDidChange:(id)arg1;
- (void)backEndSenderDidChange:(id)arg1;
- (void)removeAttachments:(id)arg1;
- (void)insertOriginalAttachments:(id)arg1;
- (BOOL)_restoreOriginalAttachments;
- (void)alwaysSendWindowsFriendlyAttachments:(id)arg1;
- (void)sendWindowsFriendlyAttachments:(id)arg1;
- (void)_setSendWindowsFriendlyAttachments:(BOOL)arg1;
- (void)alwaysAttachFilesAtEnd:(id)arg1;
- (void)attachFilesAtEnd:(id)arg1;
- (void)insertFile:(id)arg1;
- (void)openPanelSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)_sendButtonShouldBeEnabled;
- (void)_setUnapprovedRecipients:(id)arg1;
- (void)askApprovalSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)send:(id)arg1;
- (void)sendMessageAfterChecking:(id)arg1;
- (void)backEndDidCancelMessageDeliveryForAttachmentError:(id)arg1;
- (void)attachmentErrorSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)cancelSendingStationery:(id)arg1;
- (void)continueSendingStationery:(id)arg1;
- (void)emptyMessageSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)malformedAddressSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)noRecipientsSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)backEndDidAppendMessageToOutbox:(id)arg1 result:(int)arg2;
- (void)failedToAppendToOutboxSheetClosed:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (BOOL)backEnd:(id)arg1 shouldDeliverMessage:(id)arg2;
- (void)_setMessageStatusOnOriginalMessage;
- (void)backEnd:(id)arg1 didCancelMessageDeliveryForError:(id)arg2;
- (void)reportDeliveryFailure:(id)arg1;
- (void)forceClose;
- (void)backEnd:(id)arg1 didCancelMessageDeliveryForMissingCertificatesForRecipients:(id)arg2;
- (id)missingCertificatesMessageForRecipients:(id)arg1 uponDelivery:(BOOL)arg2;
- (void)backEnd:(id)arg1 didCancelMessageDeliveryForEncryptionError:(id)arg2;
- (void)shouldDeliverMessageAlertWithoutEncryptionSheetDidDismiss:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)deliveryAccount;
- (void)setDeliveryAccount:(id)arg1;
- (void)changeSignature:(id)arg1;
- (void)imageSizePopupChanged:(id)arg1;
- (void)messageSizeDidChange:(id)arg1;
- (void)encryptionStatusDidChange;
- (void)updateAttachmentStatus;
- (unsigned char)_isAttachmentScalable:(id)arg1;
- (unsigned char)_attachmentsContainScalableImage:(id)arg1 scalables:(id)arg2;
- (void)_updateImageSizePopup;
- (BOOL)_imageStatusHidden;
- (void)_showImageStatusView;
- (void)_hideImageStatusView;
- (struct CGSize)_imageSizeForTag:(long long)arg1;
- (struct CGSize)_selectedImageSize;
- (id)_maxImageSizeAsString;
- (void)_processNextImageResizer;
- (void)_ImageResizeDidFinish:(id)arg1;
- (BOOL)_isResizingImages;
- (id)_resizerForAttachment:(id)arg1;
- (BOOL)_resizeAttachment:(id)arg1;
- (BOOL)_resizeImageAttachments:(id)arg1;
- (unsigned long long)textLengthEstimate;
- (unsigned long long)_signatureOverhead;
- (unsigned long long)_encryptionOverhead;
- (unsigned long long)_estimateMessageSize;
- (void)_saveImageSizeToDefaults;
- (void)_setImageSizePopupToSize:(id)arg1;
- (id)attachmentStatusNeighbourView;
- (void)_mailAttachmentsDeleted;
- (void)mailAttachmentsDeleted:(id)arg1;
- (id)mailAttachmentsAdded:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)appendMessages:(id)arg1;
- (void)appendMessageArray:(id)arg1;
- (void)_appendMessages:(id)arg1 withParsedMessages:(id)arg2;
- (void)_generateParsedMessagesToAppendForMessages:(id)arg1;
- (void)makeRichText:(id)arg1;
- (void)makePlainText:(id)arg1;
- (void)makeFontBigger:(id)arg1;
- (void)makeFontSmaller:(id)arg1;
- (void)addCcHeader:(id)arg1;
- (void)addBccHeader:(id)arg1;
- (void)addReplyToHeader:(id)arg1;
- (void)setMessagePriority:(id)arg1;

@end

#elif defined(SNOW_LEOPARD)

#import "MVTerminationHandler.h"

@class WebViewEditor;
@class HeadersEditor;
@class EditingMessageWebView;
@class ComposeBackEnd;
@class EditingWebMessageController;
@class LoadingOverlay;
@class DeliveryFailure;
@class ColorBackgroundView;
@class StationerySelector;
@class HeadersEditor;
@class CompletionController;
@class ComposeHeaderView;
@class AccountStatusDataSource;
@class AddressTextField;
@class DraggingTextView;

@interface MessageEditor : NSObject
{
}

+ (void)initialize;
+ (id)sharedMessageEditor;
- (id)init;
- (id)retain;
- (unsigned long)retainCount;
- (void)release;
- (id)autorelease;
- (id)objectSpecifier;
- (void)setBackEnd:(id)arg1;

@end

@interface DocumentEditor : NSObject <NSUserInterfaceValidations, NSWindowDelegate, MVTerminationHandler>
{
    WebViewEditor *webViewEditor;
    HeadersEditor *headersEditor;
    NSWindow *_window;
    EditingMessageWebView *composeWebView;
    ComposeBackEnd *_backEnd;
    NSToolbar *_toolbar;
    NSMutableDictionary *_toolbarItems;
    EditingWebMessageController *webMessageController;
    LoadingOverlay *loadingOverlay;
    NSDictionary *settings;
    struct {
        unsigned int userSavedMessage:1;
        unsigned int userWantsToCloseWindow:1;
        unsigned int userKnowsSaveFailed:1;
        unsigned int registeredForNotifications:1;
        unsigned int alwaysSave:1;
        unsigned int userCanApplyStationery:1;
        unsigned int autoShowEditor:1;
        unsigned int isLoaded:1;
        unsigned int isAutoSaving:1;
    } _flags;
    int _messageType;
    struct CGPoint _originalCascadePoint;
    NSMutableDictionary *_bodiesByAttachmentURL;
    NSOperationQueue *operationQueue;
    NSOperation *finishLoadingEditorOperation;
    id _loadDelegate;
}

+ (void)initialize;
+ (id)autoSaveTimer;
+ (void)setAutosaveTimer:(id)arg1;
+ (id)_documentEditors;
+ (id)documentEditors;
+ (id)typedDocumentEditors;
+ (void)registerDocumentEditor:(id)arg1;
+ (void)unregisterDocumentEditor:(id)arg1;
+ (BOOL)documentType;
+ (id)documentWebPreferencesIdentifierForRichText:(BOOL)arg1;
+ (id)existingEditorForMessage:(id)arg1 editorClass:(Class)arg2;
+ (id)editorsForDocumentID:(id)arg1 editorClass:(Class)arg2;
+ (id)existingEditorForMessage:(id)arg1;
+ (void)saveDefaults;
+ (void)restoreFromDefaults;
+ (void)showEditorWithSavedState:(id)arg1;
+ (void)setNeedsAutosave;
+ (void)autoSaveTimerFired;
- (id)documentID;
- (BOOL)isEditingDocumentID:(id)arg1;
- (id)description;
- (id)initWithType:(int)arg1 settings:(id)arg2 backEnd:(id)arg3;
- (id)init;
- (BOOL)isLoaded;
- (void)setLoaded:(BOOL)arg1;
- (BOOL)isAutoSaving;
- (BOOL)load;
- (id)loadInterfaceOperation;
- (id)showInterfaceOperation;
- (id)prepareContentOperation;
- (id)loadInitialDocumentOperation;
- (void)loadInitialDocument;
- (id)finishLoadingEditorOperation;
- (BOOL)isFinishedLoading;
- (void)performOperationAfterLoad:(id)arg1;
- (void)finishLoadingEditor;
- (Class)backEndClass;
- (void)release;
- (void)dealloc;
- (BOOL)loadEditorNib;
- (id)operationQueue;
- (void)setOperationQueue:(id)arg1;
- (int)editorSharedNib;
- (void)show;
- (void)setHeaders:(id)arg1;
- (id)backEnd;
- (void)setBackEnd:(id)arg1;
- (id)webViewEditor;
- (id)headersEditor;
- (id)webMessageDocument;
- (id)toolbar;
- (id)window;
- (BOOL)autoShowEditor;
- (void)setAutoShowEditor:(BOOL)arg1;
- (BOOL)userCanApplyStationery;
- (void)setUserCanApplyStationery:(BOOL)arg1;
- (BOOL)stationeryPaneIsVisible;
- (BOOL)wantsToClose;
- (void)setWantsToClose:(BOOL)arg1;
- (void)readDefaultsFromDictionary:(id)arg1;
- (void)writeDefaultsToDictionary:(id)arg1;
- (void)saveState;
- (void)_appendDefaultsToArray:(id)arg1;
- (id)_frameSaveName;
- (void)prepareContent;
- (void)backEndDidLoadInitialContent:(id)arg1;
- (id)parsedMessageFromSettings:(id)arg1;
- (void)continueLoadingInitialContent;
- (void)postDocumentEditorDidFinishSetup;
- (void)_registerForNotificationsIfNeeded;
- (void)_setupSpellingAndGrammarChecking;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)backEnd:(id)arg1 didBeginBackgroundLoadActivity:(id)arg2;
- (void)loadingOverlayDidEnd:(id)arg1 returnCode:(long)arg2;
- (BOOL)autoSave;
- (BOOL)canSave;
- (BOOL)shouldSave;
- (void)saveMessageDueToUserAction:(BOOL)arg1;
- (void)backEnd:(id)arg1 willCreateMessageWithHeaders:(id)arg2;
- (BOOL)backEnd:(id)arg1 shouldSaveMessage:(id)arg2;
- (void)setUserSavedMessage:(BOOL)arg1;
- (BOOL)hasChanges;
- (void)reportSaveFailure:(id)arg1;
- (id)associatedMessage;
- (void)backEnd:(id)arg1 didUpdateMessage:(id)arg2;
- (void)backEndDidSaveMessage:(id)arg1 result:(int)arg2;
- (void)failedToSaveDraftSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)backEndDidChange:(id)arg1;
- (void)webViewDidChange:(id)arg1;
- (void)updateWindowContent;
- (void)updateUIAfterAppleScriptModification:(id)arg1;
- (void)composePrefsChanged;
- (id)mailAttachmentsAdded:(id)arg1;
- (void)openPanelSheetDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (id)mimeBodyForAttachmentWithURL:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)makeRichText:(id)arg1;
- (void)makePlainText:(id)arg1;
- (void)toggleRich:(id)arg1;
- (void)insertNumberedList:(id)arg1;
- (void)insertBulletedList:(id)arg1;
- (void)convertToNumberedList:(id)arg1;
- (void)convertToBulletedList:(id)arg1;
- (void)increaseListNestingLevel:(id)arg1;
- (void)decreaseListNestingLevel:(id)arg1;
- (void)saveDocument:(id)arg1;
- (void)saveChangedDocument:(id)arg1;
- (void)saveMessageToDrafts:(id)arg1;
- (void)performClose:(id)arg1;
- (void)messageSizeDidChange:(id)arg1;
- (void)insertFile:(id)arg1;
- (void)removeAttachments:(id)arg1;
- (void)createToDo:(id)arg1;
- (void)changeTextEncoding:(id)arg1;
- (void)showPrintPanel:(id)arg1;
- (void)searchIndex:(id)arg1;
- (void)changeSpellCheckingBehavior:(id)arg1;
- (void)toggleCheckGrammarWithSpelling:(id)arg1;
- (void)showAddressPanel:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (id)shouldSaveTitle;
- (id)shouldSaveDescription;
- (id)shouldSaveHelptag;
- (void)beginDocumentMove;
- (void)endDocumentMove;
- (BOOL)windowShouldClose:(id)arg1;
- (void)forceClose;
- (void)closeConfirmSheetDidEnd:(id)arg1 returnCode:(long)arg2 forSave:(void *)arg3;
- (void)nowWouldBeAGoodTimeToTerminate:(id)arg1;
- (id)loadDelegate;
- (void)setLoadDelegate:(id)arg1;
- (id)settings;
- (void)setSettings:(id)arg1;

@end

@interface DocumentEditor (DocumentEditorToolbar) <NSToolbarDelegate>
- (BOOL)validateToolbarItem:(id)arg1;
- (void)setupToolbar;
- (id)toolbarIdentifier;
- (void)_synchronizeChangeReplyItem:(id)arg1 messageType:(int)arg2;
- (void)toggleReplyType:(int)arg1;
- (void)updateSendButtonStateInToolbar;
- (void)toolbarWillAddItem:(id)arg1;
- (void)configureSegmentedItem:(id)arg1 withDictionary:(id)arg2 forSegment:(long)arg3;
- (id)previousIdentifierForUpgradingToolbar:(id)arg1;
- (id)toolbar:(id)arg1 upgradedItemIdentifiers:(id)arg2;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)menuForListsItem;
@end

@interface MailDocumentEditor : DocumentEditor <NSAnimationDelegate>
{
    DeliveryFailure *deliveryFailure;
    ColorBackgroundView *stationeryPane;
    StationerySelector *stationerySelector;
    NSTextField *stationeryNameTextField;
    NSButton *stationeryNameSaveButton;
    ColorBackgroundView *borderView;
    NSScroller *fakeScroller;
    NSViewAnimation *stationeryPaneAnimator;
    NSView *imageStatusView;
    NSTextField *imageFileSizeLabel;
    NSTextField *imageFileSizeTextField;
    NSPopUpButton *imageSizePopup;
    NSProgressIndicator *imageResizingProgressWheel;
    NSTextField *imageResizingProgressField;
    NSMutableArray *_imageResizers;
    unsigned int _textLengthForLastEstimatedMessageSize;
    unsigned int _encryptionOverhead;
    BOOL sendWhenFinishLoading;
    BOOL hasIncludedAttachmentsFromOriginal;
    NSMutableArray *_unapprovedRecipients;
    NSMutableArray *userActionQueue;
}

+ (BOOL)documentType;
+ (id)documentEditors;
+ (id)createEditorWithType:(int)arg1 settings:(id)arg2;
+ (void)restoreDraftMessage:(id)arg1 withSavedState:(id)arg2;
+ (void)emailAddressesApproved:(id)arg1;
+ (void)emailsRejected:(id)arg1;
+ (void)_emailAddresses:(id)arg1 approvedOrRejected:(BOOL)arg2;
+ (void)_setMessageStatus:(id)arg1 onMessageID:(id)arg2;
+ (void)handleFailedDeliveryOfMessage:(id)arg1 store:(id)arg2 error:(id)arg3;
+ (id)keyPathsForValuesAffectingDeliveryAccount;
- (id)init;
- (id)initWithBackEnd:(id)arg1;
- (id)initWithType:(int)arg1 settings:(id)arg2;
- (id)initWithType:(int)arg1 settings:(id)arg2 backEnd:(id)arg3;
- (BOOL)load;
- (void)finishLoadingEditor;
- (void)dealloc;
- (void)show;
- (int)messageType;
- (void)changeReplyMode:(id)arg1;
- (void)replyMessage:(id)arg1;
- (void)replyAllMessage:(id)arg1;
- (void)loadInitialDocument;
- (void)backEndDidLoadInitialContent:(id)arg1;
- (void)attachmentFinishedDownloading:(id)arg1;
- (id)document;
- (id)webView;
- (id)parsedMessageFromSettings:(id)arg1;
- (void)continueLoadingInitialContent;
- (double)animationDuration;
- (void)showOrHideStationery:(id)arg1;
- (void)animationDidEnd:(id)arg1;
- (BOOL)stationeryPaneIsVisible;
- (id)currentStationery;
- (void)loadStationery:(id)arg1;
- (void)saveAsStationery:(id)arg1;
- (void)continueSaveAsStationery:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)controlTextDidChange:(id)arg1;
- (void)cancelSaveAsStationery:(id)arg1;
- (void)saveSaveAsStationery:(id)arg1;
- (void)saveAsStationeryErrorSheetDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(id)arg3;
- (BOOL)canSave;
- (void)saveMessageToDrafts:(id)arg1;
- (void)backEnd:(id)arg1 willCreateMessageWithHeaders:(id)arg2;
- (BOOL)backEnd:(id)arg1 shouldSaveMessage:(id)arg2;
- (void)backEndDidChange:(id)arg1;
- (void)backEndSenderDidChange:(id)arg1;
- (void)removeAttachments:(id)arg1;
- (void)insertOriginalAttachments:(id)arg1;
- (BOOL)_restoreOriginalAttachments;
- (void)alwaysSendWindowsFriendlyAttachments:(id)arg1;
- (void)sendWindowsFriendlyAttachments:(id)arg1;
- (void)_setSendWindowsFriendlyAttachments:(BOOL)arg1;
- (void)alwaysAttachFilesAtEnd:(id)arg1;
- (void)attachFilesAtEnd:(id)arg1;
- (void)insertFile:(id)arg1;
- (void)openPanelSheetDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)_sendButtonShouldBeEnabled;
- (void)_setUnapprovedRecipients:(id)arg1;
- (void)askApprovalSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)send:(id)arg1;
- (void)sendMessageAfterChecking:(id)arg1;
- (void)backEndDidCancelMessageDeliveryForAttachmentError:(id)arg1;
- (void)attachmentErrorSheetDidEnd:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)cancelSendingStationery:(id)arg1;
- (void)continueSendingStationery:(id)arg1;
- (void)emptyMessageSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)malformedAddressSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)noRecipientsSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)backEndDidAppendMessageToOutbox:(id)arg1 result:(int)arg2;
- (void)failedToAppendToOutboxSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (BOOL)backEnd:(id)arg1 shouldDeliverMessage:(id)arg2;
- (void)_setMessageStatusOnOriginalMessage;
- (void)backEnd:(id)arg1 didCancelMessageDeliveryForError:(id)arg2;
- (void)reportDeliveryFailure:(id)arg1;
- (void)forceClose;
- (void)backEnd:(id)arg1 didCancelMessageDeliveryForMissingCertificatesForRecipients:(id)arg2;
- (id)missingCertificatesMessageForRecipients:(id)arg1 uponDelivery:(BOOL)arg2;
- (void)backEnd:(id)arg1 didCancelMessageDeliveryForEncryptionError:(id)arg2;
- (void)shouldDeliverMessageAlertWithoutEncryptionSheetDidDismiss:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (id)deliveryAccount;
- (void)setDeliveryAccount:(id)arg1;
- (void)changeSignature:(id)arg1;
- (void)imageSizePopupChanged:(id)arg1;
- (void)messageSizeDidChange:(id)arg1;
- (void)encryptionStatusDidChange;
- (void)updateAttachmentStatus;
- (unsigned char)_isAttachmentScalable:(id)arg1;
- (unsigned char)_attachmentsContainScalableImage:(id)arg1 scalables:(id)arg2;
- (void)_updateImageSizePopup;
- (BOOL)_imageStatusHidden;
- (void)_showImageStatusView;
- (void)_hideImageStatusView;
- (struct CGSize)_imageSizeForTag:(long)arg1;
- (struct CGSize)_selectedImageSize;
- (id)_maxImageSizeAsString;
- (void)_processNextImageResizer;
- (void)_ImageResizeDidFinish:(id)arg1;
- (BOOL)_isResizingImages;
- (id)_resizerForAttachment:(id)arg1;
- (BOOL)_resizeAttachment:(id)arg1;
- (BOOL)_resizeImageAttachments:(id)arg1;
- (unsigned long)textLengthEstimate;
- (unsigned long)_signatureOverhead;
- (unsigned long)_encryptionOverhead;
- (unsigned long long)_estimateMessageSize;
- (void)_saveImageSizeToDefaults;
- (void)_setImageSizePopupToSize:(id)arg1;
- (id)attachmentStatusNeighbourView;
- (void)_mailAttachmentsDeleted;
- (void)mailAttachmentsDeleted:(id)arg1;
- (id)mailAttachmentsAdded:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)appendMessages:(id)arg1;
- (void)appendMessageArray:(id)arg1;
- (void)_appendMessages:(id)arg1 withParsedMessages:(id)arg2;
- (void)_generateParsedMessagesToAppendForMessages:(id)arg1;
- (void)makeRichText:(id)arg1;
- (void)makePlainText:(id)arg1;
- (void)makeFontBigger:(id)arg1;
- (void)makeFontSmaller:(id)arg1;
- (void)addCcHeader:(id)arg1;
- (void)addBccHeader:(id)arg1;
- (void)addReplyToHeader:(id)arg1;
- (void)setMessagePriority:(id)arg1;

@end

@interface HeadersEditor : NSObject /*<AccountStatusDataSourceDelegate, NSUserInterfaceValidations>*/<NSUserInterfaceValidations>
{
    MailDocumentEditor *documentEditor;
    CompletionController *completionController;
    ComposeHeaderView *composeHeaderView;
    NSPopUpButton *fromPopup;
    NSPopUpButton *signaturePopup;
    NSPopUpButton *priorityPopup;
    NSButton *signButton;
    NSButton *encryptButton;
    AccountStatusDataSource *_deliveryASDS;
    NSPopUpButton *deliveryPopUp;
    AddressTextField *toField;
    AddressTextField *ccField;
    NSTextField *subjectField;
    AddressTextField *bccField;
    AddressTextField *replyToField;
    DraggingTextView *addressFieldEditor;
    NSMutableArray *accessoryViewOwners;
    BOOL chatShouldBeEnabled;
    BOOL _hasChanges;
}

+ (id)keyPathsForValuesAffectingDeliveryAccount;
- (void)awakeFromNib;
- (void)setUpFieldsAndButtons;
- (void)finishSetUp;
- (void)setAGoodFirstResponder;
- (void)configureButtonsAndPopUps;
- (void)initializePriorityPopUp;
- (void)composePrefsChanged;
- (void)mailAccountsDidChange;
- (void)accountInfoDidChange:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)updatePriorityPopUpMakeActive:(BOOL)arg1;
- (void)updateSecurityControls;
- (void)updateSignButtonImages;
- (void)updateSignButtonTooltip;
- (void)updateEncryptButtonImages;
- (void)updateEncryptButtonTooltip;
- (void)updateFromAndSignatureControls;
- (void)updateSignatureControlOverridingExistingSignature:(BOOL)arg1;
- (void)updateDeliveryAccountControl;
- (void)configureDeliveryPopupButton;
- (float)deliveryPopUpSizeToFitWidth;
- (void)updateCcOrBccMyselfFieldWithSender:(id)arg1 oldSender:(id)arg2;
- (void)updatePresenceButtonState;
- (void)presenceChanged:(id)arg1;
- (void)presencePreferenceChanged:(id)arg1;
- (void)updatePresenceButtonStateForAddresses:(id)arg1;
- (void)webViewDidLoadStationery:(id)arg1;
- (void)setupAddressField:(id)arg1;
- (void)_setupField:(id)arg1 withAddressesForKey:(id)arg2 visibleSelector:(SEL)arg3;
- (void)_configureTextField:(id)arg1 isAddressField:(BOOL)arg2;
- (id)fieldForHeader:(id)arg1;
- (id)headerKeyForView:(id)arg1;
- (void)enableCompletion:(BOOL)arg1 forTextField:(id)arg2;
- (void)loadHeadersFromBackEnd;
- (void)textFieldBeganOrEndedEditing:(id)arg1;
- (void)recipientsDidChange:(id)arg1;
- (void)subjectChanged;
- (void)addressFieldChanged;
- (BOOL)headerFieldIsNonEmpty:(id)arg1;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)setHeaders:(id)arg1;
- (void)appendAddresses:(id)arg1 toHeader:(id)arg2;
- (void)setInlineSpellCheckingEnabled:(BOOL)arg1;
- (void)setCheckGrammarWithSpelling:(BOOL)arg1;
- (void)turnOffEncryption;
- (void)changeSignatureFrom:(id)arg1 to:(id)arg2;
- (BOOL)messageIsToBeSigned;
- (BOOL)messageIsToBeEncrypted;
- (BOOL)messageHasRecipients;
- (BOOL)canSignFromAnyAccount;
- (BOOL)chatShouldBeEnabled;
- (BOOL)isOkayToSaveMessage:(id)arg1;
- (void)editServerList:(id)arg1 selectedAccount:(id)arg2;
- (void)toggleAccountLock:(id)arg1;
- (void)setSelectedAccount:(id)arg1;
- (id)deliveryAccount;
- (void)setDynamicDeliveryAccountForAccount:(id)arg1;
- (void)setDeliveryAccount:(id)arg1;
- (id)mailAccount;
- (void)accountStatusDidChange:(id)arg1;
- (void)changeHeaderField:(id)arg1;
- (void)changeFromHeader:(id)arg1;
- (void)setMessagePriority:(id)arg1;
- (void)securityControlChanged:(id)arg1;
- (void)_recipientsWithoutKeysSheetClosed:(id)arg1 returnCode:(long)arg2 contextInfo:(void *)arg3;
- (void)chatWithRecipients:(id)arg1;
- (void)editSignatures:(id)arg1;
- (void)changeSignature:(id)arg1;
- (void)composeHeaderViewWillBeginCustomization:(id)arg1;
- (void)composeHeaderViewDidEndCustomization:(id)arg1;
- (BOOL)headerCustomizationIsInProgress;
- (void)addCcHeader:(id)arg1;
- (void)addBccHeader:(id)arg1;
- (void)addReplyToHeader:(id)arg1;
- (void)_clearFieldIfHidden:(id)arg1;
- (void)prepareToCloseWindow;
- (void)dealloc;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)validateToolbarItem:(id)arg1;
- (id)createSenderMarkupStringIncludeBrackets:(BOOL)arg1;
- (BOOL)hasChanges;
- (void)setHasChanges:(BOOL)arg1;

@end

#endif
