/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MCChanging.h"

@protocol IMAPPersistedMessage <MCChanging>
@property(readonly) BOOL persistentIDType;
- (void)appendData:(id)arg1 part:(id)arg2;
- (void)setData:(id)arg1 isPartial:(BOOL)arg2;
- (void)setRemoteID:(id)arg1;
- (id)remoteID;

@optional
- (id)managedObjectID;
- (long long)libraryID;
@end

