/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSButtonCell.h"

@class NSPopUpButtonCell;

@interface _SortBarButtonCell : NSButtonCell
{
    BOOL _showingPopUpMenu;
    NSPopUpButtonCell *_popUpCell;
}

@property(readonly, nonatomic) NSPopUpButtonCell *popUpCell; // @synthesize popUpCell=_popUpCell;
- (void).cxx_destruct;
- (BOOL)accessibilityPerformShowMenuAction;
- (BOOL)accessibilityPerformPress;
- (BOOL)accessibilityPerformShowMenu;
- (id)accessibilityRole;
- (id)accessibilityChildren;
- (id)accessibilityValue;
- (BOOL)isAccessibilitySelectorAllowed:(SEL)arg1;
- (void)runPopUpInView:(id)arg1;
- (void)showPopUpMenuForButton:(id)arg1;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGSize)cellSize;
- (id)indicatorImage;
- (id)engravingColor;
- (id)foregroundTextColor;
- (double)titleHorizontalInset;
- (double)titleVerticalOffset;
- (double)textToImageSpace;
- (double)insetForMenuArrowImage;
- (double)insetForHighlightY;
- (double)insetForHighlightX;
- (void)sortBarButtonCellCommonInit;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

