/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "VerticallyCenteredTextFieldCell.h"

@interface FlatTableViewDataCell : VerticallyCenteredTextFieldCell
{
}

- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (id)textColor;

@end

