/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MCRemoteStoreAccount.h"

@class IMAPTaskManager, MCError, NSArray, NSDictionary, NSString;

@protocol IMAPAccount <MCRemoteStoreAccount>
@property(copy) NSString *serverPathPrefix;
@property BOOL supportsQuickResynchronization;
@property(readonly, copy, nonatomic) NSArray *allBackgroundMailboxNames;
@property(readonly) BOOL shouldMoveDeletedMessagesToTrash;
@property(readonly) BOOL allowsPartialDownloads;
@property(readonly) id <IMAPOfflineCache> offlineCache;
@property(copy) NSDictionary *serverID;
@property(retain) MCError *connectionError;
@property BOOL useIDLEIfAvailable;
@property(readonly, nonatomic) IMAPTaskManager *taskManager;
- (void)setSupportsModificationSequences:(BOOL)arg1 forMailboxName:(id)arg2;
- (id)mailboxForName:(id)arg1;
- (id)dataSourceForMailboxName:(id)arg1;
- (void)recoverFromConnectionlessStateWithServerInterface:(id)arg1;
- (void)setSeparatorCharIfNeededWithServerInterface:(id)arg1;
- (void)backgroundFetchCompleted;
- (void)sendAccountNeedsCheckingNotification;
- (id)quotaRootForName:(id)arg1 createIfNeeded:(BOOL)arg2;
- (BOOL)handleResponseCodeFromResponse:(id)arg1;
- (id)IMAPMailboxForMailboxName:(id)arg1 createIfNeeded:(BOOL)arg2;
- (id)separatorCharFetchIfNeeded:(BOOL)arg1;

@optional
- (void)detectAllMailMailboxWithConnection:(id)arg1;
- (id)gmailLabelWithName:(id)arg1;
@end

