/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MFEWSRetrievePersistedFolderDataDelegate <NSObject>
- (void)retrievePersistedFolderDataOperation:(id)arg1 didRetrieveFolderIDsByURL:(id)arg2 syncStatesByURL:(id)arg3 missedMailboxURLs:(id)arg4;
@end

