#!/bin/bash

NEW_HOME="$HOME"
if [ "$UID" == "0" ]; then
	NEW_HOME=""
fi
LOGFILE="$HOME/Library/Logs/gpgmail-uuid-patcher.log"

function log {
    current_date=$(date "+%Y-%m-%d %H:%M:%S")
    echo "$current_date: $1"
    if [[ "$2" != "" ]]; then
        echo ""
    fi
}

function gpgMailInstallPath {
    sysdir="/Library/Mail/Bundles"
    netdir="/Network/Library/Mail/Bundles"
    homedir="$HOME/Library/Mail/Bundles"
    bundle="GPGMail.mailbundle"
    
    existingInstallationAt=""

    if [[ -e "$netdir/$bundle" ]]; then
        existingInstallationAt="$netdir"
    elif [[ -e "$homedir/$bundle" ]]; then
        existingInstallationAt="$homedir"
    elif [[ -e "$sysdir/$bundle" ]]; then
        existingInstallationAt="$sysdir"
    else
        existingInstallationAt=""
    fi
    
    echo $existingInstallationAt
}

function updatePlistWithUUIDIfNecessary {
    plist="$1"
    uuid="$2"
    
    if ! grep -q $uuid "$plist.plist"; then
        echo "[uuid-patcher] Adding UUID $uuid to $plist"
        defaults write "$plist" "SupportedPluginCompatibilityUUIDs" -array-add "$uuid"
        plutil -convert xml1 "$plist.plist"
        chmod a+r "$plist.plist"
    else
        echo "[uuid-patcher] UUID $uuid is already available. No need to update plist."
    fi
}

function patchUUIDs {
    echo "[uuid-patcher] Trying to find GPGMail bundle..."
    # Location of the GPGMail bundle
    bundlePath=$(gpgMailInstallPath)
    bundle="GPGMail.mailbundle"
    
    if [ -z "$bundlePath" ]; then
        echo "[uuid-patcher] GPGMail not installed"
        return
    fi
    
    bundlePath="$bundlePath/$bundle"
    
    echo "[uuid-patcher] Found GPGMail in $bundlePath"
    
	# Find Mail.app
	mailLocation=$(mdfind -onlyin /Applications "kMDItemCFBundleIdentifier = com.apple.mail" | head -1)
	mailLocation=${mailLocation:-/Applications/Mail.app}
	
    # Fetch the Mail UUID and the Message.framework UUID
    plistMail="$mailLocation/Contents/Info"
    plistFramework="/System/Library/Frameworks/Message.framework/Resources/Info"
    uuid1=$(defaults read "$plistMail" "PluginCompatibilityUUID")
    uuid2=$(defaults read "$plistFramework" "PluginCompatibilityUUID")
    
    echo "[uuid-patcher] Following UUIDs found: $uuid1 $uuid2"
    
    if [ ! -z "$uuid1" ]; then
        updatePlistWithUUIDIfNecessary "$bundlePath/Contents/Info" $uuid1
    fi
    
    if [ ! -z "$uuid2" ]; then
        updatePlistWithUUIDIfNecessary "$bundlePath/Contents/Info" $uuid2
    fi

}
function enableBundles {
    echo "[uuid-patcher] Enable bundles!"
	
	case "$(sw_vers -productVersion | cut -d . -f 2)" in
		9) bundleCompVer=7 ;;
		8) bundleCompVer=6 ;;
		7) bundleCompVer=5 ;;
		6) bundleCompVer=4 ;;
		*) bundleCompVer=3 ;;
	esac

	defaults write com.apple.mail EnableBundles -bool YES
	defaults write com.apple.mail BundleCompatibilityVersion -int $bundleCompVer
}


# Setting up the logfile.
exec >> $LOGFILE 2>&1

if [ "$1" == "enable-bundles" ]; then
    enableBundles
else
    patchUUIDs
fi

echo "[uuid-patcher] Done!"


exit 0
